"""NumPy/PyTorch 矩阵运算强化题定义。"""

from __future__ import annotations


NUMPY_MATRIX_CASES = [
    (
        "matmul维度规则",
        ["分别完成向量点积、矩阵乘向量、矩阵乘矩阵。", "写出每种输入和输出 shape。", "用断言验证手算结果。"],
        [
            "import numpy as np  # 导入 NumPy。",
            "vector = np.array([1.0, 2.0, 3.0])  # 创建 shape=(3,) 的向量。",
            "matrix = np.array([[1.0, 0.0, 2.0], [0.0, 1.0, 3.0]])  # 创建 shape=(2,3) 的矩阵。",
            "dot = vector @ vector  # (3,)@(3,) 收缩唯一轴并得到标量。",
            "matrix_vector = matrix @ vector  # (2,3)@(3,) 得到 shape=(2,)。",
            "matrix_matrix = matrix @ matrix.T  # (2,3)@(3,2) 得到 shape=(2,2)。",
            "assert dot == 14.0 and matrix_vector.shape == (2,) and matrix_matrix.shape == (2, 2)  # 核对值与 shape。",
            "print(dot, matrix_vector, matrix_matrix)  # 输出三类乘法结果。",
        ],
    ),
    (
        "multiply_dot与matmul区别",
        ["比较逐元素乘法与矩阵乘法。", "比较二维数组上的 dot、matmul 和 @。", "说明不能把星号当矩阵乘法。"],
        [
            "import numpy as np  # 导入 NumPy。",
            "left = np.array([[1.0, 2.0], [3.0, 4.0]])  # 创建左矩阵。",
            "right = np.array([[2.0, 0.0], [1.0, 2.0]])  # 创建右矩阵。",
            "elementwise = np.multiply(left, right)  # multiply或星号执行逐位置相乘。",
            "via_at = left @ right  # @ 执行矩阵乘法。",
            "via_dot = np.dot(left, right)  # 二维输入时 dot 与矩阵乘法一致。",
            "via_matmul = np.matmul(left, right)  # matmul 与 @ 的语义一致。",
            "assert not np.array_equal(elementwise, via_at)  # 验证逐元素乘法不是矩阵乘法。",
            "assert np.allclose(via_at, via_dot) and np.allclose(via_at, via_matmul)  # 核对三种矩阵乘法写法。",
            "print(elementwise, via_at)  # 对比两类结果。",
        ],
    ),
    (
        "批量矩阵乘法与广播",
        ["创建一批矩阵。", "让共享权重矩阵沿 batch 维广播。", "再完成两个 batch 的逐批矩阵乘法。"],
        [
            "import numpy as np  # 导入 NumPy。",
            "batch = np.arange(24.0).reshape(2, 3, 4)  # 创建 shape=(B=2,M=3,K=4) 的批量矩阵。",
            "shared_weight = np.ones((4, 5))  # 创建所有 batch 共用的 shape=(K=4,N=5) 权重。",
            "broadcast_result = batch @ shared_weight  # matmul 自动广播共享权重得到 (2,3,5)。",
            "batch_weight = np.ones((2, 4, 5))  # 为每个 batch 创建独立权重。",
            "batch_result = np.matmul(batch, batch_weight)  # 逐 batch 执行 (3,4)@(4,5)。",
            "assert broadcast_result.shape == batch_result.shape == (2, 3, 5)  # 验证批量输出 shape。",
            "assert np.allclose(broadcast_result, batch_result)  # 当前权重相同，因此两个结果应相等。",
            "print(broadcast_result.shape, broadcast_result[0])  # 输出 shape 和第一个 batch。",
        ],
    ),
    (
        "转置换轴与共轭转置",
        ["区分一维向量转置和列向量。", "对三维 batch 只交换最后两轴。", "对复数矩阵执行共轭转置。"],
        [
            "import numpy as np  # 导入 NumPy。",
            "vector = np.array([1.0, 2.0, 3.0])  # 一维向量没有行列之分。",
            "column = vector[:, None]  # 用新增轴把 (3,) 变成列向量 (3,1)。",
            "batch = np.arange(24).reshape(2, 3, 4)  # 创建三维批量矩阵。",
            "batch_transposed = batch.swapaxes(-1, -2)  # 只交换矩阵的 M、K 两轴得到 (2,4,3)。",
            "complex_matrix = np.array([[1 + 2j, 3 - 1j]])  # 创建复数行矩阵。",
            "adjoint = complex_matrix.conj().T  # 共轭后转置得到 Hermitian transpose。",
            "assert vector.T.shape == (3,) and column.shape == (3, 1)  # 一维 .T 不会变成列向量。",
            "assert batch_transposed.shape == (2, 4, 3) and adjoint.shape == (2, 1)  # 验证换轴结果。",
            "print(column, batch_transposed.shape, adjoint)  # 输出关键结果。",
        ],
    ),
    (
        "inner_outer与kronecker积",
        ["计算内积和外积。", "计算两个小矩阵的 Kronecker 积。", "根据 shape 解释三者差异。"],
        [
            "import numpy as np  # 导入 NumPy。",
            "a = np.array([1.0, 2.0, 3.0])  # 创建第一个向量。",
            "b = np.array([4.0, 5.0])  # 创建不同长度的第二个向量。",
            "inner = np.inner(a, a)  # inner 对最后轴收缩并得到标量。",
            "outer = np.outer(a, b)  # outer 组合每一对元素并得到 shape=(3,2)。",
            "kronecker = np.kron(np.eye(2), np.ones((2, 2)))  # 计算分块式 Kronecker 积。",
            "assert inner == 14.0 and outer.shape == (3, 2) and kronecker.shape == (4, 4)  # 核对 shape。",
            "print(inner, outer, kronecker)  # 输出三种结果。",
        ],
    ),
    (
        "einsum常用单矩阵操作",
        ["用 einsum 求转置、迹和行和。", "分别写出下标含义。", "与 NumPy 专用函数核对。"],
        [
            "import numpy as np  # 导入 NumPy。",
            "matrix = np.arange(1.0, 10.0).reshape(3, 3)  # 创建 3×3 方阵。",
            "transposed = np.einsum('ij->ji', matrix)  # 交换输出下标顺序实现转置。",
            "trace = np.einsum('ii->', matrix)  # 重复下标 i 表示取对角线并求和。",
            "row_sums = np.einsum('ij->i', matrix)  # 消去 j 下标得到每一行的和。",
            "assert np.array_equal(transposed, matrix.T)  # 与标准转置核对。",
            "assert trace == np.trace(matrix) and np.array_equal(row_sums, matrix.sum(axis=1))  # 与专用函数核对。",
            "print(transposed, trace, row_sums)  # 输出 einsum 结果。",
        ],
    ),
    (
        "einsum批量乘法与Attention分数",
        ["创建多头 Q 和 K。", "用 einsum 计算每个 head 的 QK 转置。", "与 matmul 写法核对。"],
        [
            "import numpy as np  # 导入 NumPy。",
            "rng = np.random.default_rng(42)  # 创建可复现随机数生成器。",
            "query = rng.normal(size=(2, 3, 4, 5))  # 创建 (batch,head,query,key_dim) 的 Q。",
            "key = rng.normal(size=(2, 3, 6, 5))  # 创建 (batch,head,key,key_dim) 的 K。",
            "scores = np.einsum('bhqd,bhkd->bhqk', query, key)  # 收缩 d 并保留 batch、head、q、k。",
            "via_matmul = query @ key.swapaxes(-1, -2)  # 使用批量 matmul 完成相同的 QK 转置。",
            "assert scores.shape == (2, 3, 4, 6) and np.allclose(scores, via_matmul)  # 核对 shape 和数值。",
            "print(scores.shape, scores[0, 0])  # 输出一个 head 的分数矩阵。",
        ],
    ),
    (
        "tensordot张量收缩",
        ["指定两个张量要收缩的轴。", "预测未收缩轴组成的输出 shape。", "用 einsum 写出等价形式。"],
        [
            "import numpy as np  # 导入 NumPy。",
            "left = np.arange(24.0).reshape(2, 3, 4)  # 创建 shape=(2,3,4) 的左张量。",
            "right = np.arange(20.0).reshape(4, 5)  # 创建 shape=(4,5) 的右张量。",
            "contracted = np.tensordot(left, right, axes=([2], [0]))  # 收缩 left 轴2与 right 轴0。",
            "via_einsum = np.einsum('ijk,kl->ijl', left, right)  # 显式标注相同的 k 轴收缩。",
            "assert contracted.shape == (2, 3, 5) and np.allclose(contracted, via_einsum)  # 验证输出。",
            "print(contracted.shape, contracted[0])  # 输出 shape 和第一个切片。",
        ],
    ),
    (
        "solve与多个右端项",
        ["求解 Ax=b。", "一次求解多个右端向量。", "代回原方程验证，并说明不要先求逆。"],
        [
            "import numpy as np  # 导入 NumPy。",
            "a = np.array([[3.0, 1.0], [1.0, 2.0]])  # 创建可逆系数矩阵 A。",
            "b = np.array([9.0, 8.0])  # 创建单个右端向量 b。",
            "x = np.linalg.solve(a, b)  # 直接求解比 inv(A)@b 更快且更稳定。",
            "multiple_b = np.column_stack((b, 2 * b))  # 把两个右端向量组成 shape=(2,2)。",
            "multiple_x = np.linalg.solve(a, multiple_b)  # 一次求出两组解。",
            "assert np.allclose(a @ x, b) and np.allclose(a @ multiple_x, multiple_b)  # 把解代回验证。",
            "print(x, multiple_x)  # 输出单组和多组解。",
        ],
    ),
    (
        "lstsq最小二乘回归",
        ["为线性模型增加截距列。", "用最小二乘拟合含噪数据。", "检查残差、秩和奇异值。"],
        [
            "import numpy as np  # 导入 NumPy。",
            "x = np.arange(5.0)  # 创建单特征样本。",
            "design = np.column_stack((x, np.ones_like(x)))  # 添加全1列以同时拟合斜率和截距。",
            "targets = np.array([1.1, 2.9, 5.2, 6.8, 9.1])  # 创建近似 y=2x+1 的含噪目标。",
            "parameters, residuals, rank, singular_values = np.linalg.lstsq(design, targets, rcond=None)  # 求最小二乘解。",
            "predictions = design @ parameters  # 用矩阵乘法计算拟合值。",
            "assert rank == 2 and parameters.shape == (2,) and residuals.size == 1  # 检查满列秩和返回结构。",
            "print(parameters, predictions, residuals, singular_values)  # 输出拟合诊断信息。",
        ],
    ),
    (
        "伪逆与秩亏矩阵",
        ["构造线性相关列导致的秩亏矩阵。", "说明 solve 为什么不适用。", "使用 pinv 求最小范数解。"],
        [
            "import numpy as np  # 导入 NumPy。",
            "a = np.array([[1.0, 2.0], [2.0, 4.0], [3.0, 6.0]])  # 第二列是第一列两倍，因此矩阵秩亏。",
            "b = np.array([1.0, 2.0, 3.0])  # 创建与列空间一致的目标。",
            "rank = np.linalg.matrix_rank(a)  # 计算秩并识别线性相关列。",
            "x = np.linalg.pinv(a) @ b  # Moore-Penrose 伪逆给出最小范数最小二乘解。",
            "assert rank == 1 and np.allclose(a @ x, b)  # 验证秩和重建结果。",
            "assert np.allclose(x, np.array([0.2, 0.4]))  # 核对最小范数解。",
            "print(rank, x)  # 输出秩和伪逆解。",
        ],
    ),
    (
        "det_slogdet与条件数",
        ["计算行列式及稳定的对数行列式。", "比较良态与病态矩阵的条件数。", "解释条件数大时解对扰动敏感。"],
        [
            "import numpy as np  # 导入 NumPy。",
            "well_conditioned = np.array([[2.0, 0.0], [0.0, 3.0]])  # 创建良态对角矩阵。",
            "ill_conditioned = np.array([[1.0, 1.0], [1.0, 1.000001]])  # 创建两行近似相关的病态矩阵。",
            "determinant = np.linalg.det(well_conditioned)  # 计算普通行列式。",
            "sign, log_abs_det = np.linalg.slogdet(well_conditioned)  # 避免极大极小行列式上下溢。",
            "good_cond = np.linalg.cond(well_conditioned)  # 计算良态矩阵条件数。",
            "bad_cond = np.linalg.cond(ill_conditioned)  # 计算病态矩阵条件数。",
            "assert np.isclose(sign * np.exp(log_abs_det), determinant) and bad_cond > good_cond * 1000  # 核对稳定表示和敏感性。",
            "print(determinant, log_abs_det, good_cond, bad_cond)  # 输出数值稳定性指标。",
        ],
    ),
    (
        "eig与eigh选择",
        ["对实对称矩阵优先调用 eigh。", "验证 Av 等于 lambda v。", "验证特征向量正交并重建矩阵。"],
        [
            "import numpy as np  # 导入 NumPy。",
            "matrix = np.array([[2.0, 1.0], [1.0, 2.0]])  # 创建实对称矩阵。",
            "values, vectors = np.linalg.eigh(matrix)  # eigh 利用对称结构并返回升序实特征值。",
            "left = matrix @ vectors  # 同时计算所有 Av。",
            "right = vectors * values  # 每一列特征向量乘对应特征值。",
            "reconstructed = vectors @ np.diag(values) @ vectors.T  # 用 QΛQ 转置重建对称矩阵。",
            "assert np.allclose(left, right) and np.allclose(vectors.T @ vectors, np.eye(2))  # 验证特征方程和正交性。",
            "assert np.allclose(reconstructed, matrix)  # 验证谱分解重建。",
            "print(values, vectors, reconstructed)  # 输出谱分解结果。",
        ],
    ),
    (
        "svd与低秩近似",
        ["对非方阵做经济型 SVD。", "重建原矩阵。", "只保留最大奇异值构造 rank-1 近似并比较误差。"],
        [
            "import numpy as np  # 导入 NumPy。",
            "matrix = np.array([[3.0, 2.0, 2.0], [2.0, 3.0, -2.0]])  # 创建 2×3 非方阵。",
            "u, singular, vh = np.linalg.svd(matrix, full_matrices=False)  # 计算经济型 A=UΣVh。",
            "reconstructed = (u * singular) @ vh  # 利用广播把 U 每列乘对应奇异值。",
            "rank_one = (u[:, :1] * singular[:1]) @ vh[:1]  # 只保留最大奇异值构造最佳 rank-1 近似。",
            "full_error = np.linalg.norm(matrix - reconstructed)  # 计算完整重建误差。",
            "rank_one_error = np.linalg.norm(matrix - rank_one)  # 计算压缩后的 Frobenius 误差。",
            "assert full_error < 1e-10 and rank_one_error > full_error  # 验证完整重建和有损近似。",
            "print(singular, rank_one, rank_one_error)  # 输出奇异值与低秩近似。",
        ],
    ),
    (
        "qr分解与最小二乘",
        ["计算 reduced QR 分解。", "检查 Q 列正交并重建 A。", "用 QR 解满列秩最小二乘。"],
        [
            "import numpy as np  # 导入 NumPy。",
            "a = np.array([[1.0, 1.0], [1.0, 2.0], [1.0, 3.0]])  # 创建高矩阵设计矩阵。",
            "b = np.array([1.0, 2.0, 2.0])  # 创建回归目标。",
            "q, r = np.linalg.qr(a, mode='reduced')  # 分解 A=QR，其中 Q 的列正交。",
            "x_via_qr = np.linalg.solve(r, q.T @ b)  # 求解 Rx=Q 转置 b。",
            "x_via_lstsq = np.linalg.lstsq(a, b, rcond=None)[0]  # 使用标准最小二乘作为对照。",
            "assert np.allclose(q.T @ q, np.eye(2)) and np.allclose(q @ r, a)  # 验证正交性和重建。",
            "assert np.allclose(x_via_qr, x_via_lstsq)  # 核对 QR 解。",
            "print(q, r, x_via_qr)  # 输出 QR 因子与解。",
        ],
    ),
    (
        "cholesky正定矩阵求解",
        ["验证矩阵对称正定。", "计算 Cholesky 分解。", "用两次三角方程求解 Ax=b。"],
        [
            "import numpy as np  # 导入 NumPy。",
            "a = np.array([[4.0, 2.0], [2.0, 3.0]])  # 创建对称正定矩阵。",
            "b = np.array([6.0, 7.0])  # 创建右端向量。",
            "lower = np.linalg.cholesky(a)  # 得到 A=L@L.T 的下三角因子。",
            "intermediate = np.linalg.solve(lower, b)  # 先求 Ly=b。",
            "x = np.linalg.solve(lower.T, intermediate)  # 再求 L.T x=y。",
            "assert np.all(np.linalg.eigvalsh(a) > 0) and np.allclose(lower @ lower.T, a)  # 验证正定性和分解。",
            "assert np.allclose(a @ x, b)  # 代回原方程验证。",
            "print(lower, x)  # 输出 Cholesky 因子与解。",
        ],
    ),
    (
        "矩阵范数与余弦相似度",
        ["计算向量 L1/L2 范数。", "计算矩阵 Frobenius 和谱范数。", "批量计算余弦相似度并避免除零。"],
        [
            "import numpy as np  # 导入 NumPy。",
            "vector = np.array([3.0, -4.0])  # 创建二维向量。",
            "matrix = np.array([[3.0, 0.0], [0.0, 4.0]])  # 创建对角矩阵。",
            "l1 = np.linalg.norm(vector, ord=1)  # 计算绝对值和。",
            "l2 = np.linalg.norm(vector, ord=2)  # 计算欧氏范数。",
            "frobenius = np.linalg.norm(matrix, ord='fro')  # 计算所有元素平方和开根号。",
            "spectral = np.linalg.norm(matrix, ord=2)  # 矩阵 2-范数等于最大奇异值。",
            "rows = np.array([[1.0, 0.0], [1.0, 1.0]])  # 创建待比较的行向量。",
            "cosine = (rows @ vector) / (np.linalg.norm(rows, axis=1) * np.linalg.norm(vector) + 1e-12)  # 批量计算余弦相似度。",
            "assert l1 == 7.0 and l2 == frobenius == 5.0 and spectral == 4.0  # 核对不同范数。",
            "print(l1, l2, frobenius, spectral, cosine)  # 输出范数与相似度。",
        ],
    ),
    (
        "Gram协方差与相关矩阵",
        ["把特征按列中心化。", "用矩阵乘法手算样本协方差。", "转换为相关矩阵并与 corrcoef 核对。"],
        [
            "import numpy as np  # 导入 NumPy。",
            "samples = np.array([[1.0, 2.0], [2.0, 4.0], [4.0, 5.0], [5.0, 7.0]])  # 行是样本、列是特征。",
            "centered = samples - samples.mean(axis=0, keepdims=True)  # 每列减去训练样本均值。",
            "gram = centered.T @ centered  # 计算中心化特征的 Gram 矩阵。",
            "covariance = gram / (len(samples) - 1)  # 使用 n-1 得到无偏样本协方差。",
            "std = np.sqrt(np.diag(covariance))  # 从协方差对角线取得样本标准差。",
            "correlation = covariance / np.outer(std, std)  # 标准化协方差得到相关矩阵。",
            "assert np.allclose(covariance, np.cov(samples, rowvar=False))  # 与 np.cov 核对。",
            "assert np.allclose(correlation, np.corrcoef(samples, rowvar=False))  # 与 np.corrcoef 核对。",
            "print(gram, covariance, correlation)  # 输出三类矩阵。",
        ],
    ),
    (
        "线性回归矩阵梯度",
        ["用矩阵形式计算预测和 MSE。", "手推梯度 2/n X 转置(Xw-y)。", "用有限差分检查一个梯度分量。"],
        [
            "import numpy as np  # 导入 NumPy。",
            "x = np.array([[1.0, 0.0], [1.0, 1.0], [1.0, 2.0]])  # 第一列作为截距特征。",
            "y = np.array([1.0, 3.0, 5.0])  # 创建线性目标。",
            "weights = np.array([0.5, 1.5])  # 创建待优化参数。",
            "residual = x @ weights - y  # 使用矩阵乘法计算预测残差。",
            "loss = np.mean(residual**2)  # 计算均方误差。",
            "gradient = (2.0 / len(x)) * x.T @ residual  # 手推 MSE 对权重的矩阵梯度。",
            "epsilon = 1e-6  # 设置中心有限差分步长。",
            "direction = np.array([1.0, 0.0])  # 只扰动第一个参数。",
            "loss_plus = np.mean((x @ (weights + epsilon * direction) - y) ** 2)  # 计算正向扰动损失。",
            "loss_minus = np.mean((x @ (weights - epsilon * direction) - y) ** 2)  # 计算反向扰动损失。",
            "numeric_gradient = (loss_plus - loss_minus) / (2 * epsilon)  # 中心差分近似偏导。",
            "assert np.isclose(gradient[0], numeric_gradient, atol=1e-6)  # 核对解析梯度。",
            "print(loss, gradient, numeric_gradient)  # 输出损失和两类梯度。",
        ],
    ),
    (
        "PCA的SVD矩阵实现",
        ["中心化二维数据。", "用 SVD 找主方向。", "投影到一维并重建，解释符号不唯一。"],
        [
            "import numpy as np  # 导入 NumPy。",
            "samples = np.array([[1.0, 1.0], [2.0, 2.1], [3.0, 2.9], [4.0, 4.2]])  # 创建强相关二维数据。",
            "mean = samples.mean(axis=0, keepdims=True)  # 计算每个特征均值。",
            "centered = samples - mean  # PCA 前先中心化。",
            "_, singular, vh = np.linalg.svd(centered, full_matrices=False)  # 右奇异向量给出主轴。",
            "component = vh[:1]  # 选择解释方差最大的第一主成分。",
            "scores = centered @ component.T  # 把样本投影到一维主成分空间。",
            "reconstructed = scores @ component + mean  # 从一维分数近似重建二维数据。",
            "explained_ratio = singular[0] ** 2 / np.sum(singular**2)  # 计算第一主成分解释方差比例。",
            "assert scores.shape == (4, 1) and explained_ratio > 0.99  # 验证降维 shape 和解释率。",
            "print(component, scores, reconstructed, explained_ratio)  # 输出 PCA 中间结果。",
        ],
    ),
    (
        "矩阵标准化与广播",
        ["按列计算均值和标准差。", "使用 keepdims 保留广播所需维度。", "标准化后检查每列均值和总体标准差。"],
        [
            "import numpy as np  # 导入 NumPy。",
            "matrix = np.array([[1.0, 10.0], [2.0, 20.0], [3.0, 30.0], [4.0, 40.0]])  # 行是样本、列是特征。",
            "mean = matrix.mean(axis=0, keepdims=True)  # 沿样本轴求每列均值并保留 shape=(1,2)。",
            "std = matrix.std(axis=0, keepdims=True, ddof=0)  # 计算总体标准差并保留广播维度。",
            "standardized = (matrix - mean) / std  # 借助广播一次标准化所有列。",
            "assert mean.shape == std.shape == (1, 2)  # 验证 keepdims 的作用。",
            "assert np.allclose(standardized.mean(axis=0), 0.0)  # 验证每列均值为零。",
            "assert np.allclose(standardized.std(axis=0), 1.0)  # 验证每列总体标准差为一。",
            "print(mean, std, standardized)  # 输出标准化参数和结果。",
        ],
    ),
]


PYTORCH_MATRIX_CASES = [
    (
        "dot_mv_mm基础",
        ["分别使用 dot、mv 和 mm。", "写出每个输入和输出 shape。", "与 @ 运算符核对。"],
        [
            "import torch  # 导入 PyTorch。",
            "vector = torch.tensor([1.0, 2.0, 3.0])  # 创建一维向量。",
            "matrix = torch.tensor([[1.0, 0.0, 2.0], [0.0, 1.0, 3.0]])  # 创建二维矩阵。",
            "dot = torch.dot(vector, vector)  # dot 只接受两个一维 Tensor。",
            "matrix_vector = torch.mv(matrix, vector)  # mv 专门执行二维矩阵乘一维向量。",
            "matrix_matrix = torch.mm(matrix, matrix.t())  # mm 专门执行两个二维矩阵相乘。",
            "assert dot.item() == 14.0 and torch.equal(matrix_vector, matrix @ vector)  # 与 @ 核对向量结果。",
            "assert torch.equal(matrix_matrix, matrix @ matrix.t())  # 与 @ 核对矩阵结果。",
            "print(dot, matrix_vector, matrix_matrix)  # 输出三类运算。",
        ],
    ),
    (
        "matmul维度与广播",
        ["比较 1D、2D 和 N-D matmul 规则。", "让共享权重沿 batch 维广播。", "验证输出 shape。"],
        [
            "import torch  # 导入 PyTorch。",
            "batch = torch.arange(24.0).reshape(2, 3, 4)  # 创建 (B=2,M=3,K=4) 批量矩阵。",
            "weight = torch.ones(4, 5)  # 创建共享 (K=4,N=5) 权重。",
            "output = torch.matmul(batch, weight)  # N-D matmul 广播 batch 维并得到 (2,3,5)。",
            "vector_output = torch.matmul(batch, torch.ones(4))  # 批量矩阵乘向量得到 (2,3)。",
            "assert output.shape == (2, 3, 5) and vector_output.shape == (2, 3)  # 验证不同维度规则。",
            "print(output.shape, vector_output)  # 输出批量矩阵结果。",
        ],
    ),
    (
        "bmm与baddbmm",
        ["用 bmm 完成严格三维批量乘法。", "用 baddbmm 同时加入偏置。", "说明 bmm 本身不广播 batch。"],
        [
            "import torch  # 导入 PyTorch。",
            "left = torch.arange(24.0).reshape(2, 3, 4)  # 创建 (B,M,K) 左 Tensor。",
            "right = torch.ones(2, 4, 5)  # 创建同 batch 的 (B,K,N) 右 Tensor。",
            "product = torch.bmm(left, right)  # 对每个 batch 严格执行矩阵乘法。",
            "bias = torch.full((2, 3, 5), 2.0)  # 创建与输出同 shape 的偏置。",
            "combined = torch.baddbmm(bias, left, right, beta=0.5, alpha=2.0)  # 计算 beta*bias+alpha*(left@right)。",
            "expected = 0.5 * bias + 2.0 * product  # 直接写出等价公式。",
            "assert product.shape == (2, 3, 5) and torch.allclose(combined, expected)  # 核对 shape 和数值。",
            "print(product.shape, combined[0])  # 输出批量结果。",
        ],
    ),
    (
        "einsum常用矩阵操作",
        ["用 einsum 完成转置、迹和矩阵乘法。", "解释重复下标代表收缩。", "与专用 API 核对。"],
        [
            "import torch  # 导入 PyTorch。",
            "matrix = torch.arange(1.0, 10.0).reshape(3, 3)  # 创建 3×3 方阵。",
            "transposed = torch.einsum('ij->ji', matrix)  # 交换下标顺序实现转置。",
            "trace = torch.einsum('ii->', matrix)  # 对重复的对角下标求和。",
            "product = torch.einsum('ik,kj->ij', matrix, matrix)  # 收缩 k 实现矩阵乘法。",
            "assert torch.equal(transposed, matrix.t()) and trace == torch.trace(matrix)  # 核对转置和迹。",
            "assert torch.equal(product, matrix @ matrix)  # 核对 einsum 矩阵乘法。",
            "print(transposed, trace, product)  # 输出 einsum 结果。",
        ],
    ),
    (
        "einsum多头Attention",
        ["创建多头 Q、K、V。", "用 einsum 计算缩放点积分数和输出。", "检查所有中间 shape。"],
        [
            "import math  # 导入平方根函数。",
            "import torch  # 导入 PyTorch。",
            "torch.manual_seed(42)  # 固定随机种子。",
            "query = torch.randn(2, 3, 4, 5)  # 创建 (B,H,Q,D) 查询。",
            "key = torch.randn(2, 3, 6, 5)  # 创建 (B,H,K,D) 键。",
            "value = torch.randn(2, 3, 6, 7)  # 创建 (B,H,K,V) 值。",
            "scores = torch.einsum('bhqd,bhkd->bhqk', query, key) / math.sqrt(5)  # 计算缩放 QK 转置。",
            "weights = scores.softmax(dim=-1)  # 沿 key 轴把分数归一化。",
            "output = torch.einsum('bhqk,bhkv->bhqv', weights, value)  # 用注意力权重加权 V。",
            "assert scores.shape == (2, 3, 4, 6) and output.shape == (2, 3, 4, 7)  # 验证 Attention shape。",
            "assert torch.allclose(weights.sum(-1), torch.ones(2, 3, 4))  # 验证注意力概率和为一。",
            "print(scores.shape, output.shape)  # 输出关键 shape。",
        ],
    ),
    (
        "outerger与addmm",
        ["计算向量外积。", "用 ger 验证 outer 的旧别名行为。", "用 addmm 融合偏置和矩阵乘法。"],
        [
            "import torch  # 导入 PyTorch。",
            "a = torch.tensor([1.0, 2.0, 3.0])  # 创建列方向向量。",
            "b = torch.tensor([4.0, 5.0])  # 创建行方向向量。",
            "outer = torch.outer(a, b)  # 计算每对元素乘积得到 (3,2)。",
            "via_ger = torch.ger(a, b)  # ger 是二维外积的旧接口。",
            "left = torch.ones(3, 4)  # 创建 addmm 的左矩阵。",
            "right = torch.ones(4, 2)  # 创建 addmm 的右矩阵。",
            "fused = torch.addmm(outer, left, right, beta=0.5, alpha=2.0)  # 融合计算 0.5*outer+2*(left@right)。",
            "assert torch.equal(outer, via_ger) and torch.allclose(fused, 0.5 * outer + 2 * (left @ right))  # 核对结果。",
            "print(outer, fused)  # 输出外积与融合结果。",
        ],
    ),
    (
        "transposepermute与adjoint",
        ["区分 t、transpose 和 permute。", "只交换批量矩阵的最后两轴。", "对复数矩阵做共轭转置。"],
        [
            "import torch  # 导入 PyTorch。",
            "batch = torch.arange(24).reshape(2, 3, 4)  # 创建三维批量矩阵。",
            "last_two = batch.transpose(-1, -2)  # 只交换最后两个矩阵轴得到 (2,4,3)。",
            "reordered = batch.permute(2, 0, 1)  # 任意重排全部轴得到 (4,2,3)。",
            "complex_matrix = torch.tensor([[1 + 2j, 3 - 1j]])  # 创建复数矩阵。",
            "adjoint = complex_matrix.mH  # mH 对最后两轴执行共轭转置。",
            "assert last_two.shape == (2, 4, 3) and reordered.shape == (4, 2, 3)  # 验证轴顺序。",
            "assert torch.equal(adjoint, complex_matrix.conj().transpose(-1, -2))  # 核对共轭转置。",
            "print(last_two.shape, reordered.shape, adjoint)  # 输出换轴结果。",
        ],
    ),
    (
        "linalgsolve与批量方程",
        ["求解单个线性方程组。", "扩展到 batch 线性方程。", "代回验证并说明 solve 优于显式求逆。"],
        [
            "import torch  # 导入 PyTorch。",
            "a = torch.tensor([[3.0, 1.0], [1.0, 2.0]])  # 创建可逆系数矩阵。",
            "b = torch.tensor([9.0, 8.0])  # 创建右端向量。",
            "x = torch.linalg.solve(a, b)  # 直接求解 Ax=b。",
            "batch_a = torch.stack((a, 2 * a))  # 创建两个方程组的批量系数矩阵。",
            "batch_b = torch.stack((b, 2 * b))  # 创建对应批量右端向量。",
            "batch_x = torch.linalg.solve(batch_a, batch_b)  # 一次求解 batch 方程。",
            "assert torch.allclose(a @ x, b)  # 验证单组解。",
            "assert torch.allclose(batch_a @ batch_x.unsqueeze(-1), batch_b.unsqueeze(-1))  # 验证批量解。",
            "print(x, batch_x)  # 输出两类解。",
        ],
    ),
    (
        "linalglstsq最小二乘",
        ["构建设计矩阵和含噪标签。", "调用 torch.linalg.lstsq。", "检查 solution、rank、singular_values 和 residuals。"],
        [
            "import torch  # 导入 PyTorch。",
            "x = torch.arange(5.0)  # 创建单特征样本。",
            "design = torch.stack((x, torch.ones_like(x)), dim=1)  # 添加截距列得到 (5,2)。",
            "targets = torch.tensor([1.1, 2.9, 5.2, 6.8, 9.1])  # 创建含噪线性目标。",
            "result = torch.linalg.lstsq(design, targets)  # 求解最小化 ||Ax-b|| 的参数。",
            "parameters = result.solution  # 取得斜率和截距。",
            "predictions = design @ parameters  # 计算拟合值。",
            "assert parameters.shape == (2,) and int(result.rank) == 2  # 验证返回 shape 和满列秩。",
            "print(parameters, predictions, result.residuals, result.singular_values)  # 输出诊断信息。",
        ],
    ),
    (
        "pinv矩阵秩与条件数",
        ["构造秩亏矩阵。", "计算 matrix_rank、pinv 和 cond。", "验证伪逆的 Moore-Penrose 性质。"],
        [
            "import torch  # 导入 PyTorch。",
            "matrix = torch.tensor([[1.0, 2.0], [2.0, 4.0], [3.0, 6.0]])  # 创建秩为1的矩阵。",
            "rank = torch.linalg.matrix_rank(matrix)  # 计算数值秩。",
            "pseudo_inverse = torch.linalg.pinv(matrix)  # 用 SVD 计算 Moore-Penrose 伪逆。",
            "condition = torch.linalg.cond(matrix)  # 秩亏矩阵的条件数非常大或为无穷。",
            "projected = matrix @ pseudo_inverse @ matrix  # 计算 A A+ A。",
            "assert rank.item() == 1 and torch.allclose(projected, matrix, atol=1e-5)  # 验证秩和伪逆性质。",
            "print(rank, pseudo_inverse, condition)  # 输出数值诊断。",
        ],
    ),
    (
        "detslogdet与数值稳定性",
        ["计算 determinant。", "用 slogdet 表示符号与绝对值对数。", "验证二者关系并说明大矩阵优先 slogdet。"],
        [
            "import torch  # 导入 PyTorch。",
            "matrix = torch.diag(torch.tensor([1e-10, 1e10, 3.0]))  # 创建尺度差异很大的可逆对角矩阵。",
            "determinant = torch.linalg.det(matrix)  # 直接计算行列式。",
            "sign, log_abs_det = torch.linalg.slogdet(matrix)  # 稳定返回符号和 log(abs(det))。",
            "recovered = sign * log_abs_det.exp()  # 从对数表示恢复普通行列式。",
            "assert torch.allclose(recovered, determinant) and torch.allclose(determinant, torch.tensor(3.0))  # 核对结果。",
            "print(determinant, sign, log_abs_det)  # 输出普通与对数行列式。",
        ],
    ),
    (
        "eigheigvalsh谱分解",
        ["对实对称矩阵调用 eigh。", "验证特征方程和正交性。", "只需要特征值时调用 eigvalsh。"],
        [
            "import torch  # 导入 PyTorch。",
            "matrix = torch.tensor([[2.0, 1.0], [1.0, 2.0]])  # 创建实对称矩阵。",
            "values, vectors = torch.linalg.eigh(matrix)  # 取得升序实特征值和正交特征向量。",
            "values_only = torch.linalg.eigvalsh(matrix)  # 不计算特征向量可节省工作。",
            "reconstructed = vectors @ torch.diag(values) @ vectors.t()  # 用 QΛQ 转置重建矩阵。",
            "assert torch.allclose(matrix @ vectors, vectors * values)  # 验证 Av=lambda*v。",
            "assert torch.allclose(values, values_only) and torch.allclose(reconstructed, matrix)  # 核对特征值和重建。",
            "print(values, vectors)  # 输出谱分解结果。",
        ],
    ),
    (
        "svd与低秩近似",
        ["调用 torch.linalg.svd。", "完整重建矩阵。", "用最大奇异值构造 rank-1 近似。"],
        [
            "import torch  # 导入 PyTorch。",
            "matrix = torch.tensor([[3.0, 2.0, 2.0], [2.0, 3.0, -2.0]])  # 创建非方阵。",
            "u, singular, vh = torch.linalg.svd(matrix, full_matrices=False)  # 计算经济型 SVD。",
            "reconstructed = (u * singular) @ vh  # 使用广播完成 UΣVh 重建。",
            "rank_one = (u[:, :1] * singular[:1]) @ vh[:1]  # 只保留最大奇异值。",
            "full_error = torch.linalg.matrix_norm(matrix - reconstructed)  # 计算完整重建 Frobenius 误差。",
            "rank_one_error = torch.linalg.matrix_norm(matrix - rank_one)  # 计算低秩近似误差。",
            "assert full_error < 1e-5 and rank_one_error > full_error  # 验证重建与压缩。",
            "print(singular, rank_one, rank_one_error)  # 输出奇异值和近似。",
        ],
    ),
    (
        "qr分解与正交矩阵",
        ["计算 reduced QR。", "验证 Q 转置 Q 等于单位矩阵。", "使用 QR 解最小二乘并与 lstsq 核对。"],
        [
            "import torch  # 导入 PyTorch。",
            "a = torch.tensor([[1.0, 1.0], [1.0, 2.0], [1.0, 3.0]])  # 创建高矩阵。",
            "b = torch.tensor([1.0, 2.0, 2.0])  # 创建回归目标。",
            "q, r = torch.linalg.qr(a, mode='reduced')  # 分解 A=QR。",
            "x_qr = torch.linalg.solve(r, q.t() @ b)  # 通过 Rx=Q 转置 b 求最小二乘。",
            "x_lstsq = torch.linalg.lstsq(a, b).solution  # 用官方最小二乘核对。",
            "assert torch.allclose(q.t() @ q, torch.eye(2), atol=1e-6) and torch.allclose(q @ r, a)  # 验证 Q 正交和重建。",
            "assert torch.allclose(x_qr, x_lstsq, atol=1e-5)  # 核对两种解。",
            "print(q, r, x_qr)  # 输出 QR 分解与解。",
        ],
    ),
    (
        "cholesky与choleskysolve",
        ["构造对称正定矩阵。", "计算 Cholesky 因子。", "使用 cholesky_solve 求多右端项。"],
        [
            "import torch  # 导入 PyTorch。",
            "a = torch.tensor([[4.0, 2.0], [2.0, 3.0]])  # 创建对称正定矩阵。",
            "b = torch.tensor([[6.0], [7.0]])  # cholesky_solve 接收二维右端项。",
            "lower = torch.linalg.cholesky(a)  # 得到 A=L@L 转置。",
            "x = torch.cholesky_solve(b, lower, upper=False)  # 利用下三角 Cholesky 因子求解。",
            "assert torch.all(torch.linalg.eigvalsh(a) > 0)  # 验证正定性。",
            "assert torch.allclose(lower @ lower.t(), a) and torch.allclose(a @ x, b)  # 验证分解和解。",
            "print(lower, x)  # 输出因子和解。",
        ],
    ),
    (
        "向量矩阵范数与cdist",
        ["计算 vector_norm 和 matrix_norm。", "批量计算两组样本的欧氏距离。", "用 normalize 后点积计算余弦相似度。"],
        [
            "import torch  # 导入 PyTorch。",
            "from torch.nn import functional as F  # 导入归一化函数。",
            "vector = torch.tensor([3.0, -4.0])  # 创建向量。",
            "matrix = torch.diag(torch.tensor([3.0, 4.0]))  # 创建对角矩阵。",
            "l2 = torch.linalg.vector_norm(vector, ord=2)  # 计算欧氏范数。",
            "frobenius = torch.linalg.matrix_norm(matrix, ord='fro')  # 计算 Frobenius 范数。",
            "left = torch.tensor([[0.0, 0.0], [1.0, 0.0]])  # 创建第一组样本。",
            "right = torch.tensor([[0.0, 1.0], [1.0, 1.0]])  # 创建第二组样本。",
            "distances = torch.cdist(left, right, p=2)  # 计算所有样本对欧氏距离矩阵。",
            "cosine = F.normalize(left + 1e-6, dim=1) @ F.normalize(right + 1e-6, dim=1).t()  # 归一化后点积得到余弦相似度。",
            "assert l2 == frobenius == 5.0 and distances.shape == cosine.shape == (2, 2)  # 核对范数和 shape。",
            "print(l2, frobenius, distances, cosine)  # 输出距离指标。",
        ],
    ),
    (
        "矩阵Autograd梯度",
        ["构建 y=XW+b 和 MSE。", "使用 backward 取得矩阵梯度。", "手算 W 的梯度并核对。"],
        [
            "import torch  # 导入 PyTorch。",
            "x = torch.tensor([[1.0, 2.0], [3.0, 4.0]])  # 创建固定输入矩阵 X。",
            "weight = torch.tensor([[0.5], [1.0]], requires_grad=True)  # 创建需要梯度的权重 W。",
            "target = torch.tensor([[3.0], [7.0]])  # 创建回归目标。",
            "prediction = x @ weight  # 计算矩阵形式线性预测。",
            "residual = prediction - target  # 保存残差用于手算梯度。",
            "loss = residual.square().mean()  # 计算所有元素 MSE。",
            "loss.backward()  # Autograd 计算 dLoss/dW。",
            "manual_gradient = (2.0 / target.numel()) * x.t() @ residual.detach()  # 根据链式法则手算矩阵梯度。",
            "assert torch.allclose(weight.grad, manual_gradient)  # 核对自动和手工梯度。",
            "print(loss.item(), weight.grad, manual_gradient)  # 输出梯度检查结果。",
        ],
    ),
    (
        "nnLinear矩阵等价式",
        ["创建 nn.Linear 并固定参数。", "比较 layer(x) 与 xW 转置+b。", "反向传播检查参数梯度 shape。"],
        [
            "import torch  # 导入 PyTorch。",
            "from torch import nn  # 导入神经网络层。",
            "layer = nn.Linear(in_features=3, out_features=2)  # 创建保存 weight=(2,3) 的线性层。",
            "with torch.no_grad(): layer.weight.copy_(torch.tensor([[1.0, 0.0, 2.0], [0.0, 1.0, 3.0]]))  # 固定权重便于核对。",
            "with torch.no_grad(): layer.bias.copy_(torch.tensor([0.5, -0.5]))  # 固定偏置。",
            "x = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])  # 创建 batch 输入。",
            "official = layer(x)  # nn.Linear 自动计算 x@weight.T+bias。",
            "manual = x @ layer.weight.t() + layer.bias  # 显式写出矩阵等价式。",
            "official.sum().backward()  # 反向传播得到 weight 和 bias 梯度。",
            "assert torch.allclose(official, manual) and layer.weight.grad.shape == (2, 3)  # 核对前向和梯度 shape。",
            "print(official, layer.weight.grad, layer.bias.grad)  # 输出线性层结果。",
        ],
    ),
    (
        "causalAttention矩阵mask",
        ["用 QK 转置计算 Attention logits。", "添加上三角 causal mask。", "softmax 后验证未来位置概率为零。"],
        [
            "import math  # 导入缩放所需平方根函数。",
            "import torch  # 导入 PyTorch。",
            "torch.manual_seed(42)  # 固定随机种子。",
            "query = torch.randn(1, 4, 8)  # 创建 (B,T,D) 查询。",
            "key = torch.randn(1, 4, 8)  # 创建 (B,T,D) 键。",
            "value = torch.randn(1, 4, 6)  # 创建 (B,T,V) 值。",
            "scores = query @ key.transpose(-1, -2) / math.sqrt(8)  # 计算缩放点积 logits。",
            "causal_mask = torch.triu(torch.ones(4, 4, dtype=torch.bool), diagonal=1)  # True 标记未来位置。",
            "masked_scores = scores.masked_fill(causal_mask, float('-inf'))  # 在 softmax 前把未来 logits 设为负无穷。",
            "weights = masked_scores.softmax(dim=-1)  # 沿 key 轴计算注意力概率。",
            "output = weights @ value  # 加权 V 得到 Attention 输出。",
            "assert torch.count_nonzero(weights.masked_select(causal_mask)) == 0  # 验证未来注意力严格为零。",
            "assert output.shape == (1, 4, 6)  # 验证输出 shape。",
            "print(weights[0], output.shape)  # 输出因果注意力矩阵。",
        ],
    ),
    (
        "稀疏矩阵乘法",
        ["用 COO 索引和值创建稀疏矩阵。", "执行 sparse.mm。", "转成 dense 后核对并查看稀疏梯度流。"],
        [
            "import torch  # 导入 PyTorch。",
            "indices = torch.tensor([[0, 1, 1], [2, 0, 2]])  # 每列描述一个非零元素的行列坐标。",
            "values = torch.tensor([3.0, 4.0, 5.0], requires_grad=True)  # 创建可训练非零值。",
            "torch.sparse.check_sparse_tensor_invariants.enable()  # 显式开启 COO 索引和值约束检查。",
            "sparse = torch.sparse_coo_tensor(indices, values, size=(2, 3)).coalesce()  # 构建并合并 COO 稀疏矩阵。",
            "dense_right = torch.arange(6.0).reshape(3, 2)  # 创建稠密右矩阵。",
            "output = torch.sparse.mm(sparse, dense_right)  # 执行稀疏乘稠密矩阵。",
            "expected = sparse.to_dense() @ dense_right  # 转稠密计算对照结果。",
            "output.sum().backward()  # 验证非零 values 可以参与 Autograd。",
            "assert torch.allclose(output, expected) and values.grad is not None  # 核对结果和梯度。",
            "print(sparse, output, values.grad)  # 输出稀疏结构、乘积和梯度。",
        ],
    ),
    (
        "float精度与矩阵乘法",
        ["比较 float32 与 float64 的病态线性方程。", "分别计算解和残差。", "理解高精度通常减小数值误差但消耗更多内存。"],
        [
            "import torch  # 导入 PyTorch。",
            "a64 = torch.tensor([[1.0, 1.0], [1.0, 1.0001]], dtype=torch.float64)  # 用 float64 创建近奇异矩阵。",
            "b64 = torch.tensor([2.0, 2.0001], dtype=torch.float64)  # 创建精确解应为 [1,1] 的右端。",
            "x64 = torch.linalg.solve(a64, b64)  # 使用双精度求解。",
            "a32, b32 = a64.float(), b64.float()  # 转换为单精度版本。",
            "x32 = torch.linalg.solve(a32, b32)  # 使用单精度求解。",
            "residual64 = torch.linalg.vector_norm(a64 @ x64 - b64)  # 计算双精度残差。",
            "residual32 = torch.linalg.vector_norm(a32 @ x32 - b32)  # 计算单精度残差。",
            "assert torch.allclose(x64, torch.ones(2, dtype=torch.float64), atol=1e-8)  # 验证高精度解。",
            "print(x32, x64, residual32, residual64)  # 比较精度和残差。",
        ],
    ),
]
