"""机器学习原理与面试计算题定义。"""

from __future__ import annotations


LEVELS = ["基础", "变式", "易错点", "综合"]


def ml_case(family: int, variant: int) -> tuple[str, str, list[str]]:
    titles = [
        "训练验证测试集与数据泄漏",
        "标准化与归一化",
        "线性回归正规方程",
        "梯度下降",
        "逻辑回归与Sigmoid",
        "MSEMAE与Huber损失",
        "L1L2正则化",
        "偏差方差与过拟合",
        "交叉验证",
        "混淆矩阵与分类指标",
        "ROC与AUC",
        "类别不平衡与阈值",
        "KNN与距离度量",
        "决策树Gini与Entropy",
        "Bagging与Boosting",
        "SVM间隔与hinge loss",
        "KMeans聚类",
        "PCA降维",
        "特征选择与互信息思想",
        "概率校准与Brier分数",
        "早停与最佳模型",
        "学习曲线",
        "数据漂移PSI",
        "时间序列切分",
        "可复现性与随机种子",
    ]
    title = titles[family]
    task = f"完成“{title}”的{LEVELS[variant - 1]}题，计算结果并回答为什么不能使用错误做法。"
    n = variant + 2
    cases: list[list[str]] = [
        [
            "import numpy as np  # 导入 NumPy。",
            "rng = np.random.default_rng(42)  # 固定切分随机性。",
            "indices = rng.permutation(100)  # 先打乱样本索引。",
            "train, valid, test = indices[:60], indices[60:80], indices[80:]  # 按60/20/20切分。",
            "features = np.arange(100, dtype=float)  # 构造单特征数据。",
            "train_mean = features[train].mean()  # 只在训练集拟合预处理统计量。",
            "standardized_test = features[test] - train_mean  # 用训练统计量转换测试集。",
            "assert not set(train) & set(test) and len(standardized_test) == 20  # 验证集合互斥和测试样本数。",
            "print(train_mean, standardized_test[:3])  # 输出无泄漏处理结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "matrix = np.array([[1.0, 10.0], [2.0, 20.0], [3.0, 40.0]])  # 创建尺度差异明显的特征。",
            "mean, std = matrix.mean(0), matrix.std(0)  # 计算总体均值和标准差。",
            "standardized = (matrix - mean) / std  # Z-score标准化使均值0方差1。",
            "minimum, maximum = matrix.min(0), matrix.max(0)  # 计算每列极值。",
            "normalized = (matrix - minimum) / (maximum - minimum)  # Min-Max归一化到[0,1]。",
            "assert np.allclose(standardized.mean(0), 0) and np.allclose(normalized.min(0), 0)  # 验证缩放性质。",
            "print(standardized, '\\n', normalized)  # 输出两种缩放。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "x = np.arange(1, 6, dtype=float)[:, None]  # 创建单特征样本列。",
            f"y = {n} * x[:, 0] + 2  # 按线性规律生成目标。",
            "design = np.c_[np.ones(len(x)), x]  # 添加截距列形成设计矩阵。",
            "weights = np.linalg.pinv(design) @ y  # 使用伪逆求最小二乘解。",
            "predictions = design @ weights  # 计算训练预测。",
            "r_squared = 1 - ((y - predictions) ** 2).sum() / ((y - y.mean()) ** 2).sum()  # 计算R²。",
            f"assert np.allclose(weights, [2, {n}]) and np.isclose(r_squared, 1)  # 验证恢复真实参数。",
            "print(weights, r_squared)  # 输出回归系数和拟合优度。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "x = np.array([1.0, 2.0, 3.0])  # 创建训练特征。",
            "y = 2 * x + 1  # 创建线性目标。",
            "weight, bias = 0.0, 0.0  # 初始化模型参数。",
            f"learning_rate = {0.03 + variant * 0.01}  # 设置学习率。",
            "for _ in range(500):  # 迭代梯度下降。",
            "    errors = weight * x + bias - y  # 计算预测残差。",
            "    weight -= learning_rate * 2 * np.mean(errors * x)  # 更新权重。",
            "    bias -= learning_rate * 2 * np.mean(errors)  # 更新偏置。",
            "assert abs(weight - 2) < 0.05 and abs(bias - 1) < 0.1  # 验证收敛到真实参数。",
            "print(weight, bias)  # 输出优化结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "logits = np.array([-3.0, 0.0, 2.0])  # 构造模型logits。",
            "probabilities = 1 / (1 + np.exp(-logits))  # 使用Sigmoid转换为正类概率。",
            "labels = np.array([0.0, 1.0, 1.0])  # 定义二分类标签。",
            "epsilon = 1e-12  # 防止对0取log。",
            "log_loss = -(labels * np.log(probabilities + epsilon) + (1 - labels) * np.log(1 - probabilities + epsilon)).mean()  # 手算二元交叉熵。",
            f"predictions = probabilities >= {0.4 + variant * 0.05}  # 使用阈值转类别。",
            "assert np.all((0 < probabilities) & (probabilities < 1))  # 验证概率范围。",
            "print(probabilities, predictions, log_loss)  # 输出逻辑回归结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "targets = np.array([1.0, 2.0, 3.0, 20.0])  # 构造含离群点目标。",
            "predictions = np.array([1.2, 1.8, 3.1, 5.0])  # 构造预测。",
            "errors = predictions - targets  # 计算残差。",
            "mse = np.mean(errors**2)  # MSE对大误差平方惩罚。",
            "mae = np.mean(np.abs(errors))  # MAE对离群点更稳健。",
            f"delta = {float(n)}  # 设置Huber转折点。",
            "huber = np.mean(np.where(np.abs(errors) <= delta, 0.5 * errors**2, delta * (np.abs(errors) - 0.5 * delta)))  # 分段计算Huber损失。",
            "assert mse > mae  # 本例离群点使MSE明显更大。",
            "print(mse, mae, huber)  # 输出三种回归损失。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "weights = np.array([3.0, -1.0, 0.2, 0.0])  # 构造模型权重。",
            f"strength = {variant * 0.1}  # 设置正则化强度。",
            "l1_penalty = strength * np.abs(weights).sum()  # L1倾向产生稀疏权重。",
            "l2_penalty = strength * (weights**2).sum()  # L2平滑缩小大权重。",
            "l1_subgradient = strength * np.sign(weights)  # 计算非零处L1次梯度。",
            "l2_gradient = 2 * strength * weights  # 计算L2梯度。",
            "assert l1_penalty >= 0 and l2_penalty >= 0  # 正则项应非负。",
            "print(l1_penalty, l2_penalty, l1_subgradient, l2_gradient)  # 输出惩罚和梯度。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "train_errors = np.array([0.40, 0.25, 0.12, 0.05])  # 模型复杂度增大时训练误差下降。",
            "validation_errors = np.array([0.45, 0.28, 0.18, 0.30])  # 验证误差先降后升。",
            "best_complexity = validation_errors.argmin() + 1  # 用验证集选择复杂度。",
            "generalization_gap = validation_errors - train_errors  # 计算泛化差距。",
            f"high_variance = generalization_gap[-1] > {variant * 0.04}  # 判断复杂模型是否高方差。",
            "assert best_complexity == 3  # 验证选择验证误差最低模型。",
            "print(best_complexity, generalization_gap, high_variance)  # 输出偏差方差线索。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "indices = np.arange(12)  # 创建样本索引。",
            f"fold_count = {variant + 2}  # 设置K折数量。",
            "folds = np.array_split(indices, fold_count)  # 把样本近似等分。",
            "validation_seen = []  # 记录各折验证样本。",
            "for fold in range(fold_count):  # 每一折轮流作为验证集。",
            "    validation = folds[fold]  # 选择当前验证折。",
            "    training = np.concatenate([part for index, part in enumerate(folds) if index != fold])  # 合并其余训练折。",
            "    assert not set(training) & set(validation)  # 验证单折无交集。",
            "    validation_seen.extend(validation.tolist())  # 收集验证覆盖。",
            "assert sorted(validation_seen) == indices.tolist()  # 验证每个样本恰做一次验证。",
            "print([len(fold) for fold in folds])  # 输出各折大小。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "targets = np.array([1, 1, 1, 0, 0, 0])  # 创建真实二分类标签。",
            "predictions = np.array([1, 1, 0, 1, 0, 0])  # 创建预测。",
            "tp = np.sum((targets == 1) & (predictions == 1))  # 计算真正例。",
            "fp = np.sum((targets == 0) & (predictions == 1))  # 计算假正例。",
            "fn = np.sum((targets == 1) & (predictions == 0))  # 计算假负例。",
            "tn = np.sum((targets == 0) & (predictions == 0))  # 计算真负例。",
            "precision = tp / (tp + fp)  # 计算查准率。",
            "recall = tp / (tp + fn)  # 计算查全率。",
            "f1 = 2 * precision * recall / (precision + recall)  # 计算F1调和平均。",
            "assert tp + fp + fn + tn == len(targets)  # 验证混淆矩阵覆盖全部样本。",
            "print(tp, fp, fn, tn, precision, recall, f1)  # 输出分类指标。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "from sklearn.metrics import roc_auc_score, roc_curve  # 导入可靠的ROC工具。",
            "targets = np.array([0, 0, 1, 1])  # 创建真实标签。",
            "scores = np.array([0.1, 0.4, 0.35, 0.8])  # 创建连续正类分数。",
            "false_positive_rate, true_positive_rate, thresholds = roc_curve(targets, scores)  # 扫描所有阈值得到ROC点。",
            "auc = roc_auc_score(targets, scores)  # AUC等价于随机正样本得分高于负样本的概率。",
            "assert np.isclose(auc, 0.75)  # 验证经典例子AUC。",
            "print(false_positive_rate, true_positive_rate, thresholds, auc)  # 输出ROC曲线数据。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "targets = np.array([1, 1, 0, 0, 0, 0, 0, 0])  # 构造不平衡标签。",
            "scores = np.array([0.9, 0.45, 0.7, 0.4, 0.3, 0.2, 0.1, 0.05])  # 构造模型概率。",
            f"threshold = {0.3 + variant * 0.1}  # 根据业务代价调整阈值。",
            "predictions = scores >= threshold  # 把概率转类别。",
            "recall = np.sum(predictions & (targets == 1)) / np.sum(targets == 1)  # 计算少数类召回率。",
            "balanced_weight = len(targets) / (2 * np.bincount(targets))  # 计算常见balanced类别权重。",
            "assert len(balanced_weight) == 2  # 验证每类一个权重。",
            "print(threshold, predictions, recall, balanced_weight)  # 输出阈值和不平衡处理信息。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "training = np.array([[0.0, 0.0], [1.0, 1.0], [4.0, 4.0], [5.0, 5.0]])  # 创建二维训练点。",
            "labels = np.array([0, 0, 1, 1])  # 创建类别标签。",
            "query = np.array([3.5, 3.5])  # 创建待预测样本。",
            "distances = np.linalg.norm(training - query, axis=1)  # 计算欧氏距离。",
            f"k = {variant if variant % 2 == 1 else variant + 1}  # KNN分类常使用奇数k减少平票。",
            "neighbors = np.argsort(distances)[:k]  # 找到最近k个样本。",
            "prediction = np.bincount(labels[neighbors], minlength=2).argmax()  # 多数投票。",
            "assert prediction in (0, 1)  # 验证合法类别。",
            "print(distances, neighbors, prediction)  # 输出邻居和预测。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "counts = np.array([6.0, 4.0])  # 表示节点中的两类样本数。",
            "probabilities = counts / counts.sum()  # 计算类别概率。",
            "gini = 1 - np.sum(probabilities**2)  # 计算Gini不纯度。",
            "entropy = -np.sum(probabilities * np.log2(probabilities, where=probabilities > 0))  # 计算信息熵。",
            "left_counts = np.array([5.0, 1.0])  # 构造左子节点类别计数。",
            "right_counts = counts - left_counts  # 构造右子节点类别计数。",
            "weighted_gini = (left_counts.sum() * (1 - np.sum((left_counts / left_counts.sum()) ** 2)) + right_counts.sum() * (1 - np.sum((right_counts / right_counts.sum()) ** 2))) / counts.sum()  # 计算切分后加权Gini。",
            "gain = gini - weighted_gini  # 不纯度下降即切分收益。",
            "assert gain > 0  # 验证该切分改善纯度。",
            "print(gini, entropy, weighted_gini, gain)  # 输出树切分指标。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "predictions = np.array([[0, 1, 1, 0], [0, 1, 0, 0], [1, 1, 1, 0]])  # 三个基学习器的分类结果。",
            "bagging_vote = (predictions.mean(axis=0) >= 0.5).astype(int)  # Bagging并行模型多数投票降低方差。",
            "weak_outputs = np.array([0.2, -0.4, 0.7])  # 构造Boosting弱学习器输出。",
            f"weights = np.array([0.2, 0.3, {0.4 + variant * 0.05}])  # 后续学习器按性能加权。",
            "boosting_score = np.dot(weights, weak_outputs)  # Boosting串行加权纠错。",
            "assert bagging_vote.shape == (4,)  # 验证集成输出shape。",
            "print(bagging_vote, boosting_score)  # 输出两类集成思想结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "weights = np.array([1.0, -1.0])  # 定义线性分类超平面法向量。",
            "features = np.array([[2.0, 0.0], [0.0, 2.0], [1.0, 0.5]])  # 创建训练样本。",
            "labels = np.array([1.0, -1.0, 1.0])  # SVM标签使用-1和1。",
            "scores = features @ weights  # 计算到超平面的有符号分数。",
            "margins = labels * scores  # 计算功能间隔。",
            "hinge = np.maximum(0, 1 - margins)  # 计算hinge loss。",
            "geometric_margin = margins / np.linalg.norm(weights)  # 除以权重范数得到几何间隔。",
            "assert np.all(hinge >= 0)  # 验证损失非负。",
            "print(scores, margins, hinge, geometric_margin)  # 输出SVM关键量。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "points = np.array([[0.0, 0.0], [0.0, 1.0], [5.0, 5.0], [5.0, 6.0]])  # 创建两个明显簇。",
            "centers = np.array([[0.0, 0.0], [5.0, 5.0]])  # 初始化两个中心。",
            "for _ in range(5):  # 交替执行分配和更新。",
            "    distances = ((points[:, None, :] - centers[None, :, :]) ** 2).sum(axis=2)  # 计算样本到各中心平方距离。",
            "    assignments = distances.argmin(axis=1)  # 分配到最近中心。",
            "    centers = np.stack([points[assignments == cluster].mean(axis=0) for cluster in range(2)])  # 更新为簇均值。",
            "inertia = np.sum((points - centers[assignments]) ** 2)  # 计算簇内平方和。",
            "assert inertia <= 1.0  # 验证简单数据被正确聚类。",
            "print(assignments, centers, inertia)  # 输出聚类结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "samples = np.array([[2.0, 0.0], [0.0, 2.0], [3.0, 1.0], [1.0, 3.0]])  # 创建二维样本。",
            "centered = samples - samples.mean(axis=0)  # PCA前必须中心化。",
            "covariance = centered.T @ centered / (len(samples) - 1)  # 计算协方差矩阵。",
            "eigenvalues, eigenvectors = np.linalg.eigh(covariance)  # 对称矩阵特征分解。",
            "order = eigenvalues.argsort()[::-1]  # 按解释方差降序。",
            f"components = eigenvectors[:, order[:1]]  # 选取第一个主成分用于变式{variant}。",
            "projected = centered @ components  # 投影到低维空间。",
            "explained_ratio = eigenvalues[order] / eigenvalues.sum()  # 计算解释方差比。",
            "assert projected.shape == (4, 1)  # 验证降维shape。",
            "print(components, projected, explained_ratio)  # 输出PCA结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "features = np.array([[0, 0, 1], [0, 1, 1], [1, 0, 0], [1, 1, 0]])  # 创建三个二值特征。",
            "target = np.array([0, 0, 1, 1])  # 第一个特征完全决定标签。",
            "correlations = np.array([np.corrcoef(features[:, index], target)[0, 1] for index in range(features.shape[1])])  # 用相关性演示单变量筛选。",
            "selected = np.abs(correlations).argmax()  # 选择绝对相关最高特征。",
            "variance = features.var(axis=0)  # 低方差筛选与标签无关。",
            f"keep_variance = variance >= {0.1 * variant}  # 使用方差阈值。",
            "assert selected == 0  # 验证找到最直接相关特征。",
            "print(correlations, variance, keep_variance, selected)  # 输出筛选依据。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "probabilities = np.array([0.1, 0.4, 0.8, 0.9])  # 创建模型概率。",
            "targets = np.array([0.0, 1.0, 1.0, 1.0])  # 创建真实标签。",
            "brier = np.mean((probabilities - targets) ** 2)  # Brier分数衡量概率校准和准确性。",
            "hard_predictions = probabilities >= 0.5  # 转为硬分类仅用于accuracy。",
            "accuracy = np.mean(hard_predictions == targets)  # 计算准确率。",
            "overconfident = np.clip(probabilities * 1.1, 0, 1)  # 构造更极端的概率。",
            "overconfident_brier = np.mean((overconfident - targets) ** 2)  # 比较校准误差。",
            "assert 0 <= brier <= 1  # 验证Brier范围。",
            "print(brier, accuracy, overconfident_brier)  # 输出概率与硬指标。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "validation_loss = np.array([0.9, 0.7, 0.55, 0.50, 0.52, 0.58, 0.61])  # 构造验证损失轨迹。",
            f"patience = {variant}  # 设置连续无改进容忍轮数。",
            "best_loss = np.inf  # 初始化最佳损失。",
            "best_epoch = -1  # 初始化最佳轮次。",
            "wait = 0  # 初始化等待计数。",
            "for epoch, loss in enumerate(validation_loss):  # 逐轮检查验证损失。",
            "    if loss < best_loss:  # 发现严格改进。",
            "        best_loss, best_epoch, wait = loss, epoch, 0  # 保存最佳状态并清零等待。",
            "    else:  # 当前轮没有改进。",
            "        wait += 1  # 累加等待轮数。",
            "        if wait >= patience:  # 达到patience则停止。",
            "            break  # 退出训练循环。",
            "assert best_epoch == 3  # 验证最优模型出现在第3轮零基索引。",
            "print(best_epoch, best_loss, epoch)  # 输出最佳和停止轮次。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "train_sizes = np.array([20, 50, 100, 200])  # 创建训练样本规模。",
            "train_scores = np.array([0.99, 0.95, 0.91, 0.89])  # 训练分数随样本增加可能下降。",
            "validation_scores = np.array([0.60, 0.72, 0.80, 0.85])  # 验证分数随样本增加改善。",
            "gaps = train_scores - validation_scores  # 计算泛化差距。",
            "more_data_helped = validation_scores[-1] > validation_scores[0] and gaps[-1] < gaps[0]  # 判断增加数据是否改善高方差。",
            f"target_gap = {variant * 0.03}  # 设置期望泛化差距。",
            "needs_more_data = gaps[-1] > target_gap  # 根据目标判断是否继续收集数据。",
            "assert more_data_helped  # 验证学习曲线趋势。",
            "print(train_sizes, gaps, needs_more_data)  # 输出学习曲线诊断。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "reference = np.array([0.50, 0.30, 0.15, 0.05])  # 创建训练期分箱比例。",
            "current = np.array([0.35, 0.30, 0.20, 0.15])  # 创建当前期分箱比例。",
            "epsilon = 1e-6  # 防止除零和log零。",
            "psi_parts = (current - reference) * np.log((current + epsilon) / (reference + epsilon))  # 计算各箱PSI贡献。",
            "psi = psi_parts.sum()  # 汇总Population Stability Index。",
            f"drift_detected = psi > {variant * 0.05}  # 使用示例阈值判断漂移。",
            "assert psi >= 0  # PSI理论上非负。",
            "print(psi_parts, psi, drift_detected)  # 输出漂移指标。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "time = np.arange(20)  # 创建按时间排序样本。",
            f"test_size = {variant + 2}  # 设置滚动验证窗口大小。",
            "splits = []  # 保存时间序列切分。",
            "for train_end in range(8, 20 - test_size + 1, test_size):  # 逐步扩展训练窗口。",
            "    train = time[:train_end]  # 训练只能使用过去。",
            "    validation = time[train_end:train_end + test_size]  # 验证使用紧随其后的未来。",
            "    splits.append((train, validation))  # 保存本折。",
            "assert all(train.max() < validation.min() for train, validation in splits)  # 验证没有未来信息泄漏。",
            "print([(len(train), validation.tolist()) for train, validation in splits])  # 输出时间切分。",
        ],
        [
            "import random  # 导入Python随机模块。",
            "import numpy as np  # 导入 NumPy。",
            f"seed = {40 + variant}  # 设置统一随机种子。",
            "random.seed(seed)  # 固定Python随机性。",
            "np_rng = np.random.default_rng(seed)  # 创建局部NumPy Generator。",
            "python_values = [random.random() for _ in range(3)]  # 采样Python随机数。",
            "numpy_values = np_rng.normal(size=3)  # 采样NumPy随机数。",
            "random.seed(seed)  # 重置Python种子验证复现。",
            "assert python_values == [random.random() for _ in range(3)]  # 验证Python随机序列复现。",
            "assert np.allclose(numpy_values, np.random.default_rng(seed).normal(size=3))  # 验证NumPy随机序列复现。",
            "print(seed, python_values, numpy_values)  # 输出可复现样本。",
        ],
    ]
    return title, task, cases[family]
