"""机器学习原理与面试计算题定义。"""

from __future__ import annotations

from case_utils import independent_variant


LEVELS = ["基础", "变式", "易错点", "综合"]


def ml_case(family: int, variant: int) -> tuple[str, str, list[str]]:
    titles = [
        "训练验证测试集与数据泄漏",
        "标准化与归一化",
        "线性回归正规方程",
        "梯度下降",
        "逻辑回归与Sigmoid",
        "MSEMAE与Huber损失",
        "L1L2正则化",
        "偏差方差与过拟合",
        "交叉验证",
        "混淆矩阵与分类指标",
        "ROC与AUC",
        "类别不平衡与阈值",
        "KNN与距离度量",
        "决策树Gini与Entropy",
        "Bagging与Boosting",
        "SVM间隔与hinge loss",
        "KMeans聚类",
        "PCA降维",
        "特征选择与互信息思想",
        "概率校准与Brier分数",
        "早停与最佳模型",
        "学习曲线",
        "数据漂移PSI",
        "时间序列切分",
        "可复现性与随机种子",
    ]
    title = titles[family]
    task = f"完成“{title}”的{LEVELS[variant - 1]}题，计算结果并回答为什么不能使用错误做法。"
    n = variant + 2
    permutation_alternatives = [
        "# -------------------- 其他写法（以下代码作为知识补充，不会执行） --------------------",
        "# 写法A：先创建连续索引，再原地shuffle；结果和permutation一样是不重复的全排列。",
        "# alternative_indices = np.arange(100)  # 创建0到99且不重复的索引。",
        "# rng.shuffle(alternative_indices)  # 原地打乱；注意该方法会修改原数组。",
        "# 写法B：使用choice且设置replace=False，也能进行无放回抽样。",
        "# alternative_indices = rng.choice(100, size=100, replace=False)  # 无放回抽取全部索引。",
        "# 写法C：如果只需要随机抽取20个测试索引，可以不生成完整排列。",
        "# test_indices = rng.choice(100, size=20, replace=False)  # 直接无放回抽取测试集索引。",
        "# 易错写法：rng.integers(0, 100, size=100)默认有放回，因此会重复并遗漏部分索引。",
        "# wrong_indices = rng.integers(0, 100, size=100)  # 这是随机整数采样，不是随机排列。",
        "# assert np.unique(wrong_indices).size <= 100  # unique数量通常小于100，不能直接拿来切分数据集。",
    ]
    if family == 0:
        if variant == 1:
            code = [
                "import numpy as np  # 导入 NumPy。",
                "rng = np.random.default_rng(42)  # 固定切分随机性。",
                "indices = rng.permutation(100)  # 一步生成0到99的不重复随机排列。",
                "train, valid, test = indices[:60], indices[60:80], indices[80:]  # 按60/20/20切分。",
                "features = np.arange(100, dtype=float)  # 构造单特征数据。",
                "train_mean = features[train].mean()  # 只在训练集拟合预处理统计量。",
                "standardized_test = features[test] - train_mean  # 用训练统计量转换测试集。",
                "assert not set(train) & set(test) and len(standardized_test) == 20  # 验证集合互斥和测试样本数。",
                "print(train_mean, standardized_test[:3])  # 输出无泄漏处理结果。",
                *permutation_alternatives,
            ]
        elif variant == 2:
            code = [
                "import numpy as np  # 导入 NumPy。",
                "rng = np.random.default_rng(42)  # 固定切分随机性。",
                "labels = np.array([0] * 80 + [1] * 20)  # 构造类别比例为80比20的不平衡标签。",
                "class_zero = rng.permutation(np.flatnonzero(labels == 0))  # 单独打乱类别0的样本索引。",
                "class_one = rng.permutation(np.flatnonzero(labels == 1))  # 单独打乱类别1的样本索引。",
                "train = np.r_[class_zero[:48], class_one[:12]]  # 每类取60%组成训练集。",
                "valid = np.r_[class_zero[48:64], class_one[12:16]]  # 每类取20%组成验证集。",
                "test = np.r_[class_zero[64:], class_one[16:]]  # 每类剩余20%组成测试集。",
                "ratios = [labels[part].mean() for part in (train, valid, test)]  # 计算三个集合的正类比例。",
                "assert np.allclose(ratios, 0.2)  # 验证分层切分保持原始类别比例。",
                "print([len(train), len(valid), len(test)], ratios)  # 输出集合大小和类别比例。",
                "# -------------------- 其他写法（以下代码作为知识补充，不会执行） --------------------",
                "# 写法A：scikit-learn可以连续两次分层切分，生产代码更常用。",
                "# from sklearn.model_selection import train_test_split  # 导入官方切分工具。",
                "# train_idx, temp_idx = train_test_split(np.arange(100), test_size=0.4, stratify=labels, random_state=42)  # 先切训练集。",
                "# valid_idx, test_idx = train_test_split(temp_idx, test_size=0.5, stratify=labels[temp_idx], random_state=42)  # 再平分临时集。",
                *permutation_alternatives,
            ]
        elif variant == 3:
            code = [
                "import numpy as np  # 导入 NumPy。",
                "train_features = np.arange(80, dtype=float)  # 构造训练期特征。",
                "test_features = np.arange(1000, 1020, dtype=float)  # 构造发生分布变化的测试期特征。",
                "train_mean = train_features.mean()  # 正确做法只用训练集计算均值。",
                "leaked_mean = np.r_[train_features, test_features].mean()  # 错误做法偷看测试集后计算均值。",
                "correct_test = test_features - train_mean  # 使用训练统计量转换测试集。",
                "leaked_test = test_features - leaked_mean  # 使用泄漏统计量会人为改变测试分布。",
                "difference = np.abs(correct_test - leaked_test).mean()  # 衡量两种转换结果的平均差异。",
                "assert difference > 0 and train_mean != leaked_mean  # 验证测试信息确实污染了预处理参数。",
                "print(train_mean, leaked_mean, difference)  # 输出正确与泄漏结果。",
                "# -------------------- 其他写法（以下代码作为知识补充，不会执行） --------------------",
                "# 写法A：StandardScaler同样必须先fit训练集，再分别transform训练集和测试集。",
                "# from sklearn.preprocessing import StandardScaler  # 导入标准化器。",
                "# scaler = StandardScaler().fit(train_features.reshape(-1, 1))  # 只在训练集拟合。",
                "# scaled_test = scaler.transform(test_features.reshape(-1, 1))  # 使用训练统计量转换测试集。",
                "# 错误写法：scaler.fit_transform(np.r_[train_features, test_features].reshape(-1, 1))会发生数据泄漏。",
                *permutation_alternatives,
            ]
        else:
            code = [
                "import numpy as np  # 导入 NumPy。",
                "rng = np.random.default_rng(42)  # 固定随机性。",
                "features = np.linspace(-3, 3, 120)  # 构造一维回归特征。",
                "targets = 1.5 * features**2 + 2 * features + rng.normal(0, 0.8, 120)  # 构造带噪声二次目标。",
                "indices = rng.permutation(len(features))  # 生成无重复随机索引。",
                "train, valid, test = indices[:72], indices[72:96], indices[96:]  # 按60/20/20切分。",
                "candidate_degrees = [1, 2, 5]  # 设置欠拟合、合适和偏复杂的候选模型。",
                "validation_mse = []  # 保存每个候选模型的验证误差。",
                "for degree in candidate_degrees:  # 只使用训练集拟合并用验证集选择模型。",
                "    coefficients = np.polyfit(features[train], targets[train], degree)  # 在训练集拟合多项式。",
                "    predictions = np.polyval(coefficients, features[valid])  # 在验证集计算预测。",
                "    validation_mse.append(np.mean((predictions - targets[valid]) ** 2))  # 保存验证MSE。",
                "best_degree = candidate_degrees[int(np.argmin(validation_mse))]  # 根据验证误差选择复杂度。",
                "final_coefficients = np.polyfit(features[np.r_[train, valid]], targets[np.r_[train, valid]], best_degree)  # 用训练加验证数据重训最终模型。",
                "test_predictions = np.polyval(final_coefficients, features[test])  # 最终只评估一次测试集。",
                "test_mse = np.mean((test_predictions - targets[test]) ** 2)  # 计算最终泛化误差。",
                "assert best_degree in candidate_degrees and np.isfinite(test_mse)  # 验证模型选择和测试结果有效。",
                "print(validation_mse, best_degree, test_mse)  # 输出完整模型选择结果。",
                "# -------------------- 其他写法（以下代码作为知识补充，不会执行） --------------------",
                "# 写法A：小数据集可用K折交叉验证代替单一验证集，让模型选择更稳定。",
                "# from sklearn.model_selection import KFold, cross_val_score  # 导入交叉验证工具。",
                "# 写法B：使用Pipeline把PolynomialFeatures和LinearRegression封装，避免预处理泄漏。",
                "# from sklearn.pipeline import make_pipeline  # 导入流水线。",
                "# from sklearn.preprocessing import PolynomialFeatures  # 导入多项式特征。",
                "# from sklearn.linear_model import LinearRegression  # 导入线性回归。",
                "# model = make_pipeline(PolynomialFeatures(degree=2), LinearRegression())  # 创建可交叉验证的完整流水线。",
                *permutation_alternatives,
            ]
        return title, task, code
    cases: list[list[str]] = [
        [
            "import numpy as np  # 导入 NumPy。",
            "rng = np.random.default_rng(42)  # 固定切分随机性。",
            "indices = rng.permutation(100)  # 先打乱样本索引。",
            "train, valid, test = indices[:60], indices[60:80], indices[80:]  # 按60/20/20切分。",
            "features = np.arange(100, dtype=float)  # 构造单特征数据。",
            "train_mean = features[train].mean()  # 只在训练集拟合预处理统计量。",
            "standardized_test = features[test] - train_mean  # 用训练统计量转换测试集。",
            "assert not set(train) & set(test) and len(standardized_test) == 20  # 验证集合互斥和测试样本数。",
            "print(train_mean, standardized_test[:3])  # 输出无泄漏处理结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "matrix = np.array([[1.0, 10.0], [2.0, 20.0], [3.0, 40.0]])  # 创建尺度差异明显的特征。",
            "mean, std = matrix.mean(0), matrix.std(0)  # 计算总体均值和标准差。",
            "standardized = (matrix - mean) / std  # Z-score标准化使均值0方差1。",
            "minimum, maximum = matrix.min(0), matrix.max(0)  # 计算每列极值。",
            "normalized = (matrix - minimum) / (maximum - minimum)  # Min-Max归一化到[0,1]。",
            "assert np.allclose(standardized.mean(0), 0) and np.allclose(normalized.min(0), 0)  # 验证缩放性质。",
            "print(standardized, '\\n', normalized)  # 输出两种缩放。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "x = np.arange(1, 6, dtype=float)[:, None]  # 创建单特征样本列。",
            f"y = {n} * x[:, 0] + 2  # 按线性规律生成目标。",
            "design = np.c_[np.ones(len(x)), x]  # 添加截距列形成设计矩阵。",
            "weights = np.linalg.pinv(design) @ y  # 使用伪逆求最小二乘解。",
            "predictions = design @ weights  # 计算训练预测。",
            "r_squared = 1 - ((y - predictions) ** 2).sum() / ((y - y.mean()) ** 2).sum()  # 计算R²。",
            f"assert np.allclose(weights, [2, {n}]) and np.isclose(r_squared, 1)  # 验证恢复真实参数。",
            "print(weights, r_squared)  # 输出回归系数和拟合优度。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "x = np.array([1.0, 2.0, 3.0])  # 创建训练特征。",
            "y = 2 * x + 1  # 创建线性目标。",
            "weight, bias = 0.0, 0.0  # 初始化模型参数。",
            f"learning_rate = {0.03 + variant * 0.01}  # 设置学习率。",
            "for _ in range(500):  # 迭代梯度下降。",
            "    errors = weight * x + bias - y  # 计算预测残差。",
            "    weight -= learning_rate * 2 * np.mean(errors * x)  # 更新权重。",
            "    bias -= learning_rate * 2 * np.mean(errors)  # 更新偏置。",
            "assert abs(weight - 2) < 0.05 and abs(bias - 1) < 0.1  # 验证收敛到真实参数。",
            "print(weight, bias)  # 输出优化结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "logits = np.array([-3.0, 0.0, 2.0])  # 构造模型logits。",
            "probabilities = 1 / (1 + np.exp(-logits))  # 使用Sigmoid转换为正类概率。",
            "labels = np.array([0.0, 1.0, 1.0])  # 定义二分类标签。",
            "epsilon = 1e-12  # 防止对0取log。",
            "log_loss = -(labels * np.log(probabilities + epsilon) + (1 - labels) * np.log(1 - probabilities + epsilon)).mean()  # 手算二元交叉熵。",
            f"predictions = probabilities >= {0.4 + variant * 0.05}  # 使用阈值转类别。",
            "assert np.all((0 < probabilities) & (probabilities < 1))  # 验证概率范围。",
            "print(probabilities, predictions, log_loss)  # 输出逻辑回归结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "targets = np.array([1.0, 2.0, 3.0, 20.0])  # 构造含离群点目标。",
            "predictions = np.array([1.2, 1.8, 3.1, 5.0])  # 构造预测。",
            "errors = predictions - targets  # 计算残差。",
            "mse = np.mean(errors**2)  # MSE对大误差平方惩罚。",
            "mae = np.mean(np.abs(errors))  # MAE对离群点更稳健。",
            f"delta = {float(n)}  # 设置Huber转折点。",
            "huber = np.mean(np.where(np.abs(errors) <= delta, 0.5 * errors**2, delta * (np.abs(errors) - 0.5 * delta)))  # 分段计算Huber损失。",
            "assert mse > mae  # 本例离群点使MSE明显更大。",
            "print(mse, mae, huber)  # 输出三种回归损失。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "weights = np.array([3.0, -1.0, 0.2, 0.0])  # 构造模型权重。",
            f"strength = {variant * 0.1}  # 设置正则化强度。",
            "l1_penalty = strength * np.abs(weights).sum()  # L1倾向产生稀疏权重。",
            "l2_penalty = strength * (weights**2).sum()  # L2平滑缩小大权重。",
            "l1_subgradient = strength * np.sign(weights)  # 计算非零处L1次梯度。",
            "l2_gradient = 2 * strength * weights  # 计算L2梯度。",
            "assert l1_penalty >= 0 and l2_penalty >= 0  # 正则项应非负。",
            "print(l1_penalty, l2_penalty, l1_subgradient, l2_gradient)  # 输出惩罚和梯度。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "train_errors = np.array([0.40, 0.25, 0.12, 0.05])  # 模型复杂度增大时训练误差下降。",
            "validation_errors = np.array([0.45, 0.28, 0.18, 0.30])  # 验证误差先降后升。",
            "best_complexity = validation_errors.argmin() + 1  # 用验证集选择复杂度。",
            "generalization_gap = validation_errors - train_errors  # 计算泛化差距。",
            f"high_variance = generalization_gap[-1] > {variant * 0.04}  # 判断复杂模型是否高方差。",
            "assert best_complexity == 3  # 验证选择验证误差最低模型。",
            "print(best_complexity, generalization_gap, high_variance)  # 输出偏差方差线索。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "indices = np.arange(12)  # 创建样本索引。",
            f"fold_count = {variant + 2}  # 设置K折数量。",
            "folds = np.array_split(indices, fold_count)  # 把样本近似等分。",
            "validation_seen = []  # 记录各折验证样本。",
            "for fold in range(fold_count):  # 每一折轮流作为验证集。",
            "    validation = folds[fold]  # 选择当前验证折。",
            "    training = np.concatenate([part for index, part in enumerate(folds) if index != fold])  # 合并其余训练折。",
            "    assert not set(training) & set(validation)  # 验证单折无交集。",
            "    validation_seen.extend(validation.tolist())  # 收集验证覆盖。",
            "assert sorted(validation_seen) == indices.tolist()  # 验证每个样本恰做一次验证。",
            "print([len(fold) for fold in folds])  # 输出各折大小。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "targets = np.array([1, 1, 1, 0, 0, 0])  # 创建真实二分类标签。",
            "predictions = np.array([1, 1, 0, 1, 0, 0])  # 创建预测。",
            "tp = np.sum((targets == 1) & (predictions == 1))  # 计算真正例。",
            "fp = np.sum((targets == 0) & (predictions == 1))  # 计算假正例。",
            "fn = np.sum((targets == 1) & (predictions == 0))  # 计算假负例。",
            "tn = np.sum((targets == 0) & (predictions == 0))  # 计算真负例。",
            "precision = tp / (tp + fp)  # 计算查准率。",
            "recall = tp / (tp + fn)  # 计算查全率。",
            "f1 = 2 * precision * recall / (precision + recall)  # 计算F1调和平均。",
            "assert tp + fp + fn + tn == len(targets)  # 验证混淆矩阵覆盖全部样本。",
            "print(tp, fp, fn, tn, precision, recall, f1)  # 输出分类指标。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "from sklearn.metrics import roc_auc_score, roc_curve  # 导入可靠的ROC工具。",
            "targets = np.array([0, 0, 1, 1])  # 创建真实标签。",
            "scores = np.array([0.1, 0.4, 0.35, 0.8])  # 创建连续正类分数。",
            "false_positive_rate, true_positive_rate, thresholds = roc_curve(targets, scores)  # 扫描所有阈值得到ROC点。",
            "auc = roc_auc_score(targets, scores)  # AUC等价于随机正样本得分高于负样本的概率。",
            "assert np.isclose(auc, 0.75)  # 验证经典例子AUC。",
            "print(false_positive_rate, true_positive_rate, thresholds, auc)  # 输出ROC曲线数据。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "targets = np.array([1, 1, 0, 0, 0, 0, 0, 0])  # 构造不平衡标签。",
            "scores = np.array([0.9, 0.45, 0.7, 0.4, 0.3, 0.2, 0.1, 0.05])  # 构造模型概率。",
            f"threshold = {0.3 + variant * 0.1}  # 根据业务代价调整阈值。",
            "predictions = scores >= threshold  # 把概率转类别。",
            "recall = np.sum(predictions & (targets == 1)) / np.sum(targets == 1)  # 计算少数类召回率。",
            "balanced_weight = len(targets) / (2 * np.bincount(targets))  # 计算常见balanced类别权重。",
            "assert len(balanced_weight) == 2  # 验证每类一个权重。",
            "print(threshold, predictions, recall, balanced_weight)  # 输出阈值和不平衡处理信息。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "training = np.array([[0.0, 0.0], [1.0, 1.0], [4.0, 4.0], [5.0, 5.0]])  # 创建二维训练点。",
            "labels = np.array([0, 0, 1, 1])  # 创建类别标签。",
            "query = np.array([3.5, 3.5])  # 创建待预测样本。",
            "distances = np.linalg.norm(training - query, axis=1)  # 计算欧氏距离。",
            f"k = {variant if variant % 2 == 1 else variant + 1}  # KNN分类常使用奇数k减少平票。",
            "neighbors = np.argsort(distances)[:k]  # 找到最近k个样本。",
            "prediction = np.bincount(labels[neighbors], minlength=2).argmax()  # 多数投票。",
            "assert prediction in (0, 1)  # 验证合法类别。",
            "print(distances, neighbors, prediction)  # 输出邻居和预测。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "counts = np.array([6.0, 4.0])  # 表示节点中的两类样本数。",
            "probabilities = counts / counts.sum()  # 计算类别概率。",
            "gini = 1 - np.sum(probabilities**2)  # 计算Gini不纯度。",
            "entropy = -np.sum(probabilities * np.log2(probabilities, where=probabilities > 0))  # 计算信息熵。",
            "left_counts = np.array([5.0, 1.0])  # 构造左子节点类别计数。",
            "right_counts = counts - left_counts  # 构造右子节点类别计数。",
            "weighted_gini = (left_counts.sum() * (1 - np.sum((left_counts / left_counts.sum()) ** 2)) + right_counts.sum() * (1 - np.sum((right_counts / right_counts.sum()) ** 2))) / counts.sum()  # 计算切分后加权Gini。",
            "gain = gini - weighted_gini  # 不纯度下降即切分收益。",
            "assert gain > 0  # 验证该切分改善纯度。",
            "print(gini, entropy, weighted_gini, gain)  # 输出树切分指标。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "predictions = np.array([[0, 1, 1, 0], [0, 1, 0, 0], [1, 1, 1, 0]])  # 三个基学习器的分类结果。",
            "bagging_vote = (predictions.mean(axis=0) >= 0.5).astype(int)  # Bagging并行模型多数投票降低方差。",
            "weak_outputs = np.array([0.2, -0.4, 0.7])  # 构造Boosting弱学习器输出。",
            f"weights = np.array([0.2, 0.3, {0.4 + variant * 0.05}])  # 后续学习器按性能加权。",
            "boosting_score = np.dot(weights, weak_outputs)  # Boosting串行加权纠错。",
            "assert bagging_vote.shape == (4,)  # 验证集成输出shape。",
            "print(bagging_vote, boosting_score)  # 输出两类集成思想结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "weights = np.array([1.0, -1.0])  # 定义线性分类超平面法向量。",
            "features = np.array([[2.0, 0.0], [0.0, 2.0], [1.0, 0.5]])  # 创建训练样本。",
            "labels = np.array([1.0, -1.0, 1.0])  # SVM标签使用-1和1。",
            "scores = features @ weights  # 计算到超平面的有符号分数。",
            "margins = labels * scores  # 计算功能间隔。",
            "hinge = np.maximum(0, 1 - margins)  # 计算hinge loss。",
            "geometric_margin = margins / np.linalg.norm(weights)  # 除以权重范数得到几何间隔。",
            "assert np.all(hinge >= 0)  # 验证损失非负。",
            "print(scores, margins, hinge, geometric_margin)  # 输出SVM关键量。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "points = np.array([[0.0, 0.0], [0.0, 1.0], [5.0, 5.0], [5.0, 6.0]])  # 创建两个明显簇。",
            "centers = np.array([[0.0, 0.0], [5.0, 5.0]])  # 初始化两个中心。",
            "for _ in range(5):  # 交替执行分配和更新。",
            "    distances = ((points[:, None, :] - centers[None, :, :]) ** 2).sum(axis=2)  # 计算样本到各中心平方距离。",
            "    assignments = distances.argmin(axis=1)  # 分配到最近中心。",
            "    centers = np.stack([points[assignments == cluster].mean(axis=0) for cluster in range(2)])  # 更新为簇均值。",
            "inertia = np.sum((points - centers[assignments]) ** 2)  # 计算簇内平方和。",
            "assert inertia <= 1.0  # 验证简单数据被正确聚类。",
            "print(assignments, centers, inertia)  # 输出聚类结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "samples = np.array([[2.0, 0.0], [0.0, 2.0], [3.0, 1.0], [1.0, 3.0]])  # 创建二维样本。",
            "centered = samples - samples.mean(axis=0)  # PCA前必须中心化。",
            "covariance = centered.T @ centered / (len(samples) - 1)  # 计算协方差矩阵。",
            "eigenvalues, eigenvectors = np.linalg.eigh(covariance)  # 对称矩阵特征分解。",
            "order = eigenvalues.argsort()[::-1]  # 按解释方差降序。",
            f"components = eigenvectors[:, order[:1]]  # 选取第一个主成分用于变式{variant}。",
            "projected = centered @ components  # 投影到低维空间。",
            "explained_ratio = eigenvalues[order] / eigenvalues.sum()  # 计算解释方差比。",
            "assert projected.shape == (4, 1)  # 验证降维shape。",
            "print(components, projected, explained_ratio)  # 输出PCA结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "features = np.array([[0, 0, 1], [0, 1, 1], [1, 0, 0], [1, 1, 0]])  # 创建三个二值特征。",
            "target = np.array([0, 0, 1, 1])  # 第一个特征完全决定标签。",
            "correlations = np.array([np.corrcoef(features[:, index], target)[0, 1] for index in range(features.shape[1])])  # 用相关性演示单变量筛选。",
            "selected = np.abs(correlations).argmax()  # 选择绝对相关最高特征。",
            "variance = features.var(axis=0)  # 低方差筛选与标签无关。",
            f"keep_variance = variance >= {0.1 * variant}  # 使用方差阈值。",
            "assert selected == 0  # 验证找到最直接相关特征。",
            "print(correlations, variance, keep_variance, selected)  # 输出筛选依据。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "probabilities = np.array([0.1, 0.4, 0.8, 0.9])  # 创建模型概率。",
            "targets = np.array([0.0, 1.0, 1.0, 1.0])  # 创建真实标签。",
            "brier = np.mean((probabilities - targets) ** 2)  # Brier分数衡量概率校准和准确性。",
            "hard_predictions = probabilities >= 0.5  # 转为硬分类仅用于accuracy。",
            "accuracy = np.mean(hard_predictions == targets)  # 计算准确率。",
            "overconfident = np.clip(probabilities * 1.1, 0, 1)  # 构造更极端的概率。",
            "overconfident_brier = np.mean((overconfident - targets) ** 2)  # 比较校准误差。",
            "assert 0 <= brier <= 1  # 验证Brier范围。",
            "print(brier, accuracy, overconfident_brier)  # 输出概率与硬指标。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "validation_loss = np.array([0.9, 0.7, 0.55, 0.50, 0.52, 0.58, 0.61])  # 构造验证损失轨迹。",
            f"patience = {variant}  # 设置连续无改进容忍轮数。",
            "best_loss = np.inf  # 初始化最佳损失。",
            "best_epoch = -1  # 初始化最佳轮次。",
            "wait = 0  # 初始化等待计数。",
            "for epoch, loss in enumerate(validation_loss):  # 逐轮检查验证损失。",
            "    if loss < best_loss:  # 发现严格改进。",
            "        best_loss, best_epoch, wait = loss, epoch, 0  # 保存最佳状态并清零等待。",
            "    else:  # 当前轮没有改进。",
            "        wait += 1  # 累加等待轮数。",
            "        if wait >= patience:  # 达到patience则停止。",
            "            break  # 退出训练循环。",
            "assert best_epoch == 3  # 验证最优模型出现在第3轮零基索引。",
            "print(best_epoch, best_loss, epoch)  # 输出最佳和停止轮次。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "train_sizes = np.array([20, 50, 100, 200])  # 创建训练样本规模。",
            "train_scores = np.array([0.99, 0.95, 0.91, 0.89])  # 训练分数随样本增加可能下降。",
            "validation_scores = np.array([0.60, 0.72, 0.80, 0.85])  # 验证分数随样本增加改善。",
            "gaps = train_scores - validation_scores  # 计算泛化差距。",
            "more_data_helped = validation_scores[-1] > validation_scores[0] and gaps[-1] < gaps[0]  # 判断增加数据是否改善高方差。",
            f"target_gap = {variant * 0.03}  # 设置期望泛化差距。",
            "needs_more_data = gaps[-1] > target_gap  # 根据目标判断是否继续收集数据。",
            "assert more_data_helped  # 验证学习曲线趋势。",
            "print(train_sizes, gaps, needs_more_data)  # 输出学习曲线诊断。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "reference = np.array([0.50, 0.30, 0.15, 0.05])  # 创建训练期分箱比例。",
            "current = np.array([0.35, 0.30, 0.20, 0.15])  # 创建当前期分箱比例。",
            "epsilon = 1e-6  # 防止除零和log零。",
            "psi_parts = (current - reference) * np.log((current + epsilon) / (reference + epsilon))  # 计算各箱PSI贡献。",
            "psi = psi_parts.sum()  # 汇总Population Stability Index。",
            f"drift_detected = psi > {variant * 0.05}  # 使用示例阈值判断漂移。",
            "assert psi >= 0  # PSI理论上非负。",
            "print(psi_parts, psi, drift_detected)  # 输出漂移指标。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "time = np.arange(20)  # 创建按时间排序样本。",
            f"test_size = {variant + 2}  # 设置滚动验证窗口大小。",
            "splits = []  # 保存时间序列切分。",
            "for train_end in range(8, 20 - test_size + 1, test_size):  # 逐步扩展训练窗口。",
            "    train = time[:train_end]  # 训练只能使用过去。",
            "    validation = time[train_end:train_end + test_size]  # 验证使用紧随其后的未来。",
            "    splits.append((train, validation))  # 保存本折。",
            "assert all(train.max() < validation.min() for train, validation in splits)  # 验证没有未来信息泄漏。",
            "print([(len(train), validation.tolist()) for train, validation in splits])  # 输出时间切分。",
        ],
        [
            "import random  # 导入Python随机模块。",
            "import numpy as np  # 导入 NumPy。",
            f"seed = {40 + variant}  # 设置统一随机种子。",
            "random.seed(seed)  # 固定Python随机性。",
            "np_rng = np.random.default_rng(seed)  # 创建局部NumPy Generator。",
            "python_values = [random.random() for _ in range(3)]  # 采样Python随机数。",
            "numpy_values = np_rng.normal(size=3)  # 采样NumPy随机数。",
            "random.seed(seed)  # 重置Python种子验证复现。",
            "assert python_values == [random.random() for _ in range(3)]  # 验证Python随机序列复现。",
            "assert np.allclose(numpy_values, np.random.default_rng(seed).normal(size=3))  # 验证NumPy随机序列复现。",
            "print(seed, python_values, numpy_values)  # 输出可复现样本。",
        ],
    ]
    # 各主题的变式、易错点、综合代码；基础公式会间隔重复，但考察角度不同。
    extras: list[list[list[str]]] = [
        [[], [], []],  # 第001至004题已在函数开头分别完整实现四种不同场景。
        [
            ["robust_data = np.array([1.0, 2.0, 3.0, 100.0]); robust_scaled = (robust_data - np.median(robust_data)) / (np.percentile(robust_data, 75) - np.percentile(robust_data, 25))  # Robust缩放使用中位数和IQR降低离群值影响。", "assert np.median(robust_scaled) == 0  # 验证中心位于中位数。"],
            ["constant_feature = np.ones(4); safe_denominator = np.where(constant_feature.std() == 0, 1.0, constant_feature.std()); safe_standardized = (constant_feature - constant_feature.mean()) / safe_denominator  # 常数列标准差为零，必须防止除零。", "assert np.isfinite(safe_standardized).all() and np.allclose(safe_standardized, 0)  # 验证安全处理。"],
            ["skewed = np.array([0.0, 1.0, 9.0, 99.0]); log_transformed = np.log1p(skewed); standardized_log = (log_transformed - log_transformed.mean()) / log_transformed.std()  # 综合先log1p减小偏态再标准化。", "assert np.isclose(standardized_log.mean(), 0) and np.isclose(standardized_log.std(), 1)  # 验证组合变换。"],
        ],
        [
            ["ridge_design = np.c_[np.ones(5), np.arange(5), np.arange(5)**2]; ridge_target = np.array([1, 2, 5, 10, 17.0]); ridge_penalty = np.diag([0.0, 1.0, 1.0]); ridge_weights = np.linalg.solve(ridge_design.T @ ridge_design + ridge_penalty, ridge_design.T @ ridge_target)  # Ridge正规方程通常不惩罚截距。", "assert ridge_weights.shape == (3,) and np.isfinite(ridge_weights).all()  # 验证正则化解。"],
            ["collinear = np.c_[np.arange(5.0), 2 * np.arange(5.0)]; collinear_rank = np.linalg.matrix_rank(collinear); stable_weights = np.linalg.pinv(collinear) @ np.arange(5.0)  # 完全共线使XTX不可逆，应使用lstsq或伪逆。", "assert collinear_rank == 1 and np.isfinite(stable_weights).all()  # 验证多重共线性陷阱。"],
            ["diagnostic_x = np.arange(1, 8.0); diagnostic_y = 2 * diagnostic_x + np.array([-1, 0, 1, 0, -1, 0, 1]); diagnostic_coef = np.polyfit(diagnostic_x, diagnostic_y, 1); diagnostic_residuals = diagnostic_y - np.polyval(diagnostic_coef, diagnostic_x)  # 综合拟合并检查残差。", "assert abs(diagnostic_residuals.mean()) < 1e-12 and diagnostic_residuals.shape == diagnostic_y.shape  # 含截距OLS残差均值接近零。"],
        ],
        [
            ["momentum_weight = 0.0; velocity = 0.0  # 初始化动量梯度下降。\nfor _ in range(100):  # 迭代优化一维二次函数。\n    gradient = 2 * (momentum_weight - 3); velocity = 0.9 * velocity + gradient; momentum_weight -= 0.05 * velocity  # 累积历史梯度并更新。", "assert abs(momentum_weight - 3) < 0.1  # 验证动量收敛到最优点。"],
            ["large_scale_x = np.array([1000.0, 2000.0]); unstable_weight = 1.0; unstable_gradient = 2 * np.mean((unstable_weight * large_scale_x) * large_scale_x); unstable_weight -= 0.1 * unstable_gradient  # 未缩放特征配大步长会产生巨大更新。", "assert abs(unstable_weight) > 1000  # 验证尺度影响收敛稳定性。"],
            ["adam_value = 0.0; first_moment = second_moment = 0.0  # 初始化Adam的一阶二阶矩。\nfor step in range(1, 101):  # 迭代最小化(value-3)^2。\n    gradient = 2 * (adam_value - 3); first_moment = 0.9 * first_moment + 0.1 * gradient; second_moment = 0.999 * second_moment + 0.001 * gradient**2; corrected_first = first_moment / (1 - 0.9**step); corrected_second = second_moment / (1 - 0.999**step); adam_value -= 0.1 * corrected_first / (np.sqrt(corrected_second) + 1e-8)  # 偏差修正后更新。", "assert abs(adam_value - 3) < 0.1  # 验证Adam综合实现。"],
        ],
        [
            ["multi_logits = np.array([[2.0, 1.0, 0.0], [0.0, 1.0, 2.0]]); shifted_logits = multi_logits - multi_logits.max(axis=1, keepdims=True); softmax = np.exp(shifted_logits) / np.exp(shifted_logits).sum(axis=1, keepdims=True)  # 减去每行最大值稳定计算softmax。", "assert np.allclose(softmax.sum(1), 1) and softmax.argmax(1).tolist() == [0, 2]  # 验证多分类概率。"],
            ["extreme_logits = np.array([-1000.0, 1000.0]); stable_losses = np.maximum(extreme_logits, 0) - extreme_logits * np.array([0.0, 1.0]) + np.log1p(np.exp(-np.abs(extreme_logits)))  # 直接按logits计算BCE避免sigmoid上溢下溢。", "assert np.isfinite(stable_losses).all() and np.allclose(stable_losses, 0)  # 验证数值稳定性。"],
            ["log_prob_feature = np.array([[np.log(0.8), np.log(0.2)], [np.log(0.3), np.log(0.7)]]); log_prior = np.log(np.array([0.5, 0.5])); naive_bayes_scores = log_prob_feature.sum(axis=0) + log_prior; naive_bayes_prediction = naive_bayes_scores.argmax()  # 综合用log概率实现朴素贝叶斯分类思想。", "assert naive_bayes_prediction in (0, 1) and np.isfinite(naive_bayes_scores).all()  # 验证概率模型计算。"],
        ],
        [
            ["quantile_errors = np.array([-2.0, -1.0, 1.0, 3.0]); quantile = 0.8; pinball = np.maximum(quantile * quantile_errors, (quantile - 1) * quantile_errors)  # Pinball损失用于分位数回归且对正负误差不对称。", "assert pinball.tolist() == [0.3999999999999999, 0.19999999999999996, 0.8, 2.4000000000000004]  # 验证高分位更惩罚低估。"],
            ["outlier_errors = np.array([0.0, 1.0, 100.0]); mse_contribution = outlier_errors**2; mae_contribution = np.abs(outlier_errors)  # MSE平方放大离群点，MAE线性增长。", "assert mse_contribution[-1] / mse_contribution[1] > mae_contribution[-1] / mae_contribution[1]  # 验证鲁棒性差异。"],
            ["log_cosh_errors = np.array([-10.0, 0.0, 10.0]); log_cosh = np.logaddexp(log_cosh_errors, -log_cosh_errors) - np.log(2)  # log-cosh在零附近像MSE、大误差时像MAE。", "assert np.isfinite(log_cosh).all() and log_cosh[0] == log_cosh[-1]  # 验证平滑对称损失。"],
        ],
        [
            ["elastic_weights = np.array([-2.0, 0.5, 3.0]); l1_strength, l2_strength = 0.2, 0.3; elastic_penalty = l1_strength * np.abs(elastic_weights).sum() + l2_strength * (elastic_weights**2).sum()  # Elastic Net组合L1稀疏与L2稳定。", "assert elastic_penalty > 0  # 验证组合正则项。"],
            ["scaled_equivalent = np.array([1.0, 1000.0]); same_effect_weights = np.array([1.0, 0.001]); unequal_penalty = np.abs(same_effect_weights)  # 未标准化时同等预测作用的特征受到完全不同L1惩罚。", "assert unequal_penalty[0] / unequal_penalty[1] == 1000  # 验证正则化前必须关注尺度。"],
            ["orthogonal_design = np.eye(3); sparse_target = np.array([3.0, 0.1, -2.0]); threshold = 0.5; lasso_closed_form = np.sign(sparse_target) * np.maximum(np.abs(sparse_target) - threshold, 0)  # 正交设计下Lasso等价于软阈值。", "assert lasso_closed_form.tolist() == [2.5, 0.0, -1.5]  # 综合验证L1产生稀疏系数。"],
        ],
        [
            ["rng_bias = np.random.default_rng(42); population = rng_bias.normal(size=200); bootstrap_means = np.array([rng_bias.choice(population, size=len(population), replace=True).mean() for _ in range(200)])  # Bootstrap重采样估计统计量方差。", "assert bootstrap_means.std() > 0 and abs(bootstrap_means.mean() - population.mean()) < 0.1  # 验证抽样分布。"],
            ["training_errors = np.array([0.5, 0.2, 0.05]); validation_errors = np.array([0.55, 0.3, 0.8]); gaps = validation_errors - training_errors; selected_by_test_wrong = validation_errors.argmin()  # 若数组代表测试误差，用它选复杂度会造成测试集泄漏。", "assert gaps[-1] > gaps[0] and selected_by_test_wrong == 1  # 识别高方差与错误选择动作。"],
            ["ensemble_errors = np.array([[1.0, -1.0, 0.5], [-1.0, 1.0, -0.5], [0.5, -0.5, 0.0]]); individual_variance = ensemble_errors.var(axis=1).mean(); averaged_variance = ensemble_errors.mean(axis=0).var()  # 平均低相关模型可降低方差。", "assert averaged_variance < individual_variance  # 综合解释bagging改善高方差。"],
        ],
        [
            ["labels_cv = np.array([0] * 8 + [1] * 4); class_zero_cv = np.flatnonzero(labels_cv == 0); class_one_cv = np.flatnonzero(labels_cv == 1); stratified_folds = [np.r_[class_zero_cv[index::4], class_one_cv[index::4]] for index in range(4)]  # 手工构造保持类别比例的分层K折。", "assert all(np.isclose(labels_cv[fold].mean(), labels_cv.mean()) for fold in stratified_folds)  # 验证每折比例。"],
            ["groups_cv = np.repeat(np.arange(6), 2); validation_group = 2; validation_indices = np.flatnonzero(groups_cv == validation_group); training_indices = np.flatnonzero(groups_cv != validation_group)  # Group CV保证同一主体不跨训练验证。", "assert not set(groups_cv[training_indices]) & set(groups_cv[validation_indices])  # 验证组间隔离。"],
            ["outer_folds = [np.arange(0, 4), np.arange(4, 8)]; nested_counts = []  # 外层评估泛化，内层选择超参数。\nfor outer_validation in outer_folds:  # 遍历外层验证块。\n    outer_training = np.setdiff1d(np.arange(8), outer_validation); inner_validation = outer_training[::2]; inner_training = np.setdiff1d(outer_training, inner_validation); nested_counts.append((len(inner_training), len(inner_validation), len(outer_validation)))  # 只在外层训练集内部再切分。", "assert nested_counts == [(2, 2, 4), (2, 2, 4)]  # 综合验证nested CV层级。"],
        ],
        [
            ["multi_confusion = np.array([[5, 1, 0], [2, 3, 1], [0, 1, 7]]); per_class_recall = np.diag(multi_confusion) / multi_confusion.sum(axis=1); macro_recall = per_class_recall.mean(); weighted_recall = np.average(per_class_recall, weights=multi_confusion.sum(axis=1))  # 比较macro和按支持度weighted平均。", "assert 0 <= macro_recall <= 1 and 0 <= weighted_recall <= 1  # 验证多分类指标范围。"],
            ["binary_confusion = np.array([[90, 10], [5, 15]]); tn, fp, fn, tp = binary_confusion.ravel(); specificity = tn / (tn + fp); balanced_accuracy = (tp / (tp + fn) + specificity) / 2  # specificity关注负类，balanced accuracy平均两类召回。", "assert np.isclose(specificity, 0.9) and np.isclose(balanced_accuracy, 0.825)  # 验证不平衡指标。"],
            ["multilabel_true = np.array([[1, 1, 0], [0, 1, 0]], dtype=bool); multilabel_pred = np.array([[1, 0, 1], [0, 1, 0]], dtype=bool); micro_tp = (multilabel_true & multilabel_pred).sum(); micro_fp = (~multilabel_true & multilabel_pred).sum(); micro_fn = (multilabel_true & ~multilabel_pred).sum(); micro_f1 = 2 * micro_tp / (2 * micro_tp + micro_fp + micro_fn)  # 综合计算多标签micro-F1。", "assert np.isclose(micro_f1, 2 / 3)  # 验证样本类别展开后的整体指标。"],
        ],
        [
            ["precision_points = np.array([1.0, 0.75, 0.5]); recall_points = np.array([0.0, 0.5, 1.0]); pr_auc = np.trapezoid(precision_points, recall_points)  # PR-AUC在正类稀少时比ROC-AUC更关注正类质量。", "assert 0 <= pr_auc <= 1  # 验证曲线面积范围。"],
            ["tied_scores = np.array([0.8, 0.8, 0.2, 0.1]); tied_labels = np.array([1, 0, 1, 0]); pair_scores = [(tied_scores[p] > tied_scores[n]) + 0.5 * (tied_scores[p] == tied_scores[n]) for p in np.flatnonzero(tied_labels) for n in np.flatnonzero(1 - tied_labels)]; rank_auc = np.mean(pair_scores)  # AUC等于随机正样本得分高于负样本的概率，平分计0.5。", "assert 0 <= rank_auc <= 1  # 验证排序解释。"],
            ["class_aucs = np.array([0.95, 0.7, 0.6]); class_supports = np.array([80, 15, 5]); macro_auc = class_aucs.mean(); weighted_auc = np.average(class_aucs, weights=class_supports)  # 多分类One-vs-Rest可使用macro或weighted汇总。", "assert weighted_auc > macro_auc  # 综合显示多数类表现会主导weighted指标。"],
        ],
        [
            ["majority = np.arange(20); minority = np.arange(20, 24); rng_balance = np.random.default_rng(42); oversampled_minority = rng_balance.choice(minority, size=len(majority), replace=True); balanced_indices = np.r_[majority, oversampled_minority]  # 只在训练集内随机过采样少数类。", "assert len(balanced_indices) == 40 and len(np.unique(oversampled_minority)) <= len(minority)  # 验证有放回过采样。"],
            ["costs = {'fp': 1, 'fn': 10}; candidate_confusions = [np.array([[90, 5], [4, 1]]), np.array([[80, 15], [1, 4]])]; business_costs = [matrix[0, 1] * costs['fp'] + matrix[1, 0] * costs['fn'] for matrix in candidate_confusions]  # 阈值应依据业务成本而非固定0.5。", "assert np.argmin(business_costs) == 1  # 高漏报成本下选择召回更高的方案。"],
            ["class_counts = np.array([90, 10]); balanced_weights = class_counts.sum() / (len(class_counts) * class_counts); sample_labels = np.array([0, 0, 1]); sample_weights = balanced_weights[sample_labels]  # balanced权重与类别频次成反比。", "assert sample_weights[-1] > sample_weights[0] and np.isclose((balanced_weights * class_counts).sum(), class_counts.sum())  # 综合验证加权守恒。"],
        ],
        [
            ["knn_train = np.array([[0.0, 0.0], [1.0, 1000.0]]); knn_query = np.array([0.9, 0.0]); raw_distances = np.linalg.norm(knn_train - knn_query, axis=1); standardized_train = (knn_train - knn_train.mean(0)) / np.where(knn_train.std(0) == 0, 1, knn_train.std(0)); standardized_query = (knn_query - knn_train.mean(0)) / np.where(knn_train.std(0) == 0, 1, knn_train.std(0))  # KNN对尺度敏感，缩放会改变距离贡献。", "assert not np.allclose(raw_distances, np.linalg.norm(standardized_train - standardized_query, axis=1))  # 验证尺度影响。"],
            ["neighbor_distances = np.array([0.1, 0.5, 1.0]); neighbor_labels = np.array([1, 0, 0]); inverse_weights = 1 / np.maximum(neighbor_distances, 1e-12); weighted_vote = np.bincount(neighbor_labels, weights=inverse_weights).argmax()  # 距离加权KNN让近邻贡献更大。", "assert weighted_vote == 1  # 一个很近的正类可超过两个远负类。"],
            ["rng_dimension = np.random.default_rng(0); low_dim = rng_dimension.random((1000, 2)); high_dim = rng_dimension.random((1000, 50)); low_ratio = np.linalg.norm(low_dim, axis=1).min() / np.linalg.norm(low_dim, axis=1).max(); high_ratio = np.linalg.norm(high_dim, axis=1).min() / np.linalg.norm(high_dim, axis=1).max()  # 高维中最近和最远距离趋于相似。", "assert high_ratio > low_ratio  # 综合演示维度灾难。"],
        ],
        [
            ["parent_counts = np.array([6, 4]); left_counts = np.array([4, 1]); right_counts = parent_counts - left_counts; entropy_fn = lambda counts: -(counts[counts > 0] / counts.sum() * np.log2(counts[counts > 0] / counts.sum())).sum(); information_gain = entropy_fn(parent_counts) - (left_counts.sum() * entropy_fn(left_counts) + right_counts.sum() * entropy_fn(right_counts)) / parent_counts.sum()  # 计算entropy信息增益。", "assert information_gain >= 0  # 验证有效切分不增加加权不纯度。"],
            ["deep_train_scores = np.array([0.8, 0.95, 1.0]); deep_valid_scores = np.array([0.78, 0.82, 0.65]); best_depth_index = deep_valid_scores.argmax()  # 不能用训练准确率选择树深，否则总偏向复杂树。", "assert best_depth_index == 1 and deep_train_scores.argmax() != best_depth_index  # 验证预剪枝需看验证集。"],
            ["leaf_probabilities = np.array([0.7, 0.3]); leaf_gini = 1 - np.sum(leaf_probabilities**2); leaf_entropy = -np.sum(leaf_probabilities * np.log2(leaf_probabilities)); leaf_prediction = leaf_probabilities.argmax()  # 综合叶节点概率、不纯度和预测。", "assert leaf_gini < leaf_entropy and leaf_prediction == 0  # 两种指标量纲不同但纯度趋势一致。"],
        ],
        [
            ["rng_bootstrap = np.random.default_rng(1); bootstrap_indices = rng_bootstrap.choice(10, size=10, replace=True); oob_indices = np.setdiff1d(np.arange(10), np.unique(bootstrap_indices))  # Bagging有放回抽样，未抽中样本形成OOB集。", "assert len(np.unique(bootstrap_indices)) <= 10 and not set(bootstrap_indices) & set(oob_indices)  # 验证bootstrap与OOB。"],
            ["boost_labels = np.array([1, 1, -1, -1]); weak_predictions = np.array([1, -1, -1, -1]); sample_weights_boost = np.full(4, 0.25); weighted_error = sample_weights_boost[weak_predictions != boost_labels].sum(); learner_weight = 0.5 * np.log((1 - weighted_error) / weighted_error); updated_weights = sample_weights_boost * np.exp(-learner_weight * boost_labels * weak_predictions); updated_weights /= updated_weights.sum()  # AdaBoost提高错分样本权重。", "assert updated_weights[1] == updated_weights.max()  # 验证错分样本被关注。"],
            ["base_oof = np.array([[0.8, 0.6], [0.2, 0.3], [0.7, 0.9], [0.1, 0.4]]); meta_weights = np.linalg.lstsq(np.c_[np.ones(4), base_oof], np.array([1, 0, 1, 0]), rcond=None)[0]; stacked = np.c_[np.ones(4), base_oof] @ meta_weights  # Stacking元学习器必须训练在out-of-fold预测上。", "assert stacked.shape == (4,) and np.isfinite(stacked).all()  # 综合验证两层模型输入。"],
        ],
        [
            ["svm_scores = np.array([2.0, 0.5, -1.5]); svm_labels = np.array([1.0, 1.0, -1.0]); margins = svm_labels * svm_scores; support_candidates = margins <= 1  # 间隔内或边界上的样本影响hinge loss。", "assert support_candidates.tolist() == [False, True, False]  # 验证支持向量候选。"],
            ["kernel_points = np.array([[1.0, 2.0], [2.0, 1.0]]); linear_kernel = kernel_points @ kernel_points.T; gamma = 0.5; squared_distances = ((kernel_points[:, None] - kernel_points[None, :])**2).sum(-1); rbf_kernel = np.exp(-gamma * squared_distances)  # 核技巧只通过样本相似度隐式映射。", "assert np.allclose(np.diag(rbf_kernel), 1) and linear_kernel.shape == rbf_kernel.shape  # 验证两种Gram矩阵。"],
            ["kernel_matrix = np.array([[1.0, 0.5], [0.5, 1.0]]); kernel_eigenvalues = np.linalg.eigvalsh(kernel_matrix); decision_scores = kernel_matrix @ np.array([1.0, -1.0]) + 0.1  # 合法Mercer核矩阵应半正定。", "assert kernel_eigenvalues.min() >= 0 and decision_scores.shape == (2,)  # 综合核SVM决策形式。"],
        ],
        [
            ["rng_kpp = np.random.default_rng(2); points_kpp = np.array([[0.0], [1.0], [9.0], [10.0]]); first_center = points_kpp[0]; squared_nearest = ((points_kpp - first_center)**2).ravel(); second_center = points_kpp[rng_kpp.choice(len(points_kpp), p=squared_nearest / squared_nearest.sum())]  # KMeans++按到最近中心距离平方选新中心。", "assert second_center.shape == (1,)  # 验证概率初始化。"],
            ["dbscan_points = np.array([[0.0], [0.1], [5.0], [5.1], [20.0]]); dbscan_distances = np.abs(dbscan_points - dbscan_points.T); neighbor_counts = (dbscan_distances <= 0.2).sum(1); core_mask = neighbor_counts >= 2; noise_candidate = ~core_mask  # DBSCAN用eps邻域和min_samples识别密度及噪声。", "assert noise_candidate.tolist() == [False, False, False, False, True]  # 验证离群点。"],
            ["gmm_values = np.array([-2.0, -1.5, 1.5, 2.0]); gmm_means = np.array([-1.0, 1.0]); responsibilities = np.exp(-0.5 * (gmm_values[:, None] - gmm_means[None, :])**2); responsibilities /= responsibilities.sum(1, keepdims=True); updated_means = (responsibilities * gmm_values[:, None]).sum(0) / responsibilities.sum(0)  # 综合演示GMM的E步责任度与M步均值更新。", "assert updated_means[0] < 0 < updated_means[1] and np.allclose(responsibilities.sum(1), 1)  # 验证软聚类。"],
        ],
        [
            ["pca_scaled_data = np.array([[1.0, 100.0], [2.0, 110.0], [3.0, 120.0]]); raw_variance = pca_scaled_data.var(0); scaled_pca_data = (pca_scaled_data - pca_scaled_data.mean(0)) / pca_scaled_data.std(0); scaled_variance = scaled_pca_data.var(0)  # PCA对特征尺度敏感。", "assert raw_variance[1] > raw_variance[0] and np.allclose(scaled_variance, 1)  # 验证标准化必要性。"],
            ["pca_train = np.array([[0.0, 0.0], [1.0, 1.0]]); pca_test = np.array([[100.0, 100.0]]); correct_center = pca_train.mean(0); leaked_center = np.r_[pca_train, pca_test].mean(0)  # 在全数据上中心化会把测试分布泄漏给PCA。", "assert not np.allclose(correct_center, leaked_center)  # 验证无监督预处理同样会泄漏。"],
            ["pca_matrix = np.array([[2.0, 0.0], [0.0, 1.0], [-2.0, 0.0], [0.0, -1.0]]); pca_centered = pca_matrix - pca_matrix.mean(0); _, pca_singular, pca_vt = np.linalg.svd(pca_centered, full_matrices=False); whitened = (pca_centered @ pca_vt.T) / (pca_singular / np.sqrt(len(pca_matrix) - 1))  # 综合SVD投影并whitening。", "assert np.allclose(np.cov(whitened, rowvar=False), np.eye(2))  # 验证白化后单位协方差。"],
        ],
        [
            ["feature_matrix = np.array([[1, 1, 0], [2, 2, 1], [3, 3, 0], [4, 4, 1]], dtype=float); feature_correlation = np.corrcoef(feature_matrix, rowvar=False); redundant_pair = abs(feature_correlation[0, 1]) > 0.95  # 过滤法可先删除高度共线特征。", "assert redundant_pair  # 验证冗余特征识别。"],
            ["selection_train_scores = np.array([0.8, 0.9, 1.0]); selection_validation_scores = np.array([0.78, 0.85, 0.7]); selected_feature_count = np.array([1, 2, 3])[selection_validation_scores.argmax()]  # wrapper方法必须在验证或CV内部选特征数。", "assert selected_feature_count == 2  # 防止按训练分数选择全部特征。"],
            ["baseline_metric = 0.9; shuffled_metrics = np.array([0.89, 0.6, 0.88]); permutation_importance = baseline_metric - shuffled_metrics; ranked_features = np.argsort(permutation_importance)[::-1]  # 排列重要性衡量打乱单列后的性能下降。", "assert ranked_features[0] == 1 and permutation_importance[1] == permutation_importance.max()  # 综合得到模型无关重要性排序。"],
        ],
        [
            ["calibration_probabilities = np.array([0.1, 0.2, 0.8, 0.9]); calibration_labels = np.array([0, 1, 1, 1]); calibration_bins = np.array([0, 0, 1, 1]); bin_gaps = [abs(calibration_probabilities[calibration_bins == index].mean() - calibration_labels[calibration_bins == index].mean()) for index in range(2)]; ece = sum((calibration_bins == index).mean() * bin_gaps[index] for index in range(2))  # ECE按bin加权置信度与准确率差。", "assert 0 <= ece <= 1  # 验证校准误差范围。"],
            ["overconfident = np.array([0.99, 0.99]); uncertain = np.array([0.6, 0.6]); wrong_labels = np.array([1.0, 0.0]); overconfident_brier = np.mean((overconfident - wrong_labels)**2); uncertain_brier = np.mean((uncertain - wrong_labels)**2)  # Brier分数会严惩高置信度错误。", "assert overconfident_brier > uncertain_brier  # 验证概率质量不等于准确率。"],
            ["raw_calibration_scores = np.array([-2.0, -1.0, 1.0, 2.0]); platt_a, platt_b = 1.2, -0.1; platt_probabilities = 1 / (1 + np.exp(-(platt_a * raw_calibration_scores + platt_b)))  # Platt scaling在独立校准集上拟合一维逻辑映射。", "assert np.all(np.diff(platt_probabilities) > 0) and np.all((platt_probabilities > 0) & (platt_probabilities < 1))  # 综合验证单调概率映射。"],
        ],
        [
            ["validation_history = np.array([1.0, 0.8, 0.795, 0.792, 0.791]); min_delta = 0.01; patience_count = 0; best_value = np.inf; stop_epoch = None  # min_delta过滤微小噪声改进。\nfor epoch, value in enumerate(validation_history):  # 逐轮监控。\n    if value < best_value - min_delta: best_value, patience_count = value, 0  # 显著改进时保存。\n    else: patience_count += 1  # 否则累计无改进轮数。\n    if patience_count >= 2: stop_epoch = epoch; break  # 达到patience时停止。", "assert stop_epoch == 3  # 验证min_delta和patience共同作用。"],
            ["training_loss_history = np.array([1.0, 0.7, 0.5, 0.3]); validation_loss_history = np.array([1.1, 0.8, 0.6, 0.9]); wrong_epoch = training_loss_history.argmin(); correct_epoch = validation_loss_history.argmin()  # 早停只能根据验证指标，不能看训练损失。", "assert wrong_epoch == 3 and correct_epoch == 2  # 验证监控对象陷阱。"],
            ["model_states = [{'weight': value} for value in [0.1, 0.2, 0.3, 0.4]]; validation_losses = np.array([0.9, 0.6, 0.5, 0.8]); best_epoch = validation_losses.argmin(); restored_state = dict(model_states[best_epoch])  # 综合保存并恢复最佳epoch而非最后epoch。", "assert restored_state == {'weight': 0.3} and best_epoch != len(model_states) - 1  # 验证最佳模型恢复。"],
        ],
        [
            ["sample_sizes = np.array([20, 50, 100, 200]); train_curve = np.array([0.99, 0.95, 0.9, 0.86]); valid_curve = np.array([0.55, 0.65, 0.75, 0.82]); shrinking_gap = train_curve - valid_curve  # 随数据增加间距缩小说明继续加数据可能有帮助。", "assert shrinking_gap[-1] < shrinking_gap[0]  # 验证高方差学习曲线。"],
            ["underfit_train = np.array([0.55, 0.57, 0.58]); underfit_valid = np.array([0.53, 0.55, 0.56]); small_gap = np.abs(underfit_train[-1] - underfit_valid[-1]); low_both = max(underfit_train[-1], underfit_valid[-1]) < 0.7  # 两条曲线接近但都差表示高偏差。", "assert small_gap < 0.05 and low_both  # 验证不能只看gap。"],
            ["compute_sizes = np.array([10, 20, 40, 80]); fit_times = compute_sizes**2; log_slope = np.polyfit(np.log(compute_sizes), np.log(fit_times), 1)[0]  # 综合用log-log斜率估计算法随样本量的经验复杂度。", "assert np.isclose(log_slope, 2)  # 验证二次扩展趋势。"],
        ],
        [
            ["reference_categories = np.array([0.5, 0.3, 0.2]); current_categories = np.array([0.4, 0.4, 0.2]); total_variation = 0.5 * np.abs(reference_categories - current_categories).sum()  # Total Variation衡量离散分布整体差异。", "assert np.isclose(total_variation, 0.1)  # 验证漂移距离。"],
            ["zero_reference = np.array([0.5, 0.5, 0.0]); nonzero_current = np.array([0.4, 0.4, 0.2]); unsafe_psi = np.isfinite((nonzero_current - zero_reference) * np.log(np.divide(nonzero_current, zero_reference, out=np.full(3, np.inf), where=zero_reference != 0))).all()  # PSI遇到零箱会产生无穷，需平滑。", "assert not unsafe_psi  # 验证零概率陷阱。"],
            ["p_distribution = np.array([0.8, 0.2]); q_distribution = np.array([0.5, 0.5]); midpoint = (p_distribution + q_distribution) / 2; kl = lambda left, right: np.sum(left * np.log(left / right)); js_divergence = 0.5 * kl(p_distribution, midpoint) + 0.5 * kl(q_distribution, midpoint)  # Jensen-Shannon是对称且有界的分布漂移指标。", "assert js_divergence >= 0 and np.isclose(js_divergence, 0.5 * kl(q_distribution, midpoint) + 0.5 * kl(p_distribution, midpoint))  # 综合验证对称性。"],
        ],
        [
            ["ordered_time = np.arange(20); gap = 2; train_time = ordered_time[:10]; validation_time = ordered_time[10 + gap:15]  # gap或embargo避免标签窗口与未来特征相邻泄漏。", "assert train_time.max() + gap < validation_time.min()  # 验证时间间隔。"],
            ["random_split = np.random.default_rng(0).permutation(np.arange(20)); random_train, random_test = random_split[:15], random_split[15:]; chronological_violation = random_train.max() > random_test.min()  # 普通随机切分破坏时间因果顺序。", "assert chronological_violation  # 验证时间序列不能随意shuffle。"],
            ["time_values = np.arange(12); expanding_splits = [(time_values[:end], time_values[end:end + 2]) for end in range(4, 11, 2)]; rolling_splits = [(time_values[max(0, end - 4):end], time_values[end:end + 2]) for end in range(4, 11, 2)]  # 综合比较扩展窗口与固定滚动窗口。", "assert len(expanding_splits[-1][0]) > len(rolling_splits[-1][0]) and all(train.max() < test.min() for train, test in rolling_splits)  # 验证两种回测。"],
        ],
        [
            ["base_seed = 42; child_sequences = np.random.SeedSequence(base_seed).spawn(2); child_values = [np.random.default_rng(sequence).normal(size=3) for sequence in child_sequences]  # 并行任务应派生独立随机流而不是共用全局状态。", "assert not np.array_equal(child_values[0], child_values[1])  # 验证可复现但相互独立。"],
            ["same_seed_predictions = [np.random.default_rng(42).integers(0, 2, size=10) for _ in range(2)]; different_seed_predictions = [np.random.default_rng(seed).integers(0, 2, size=10) for seed in [42, 43]]  # 相同seed复现实验，不同seed用于评估方差。", "assert np.array_equal(*same_seed_predictions) and not np.array_equal(*different_seed_predictions)  # 验证seed语义。"],
            ["experiment_record = {'code_version': 'abc123', 'data_version': 'v2', 'seed': 42, 'features': ['x1', 'x2'], 'metric': 0.91}; required_fields = {'code_version', 'data_version', 'seed', 'features', 'metric'}  # 综合复现还需代码、数据、特征和指标版本，不能只有随机种子。", "assert required_fields <= experiment_record.keys()  # 验证实验追踪元数据。"],
        ],
    ]
    base_code = cases[family]
    if variant == 1:
        code = list(base_code)
    else:
        code = independent_variant(base_code, extras[family][variant - 2])
    return title, task, code
