"""NumPy 与矩阵运算题目定义。"""

from __future__ import annotations


LEVELS = ["基础", "变式", "易错点", "综合"]


def numpy_case(family: int, variant: int) -> tuple[str, str, list[str]]:
    titles = [
        "数组创建dtype与shape",
        "arange与linspace",
        "切片与负索引",
        "布尔索引与花式索引",
        "reshape转置与轴",
        "广播机制",
        "concatenate与split",
        "聚合函数与axis",
        "排序与argpartition",
        "unique集合操作与计数",
        "where与select条件选择",
        "NaN与缺失值计算",
        "随机数Generator与复现",
        "向量点积与矩阵乘法",
        "线性方程组求解",
        "行列式逆矩阵与条件数",
        "特征值与特征向量",
        "SVD奇异值分解",
        "范数与向量距离",
        "outer与einsum",
        "协方差与相关系数",
        "多项式拟合",
        "FFT频域分析",
        "view与copy内存陷阱",
        "向量化与性能思想",
    ]
    title = titles[family]
    task = f"完成“{title}”的{LEVELS[variant - 1]}题，写出关键数组的shape并解释结果。"
    n = variant + 2
    cases: list[list[str]] = [
        [
            "import numpy as np  # 导入 NumPy。",
            f"array = np.array([[1, 2, {n}], [4, 5, 6]], dtype=np.float32)  # 创建二维浮点数组。",
            "converted = array.astype(np.int64)  # 显式转换dtype并产生新数组。",
            "assert array.shape == (2, 3) and array.ndim == 2  # 验证shape和维数。",
            "print(array.dtype, converted.dtype, array.size, array.itemsize)  # 查看类型、元素数和单元素字节数。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            f"integers = np.arange(0, {n * 4}, {n})  # 按步长生成左闭右开整数序列。",
            f"points = np.linspace(0.0, 1.0, num={n + 2}, endpoint=True)  # 按点数生成包含终点的等距序列。",
            "differences = np.diff(points)  # 计算相邻点间隔。",
            "assert np.allclose(differences, differences[0])  # 验证linspace等距。",
            "print(integers, points)  # 输出两种序列。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "matrix = np.arange(1, 17).reshape(4, 4)  # 创建4×4矩阵。",
            "center = matrix[1:3, 1:3]  # 同时切片行和列取得中心块。",
            "reversed_rows = matrix[::-1]  # 使用负步长翻转行顺序。",
            f"every_n = matrix.ravel()[::{variant}]  # 在展平视图上按步长抽样。",
            "assert center.shape == (2, 2)  # 验证二维切片shape。",
            "print(center, '\\n', reversed_rows, '\\n', every_n)  # 输出切片结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "array = np.array([3, 8, 1, 9, 4, 7])  # 创建一维数组。",
            f"selected = array[array >= {n}]  # 使用布尔mask筛选满足阈值的元素。",
            "order = np.array([3, 0, 5])  # 定义花式索引顺序。",
            "reordered = array[order]  # 花式索引总是返回副本。",
            "assert reordered.tolist() == [9, 3, 7]  # 验证按指定位置重排。",
            "print(selected, reordered)  # 输出两种索引结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "array = np.arange(24)  # 创建24个元素。",
            "cube = array.reshape(2, 3, 4)  # 重塑为三维数组。",
            "permuted = cube.transpose(2, 0, 1)  # 把轴顺序由(0,1,2)改为(2,0,1)。",
            "flattened = permuted.reshape(-1)  # 使用-1自动推导展平长度。",
            "assert permuted.shape == (4, 2, 3) and flattened.size == 24  # 验证轴变换只改布局不改元素数。",
            "print(cube.strides, permuted.strides)  # 查看转置前后的内存步幅。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "matrix = np.arange(12).reshape(3, 4)  # 创建shape为(3,4)的矩阵。",
            "column_bias = np.array([10, 20, 30, 40])  # 创建shape为(4,)的列方向偏置。",
            "row_scale = np.array([1, 2, 3]).reshape(3, 1)  # 显式变成shape为(3,1)的行方向缩放。",
            "answer = (matrix + column_bias) * row_scale  # 利用广播完成无循环计算。",
            "assert answer.shape == matrix.shape  # 广播结果保持矩阵shape。",
            "print(answer)  # 输出广播运算结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "left = np.arange(6).reshape(2, 3)  # 创建左侧矩阵。",
            "right = np.arange(6, 12).reshape(2, 3)  # 创建右侧矩阵。",
            "rows = np.concatenate([left, right], axis=0)  # 沿行轴拼接。",
            "columns = np.concatenate([left, right], axis=1)  # 沿列轴拼接。",
            "parts = np.array_split(columns, 3, axis=1)  # 允许不等分地拆成三块。",
            "assert rows.shape == (4, 3) and columns.shape == (2, 6)  # 验证不同轴的shape。",
            "print(rows, '\\n', [part.shape for part in parts])  # 输出拼接与拆分结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "cube = np.arange(24).reshape(2, 3, 4)  # 创建三维数组。",
            "sum_axis0 = cube.sum(axis=0)  # 消去batch轴得到shape(3,4)。",
            "mean_last = cube.mean(axis=-1, keepdims=True)  # 消去最后轴但保留长度1维。",
            "maximum_positions = cube.argmax(axis=2)  # 返回每行最大值的位置。",
            "assert mean_last.shape == (2, 3, 1)  # 验证keepdims便于后续广播。",
            "print(sum_axis0, '\\n', mean_last, '\\n', maximum_positions)  # 输出聚合结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "values = np.array([9, 1, 7, 3, 8, 2])  # 构造无序数组。",
            "sorted_values = np.sort(values)  # 完整排序并返回副本。",
            f"k = {min(variant + 1, 5)}  # 设置需要取得的前k个元素数量。",
            "smallest_indices = np.argpartition(values, k - 1)[:k]  # 线性期望时间取得最小k个位置但内部无序。",
            "smallest = np.sort(values[smallest_indices])  # 只对选中的k个元素排序。",
            "assert np.array_equal(smallest, sorted_values[:k])  # 与完整排序结果核对。",
            "print(sorted_values, smallest_indices, smallest)  # 输出排序与局部分区结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "values = np.array([3, 1, 3, 2, 1, 3])  # 构造含重复元素的数组。",
            "unique, first_indices, counts = np.unique(values, return_index=True, return_counts=True)  # 同时取得唯一值、首次位置和频次。",
            "left = np.array([1, 2, 3])  # 定义第一集合。",
            "right = np.array([3, 4, 5])  # 定义第二集合。",
            "intersection = np.intersect1d(left, right)  # 计算交集。",
            "assert counts.sum() == values.size  # 验证频次总和等于元素数。",
            "print(unique, first_indices, counts, intersection)  # 输出集合统计。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "values = np.array([-3, 0, 2, 8, 12])  # 构造跨多个条件区间的数据。",
            "sign = np.where(values >= 0, 1, -1)  # 二选一条件向量化。",
            "labels = np.select([values < 0, values < 10], ['negative', 'small'], default='large')  # 多条件按顺序选择。",
            "clipped = np.clip(values, 0, 10)  # 把数值限制到闭区间。",
            "assert labels.tolist() == ['negative', 'small', 'small', 'small', 'large']  # 验证条件优先级。",
            "print(sign, labels, clipped)  # 输出条件运算结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "values = np.array([1.0, np.nan, 3.0, np.nan, 5.0])  # 构造含NaN数组。",
            "mask = np.isnan(values)  # 识别NaN而不能用等号比较。",
            "mean = np.nanmean(values)  # 忽略NaN计算均值。",
            "filled = np.nan_to_num(values, nan=mean)  # 使用均值替换NaN。",
            "assert not np.isnan(filled).any()  # 验证填充完成。",
            "print(mask, mean, filled)  # 输出缺失值处理结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            f"rng = np.random.default_rng({40 + variant})  # 使用推荐的Generator并固定种子。",
            "normal = rng.normal(loc=0.0, scale=1.0, size=(2, 3))  # 从正态分布采样。",
            "integers = rng.integers(0, 10, size=5)  # 从离散均匀分布采样。",
            "choice = rng.choice(['A', 'B', 'C'], size=4, replace=True, p=[0.2, 0.3, 0.5])  # 按概率采样类别。",
            f"repeat = np.random.default_rng({40 + variant}).normal(size=(2, 3))  # 用相同种子复现第一组采样。",
            "assert np.allclose(normal, repeat)  # 验证可复现性。",
            "print(normal, integers, choice)  # 输出随机样本。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "vector_a = np.array([1.0, 2.0, 3.0])  # 创建第一个向量。",
            "vector_b = np.array([4.0, 5.0, 6.0])  # 创建第二个向量。",
            "dot = vector_a @ vector_b  # 一维@一维得到标量点积。",
            "matrix = np.arange(6).reshape(2, 3)  # 创建2×3矩阵。",
            "product = matrix @ vector_a  # 矩阵乘向量得到长度2结果。",
            "batch = np.matmul(np.ones((4, 2, 3)), np.ones((4, 3, 5)))  # 批量矩阵乘法。",
            "assert dot == 32 and batch.shape == (4, 2, 5)  # 验证点积值和批量shape。",
            "print(dot, product, batch.shape)  # 输出矩阵运算结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "coefficients = np.array([[3.0, 1.0], [1.0, 2.0]])  # 定义线性方程系数矩阵A。",
            f"targets = np.array([{9 + variant}.0, {8 + variant}.0])  # 定义右侧向量b。",
            "solution = np.linalg.solve(coefficients, targets)  # 直接求解Ax=b比显式求逆更稳定。",
            "reconstructed = coefficients @ solution  # 把解代回原方程。",
            "assert np.allclose(reconstructed, targets)  # 验证数值解。",
            "print(solution, reconstructed)  # 输出解和代回结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "matrix = np.array([[4.0, 2.0], [1.0, 3.0]])  # 创建可逆方阵。",
            "determinant = np.linalg.det(matrix)  # 计算行列式判断是否奇异。",
            "inverse = np.linalg.inv(matrix)  # 计算逆矩阵用于教学展示。",
            "identity = matrix @ inverse  # 原矩阵乘逆矩阵应得到单位阵。",
            "condition = np.linalg.cond(matrix)  # 条件数衡量数值敏感性。",
            "assert determinant != 0 and np.allclose(identity, np.eye(2))  # 验证可逆性。",
            "print(determinant, inverse, condition)  # 输出线性代数指标。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "matrix = np.array([[2.0, 1.0], [1.0, 2.0]])  # 创建实对称矩阵。",
            "eigenvalues, eigenvectors = np.linalg.eigh(matrix)  # 对称矩阵优先使用eigh。",
            "left = matrix @ eigenvectors[:, 0]  # 计算Av。",
            "right = eigenvalues[0] * eigenvectors[:, 0]  # 计算λv。",
            "assert np.allclose(left, right)  # 验证特征方程Av=λv。",
            "print(eigenvalues, '\\n', eigenvectors)  # 输出特征值和正交特征向量。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "matrix = np.array([[3.0, 1.0], [1.0, 3.0], [1.0, 1.0]])  # 创建非方阵。",
            "u, singular_values, vt = np.linalg.svd(matrix, full_matrices=False)  # 计算紧凑SVD。",
            "reconstructed = u @ np.diag(singular_values) @ vt  # 用UΣVᵀ重建矩阵。",
            f"rank_k = u[:, :1] @ np.diag(singular_values[:1]) @ vt[:1]  # 构造rank-{variant if variant == 1 else 1}低秩近似。",
            "assert np.allclose(reconstructed, matrix)  # 验证完整SVD可重建。",
            "print(singular_values, '\\n', rank_k)  # 输出奇异值和低秩近似。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "a = np.array([1.0, 2.0, 3.0])  # 创建向量a。",
            "b = np.array([4.0, 2.0, 0.0])  # 创建向量b。",
            "l1 = np.linalg.norm(a - b, ord=1)  # 计算曼哈顿距离。",
            "l2 = np.linalg.norm(a - b, ord=2)  # 计算欧氏距离。",
            "cosine = (a @ b) / (np.linalg.norm(a) * np.linalg.norm(b))  # 计算余弦相似度。",
            "assert -1 <= cosine <= 1  # 验证余弦范围。",
            "print(l1, l2, cosine)  # 输出三种相似性指标。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "a = np.array([1, 2, 3])  # 创建列因子向量。",
            "b = np.array([4, 5])  # 创建行因子向量。",
            "outer = np.outer(a, b)  # 计算所有两两乘积。",
            "einsum_outer = np.einsum('i,j->ij', a, b)  # 用爱因斯坦求和表达外积。",
            "matrix = np.arange(6).reshape(2, 3)  # 创建矩阵。",
            "column_sums = np.einsum('ij->j', matrix)  # 用einsum沿行轴求和。",
            "assert np.array_equal(outer, einsum_outer)  # 验证两种外积写法一致。",
            "print(outer, column_sums)  # 输出einsum结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "samples = np.array([[1.0, 2.0], [2.0, 4.0], [3.0, 5.0], [4.0, 8.0]])  # 每行一个样本每列一个特征。",
            "covariance = np.cov(samples, rowvar=False, ddof=1)  # 计算样本协方差矩阵。",
            "correlation = np.corrcoef(samples, rowvar=False)  # 计算标准化相关系数。",
            "centered = samples - samples.mean(axis=0, keepdims=True)  # 对特征中心化。",
            "manual_covariance = centered.T @ centered / (len(samples) - 1)  # 手算样本协方差。",
            "assert np.allclose(covariance, manual_covariance)  # 验证公式实现。",
            "print(covariance, '\\n', correlation)  # 输出协方差和相关矩阵。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "x = np.linspace(-2, 2, 9)  # 创建自变量采样点。",
            "y = 2 * x**2 - 3 * x + 1  # 根据二次函数生成无噪声目标。",
            "coefficients = np.polyfit(x, y, deg=2)  # 最小二乘拟合二次多项式。",
            "predictions = np.polyval(coefficients, x)  # 用拟合系数计算预测。",
            "assert np.allclose(predictions, y)  # 无噪声且阶数正确时应精确拟合。",
            "print(coefficients, np.mean((predictions - y) ** 2))  # 输出系数和MSE。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "sample_count = 128  # 设置采样点数。",
            "time = np.arange(sample_count) / sample_count  # 构造一秒内的均匀时间点。",
            f"frequency = {variant + 2}  # 设置正弦信号频率。",
            "signal = np.sin(2 * np.pi * frequency * time)  # 生成单频正弦信号。",
            "spectrum = np.fft.rfft(signal)  # 对实信号计算单边FFT。",
            "frequencies = np.fft.rfftfreq(sample_count, d=1 / sample_count)  # 计算每个频点对应频率。",
            "dominant = frequencies[np.abs(spectrum).argmax()]  # 找到幅度最大的主频。",
            "assert dominant == frequency  # 验证FFT识别出真实频率。",
            "print(dominant)  # 输出主频。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "original = np.arange(6)  # 创建原始数组。",
            "view = original[1:4]  # 基本切片通常返回共享内存的视图。",
            "copy = original[[1, 2, 3]]  # 花式索引返回独立副本。",
            "view[0] = 99  # 修改视图会影响原数组。",
            "copy[1] = 88  # 修改副本不会影响原数组。",
            "assert original[1] == 99 and original[2] != 88  # 验证view与copy差异。",
            "print(original, view, copy, np.shares_memory(original, view))  # 输出内存共享信息。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "values = np.arange(1, 1001, dtype=float)  # 创建待计算数据。",
            "vectorized = values**2 + 2 * values + 1  # 使用ufunc向量化完成逐元素公式。",
            "loop_result = np.array([value**2 + 2 * value + 1 for value in values])  # 用Python循环表达相同逻辑用于对照。",
            f"matrix = np.arange({n * n}).reshape({n}, {n})  # 创建随变式变化的方阵。",
            "row_norms = np.sqrt((matrix.astype(float) ** 2).sum(axis=1))  # 无显式循环计算每行L2范数。",
            "assert np.array_equal(vectorized, loop_result)  # 验证向量化不改变结果。",
            "print(vectorized[:3], row_norms)  # 输出部分结果。",
        ],
    ]
    # 每个知识点的三种进阶代码：变式、易错点、综合。
    # 基础代码会反复出现以帮助记忆，下面的可执行代码保证考法和API真正不同。
    extras: list[list[list[str]]] = [
        [
            ["from_list = np.asarray([1, 2, 3])  # 使用asarray接收已有序列，输入已是数组时通常避免复制。", "assert from_list.dtype.kind in 'iu'  # 验证整数序列推导为整数dtype。"],
            ["truncated = np.array([1.9, -2.9]).astype(np.int64)  # 浮点转整数会向零截断而不是四舍五入。", "assert truncated.tolist() == [1, -2]  # 验证常见dtype转换陷阱。"],
            ["constructed = np.stack([np.zeros(3), np.ones(3), np.full(3, 2)])  # 综合使用zeros、ones、full和stack构造矩阵。", "assert constructed.shape == (3, 3) and np.eye(3).trace() == 3  # 同时复习eye单位矩阵。"],
        ],
        [
            ["range_short = np.arange(100); range_full = np.arange(0, 100); range_keywords = np.arange(start=0, stop=100, step=1)  # arange三种等价常用写法。", "assert np.array_equal(range_short, range_full) and np.array_equal(range_full, range_keywords)  # 验证三种参数形式结果一致。"],
            ["float_steps = np.arange(0.0, 1.0, 0.1); fixed_points = np.linspace(0.0, 1.0, 11)  # 浮点步长用arange可能累积误差，固定点数优先linspace。", "assert len(float_steps) == 10 and len(fixed_points) == 11 and fixed_points[-1] == 1  # 比较左闭右开与包含终点。"],
            ["grid_x, grid_y = np.meshgrid(np.arange(3), np.linspace(0, 1, 2), indexing='xy')  # 综合使用arange、linspace和meshgrid生成二维坐标。", "assert grid_x.shape == grid_y.shape == (2, 3)  # 验证网格shape。"],
        ],
        [
            ["expanded = matrix[..., np.newaxis]  # 使用省略号和newaxis在末尾增加维度。", "assert expanded.shape == matrix.shape + (1,)  # 验证新增长度为1的轴。"],
            ["slice_view = matrix[:, :2]; slice_view[0, 0] = -1  # 基本切片是视图，修改它会影响原数组。", "assert matrix[0, 0] == -1 and np.shares_memory(matrix, slice_view)  # 验证共享内存陷阱。"],
            ["picked = np.take(matrix, [0, -1], axis=0); clipped = matrix.clip(min=0)  # 综合使用take按轴选择并用clip限制范围。", "assert picked.shape[0] == 2 and clipped.min() >= 0  # 验证选择和裁剪结果。"],
        ],
        [
            ["taken = np.take(array, order); nonzero_positions = np.flatnonzero(np.isin(array, selected))  # 使用take、isin和flatnonzero表达花式选择。", "assert np.array_equal(taken, reordered) and np.array_equal(array[nonzero_positions], selected)  # 验证两套写法等价。"],
            ["repeated = np.zeros(3, dtype=int); repeated[[0, 0]] += 1  # 重复花式索引的原地累加只写回一次，是高频陷阱。", "assert repeated[0] == 1  # 如需累计重复位置应使用np.add.at。"],
            ["rows_ix, cols_ix = np.ix_([0, 2], [1, 3]); cross = np.arange(12).reshape(3, 4)[rows_ix, cols_ix]  # 使用ix_取得行列笛卡尔积。", "assert cross.shape == (2, 2)  # 区分成对花式索引和网格索引。"],
        ],
        [
            ["moved = np.moveaxis(cube, 0, -1); swapped = np.swapaxes(cube, 0, 1)  # 使用moveaxis和swapaxes改变轴顺序。", "assert moved.shape == (3, 4, 2) and swapped.shape == (3, 2, 4)  # 验证轴操作。"],
            ["non_contiguous = cube.transpose(2, 1, 0); safe_shape = np.ascontiguousarray(non_contiguous).reshape(4, -1)  # 转置后先连续化可避免布局误解。", "assert safe_shape.flags.c_contiguous  # 验证结果采用C连续布局。"],
            ["flat_view = cube.ravel(); flat_copy = cube.flatten(); flat_view[0] = -1  # ravel尽量返回视图，flatten总是复制。", "assert cube.ravel()[0] == -1 and flat_copy[0] != -1  # 综合比较reshape、ravel和flatten。"],
        ],
        [
            ["broadcasted = np.broadcast_to(np.arange(4), (3, 4))  # broadcast_to创建只读广播视图而不复制数据。", "assert broadcasted.shape == (3, 4) and not broadcasted.flags.writeable  # 验证shape与只读属性。"],
            ["try:  # 主动运行一个不兼容的广播操作。\n    np.ones((2, 3)) + np.ones((2, 2))  # 尝试广播不兼容的尾部维度。\nexcept ValueError as error:  # 捕获预期的广播异常。\n    broadcast_error = str(error)  # 保存shape不兼容错误。", "assert 'broadcast' in broadcast_error.lower()  # 验证错误来自广播规则。"],
            ["batch = np.arange(24).reshape(2, 3, 4); weights = np.arange(4); weighted = np.einsum('bij,j->bi', batch, weights)  # 用einsum完成批量加权求和。", "assert weighted.shape == (2, 3)  # 验证综合广播运算shape。"],
        ],
        [
            ["stacked = np.stack([left, right], axis=0); vertical = np.vstack([left, right]); horizontal = np.hstack([left, right])  # 比较新增轴stack与已有轴拼接。", "assert stacked.shape == (2, 2, 3) and vertical.shape == rows.shape and horizontal.shape == columns.shape  # 验证三种拼接。"],
            ["uneven = np.array_split(np.arange(10), 3)  # array_split允许不能整除，split则会抛错。", "assert [len(part) for part in uneven] == [4, 3, 3]  # 验证不等长拆分规则。"],
            ["blocked = np.block([[left, right], [right, left]])  # 使用block按二维布局组合小矩阵。", "assert blocked.shape == (4, 6)  # 验证分块矩阵shape。"],
        ],
        [
            ["column_mean = cube.mean(axis=(0, 1), keepdims=True)  # 同时沿多个轴聚合并保留维度。", "assert column_mean.shape == (1, 1, 4)  # 验证多轴与keepdims。"],
            ["small = np.array([250, 10], dtype=np.uint8); overflowed = small.sum(dtype=np.uint8)  # 指定过小累加dtype会发生整数溢出。", "assert overflowed == 4 and small.sum(dtype=np.int64) == 260  # 对比错误与安全累加dtype。"],
            ["accumulated = np.add.accumulate(np.arange(1, 6)); reduced = np.multiply.reduce(np.arange(1, 6))  # 综合使用ufunc的accumulate和reduce。", "assert accumulated[-1] == 15 and reduced == 120  # 验证累计和连乘。"],
        ],
        [
            ["records = np.array([(2, 'b'), (1, 'c'), (1, 'a')], dtype=[('score', int), ('name', 'U1')]); ordered_records = np.sort(records, order=['score', 'name'])  # 对结构化数组多键排序。", "assert ordered_records['name'].tolist() == ['a', 'c', 'b']  # 验证多字段排序。"],
            ["stable_order = np.argsort(np.array([2, 1, 2, 1]), kind='stable')  # stable排序保持相等元素原始先后。", "assert stable_order.tolist() == [1, 3, 0, 2]  # 验证稳定性。"],
            ["median_position = len(values) // 2; partitioned = np.partition(values, median_position)  # 只确定第k位置时无需完整排序。", "assert partitioned[median_position] == np.sort(values)[median_position]  # 验证partition关键位置。"],
        ],
        [
            ["unique_values, first_indices, inverse, counts = np.unique(values, return_index=True, return_inverse=True, return_counts=True)  # 一次取得唯一值、首次位置、逆映射和计数。", "assert np.array_equal(unique_values[inverse], values) and counts.sum() == values.size  # 用逆映射重建原数组。"],
            ["union = np.union1d([1, 2, 3], [3, 4]); difference = np.setdiff1d([1, 2, 3], [2])  # 使用集合运算并注意结果会排序。", "assert union.tolist() == [1, 2, 3, 4] and difference.tolist() == [1, 3]  # 验证集合结果。"],
            ["nonnegative = np.array([0, 1, 1, 3]); frequencies = np.bincount(nonnegative, minlength=5)  # 非负小整数计数优先bincount。", "assert frequencies.tolist() == [1, 2, 0, 1, 0]  # 验证计数与补零。"],
        ],
        [
            ["masked_copy = values.copy(); np.putmask(masked_copy, masked_copy < 0, -1)  # putmask原地修改满足条件的位置。", "assert np.all(masked_copy[values >= 0] >= 0)  # 验证掩码写入。"],
            ["with np.errstate(divide='ignore', invalid='ignore'):  # 临时管理可预期的浮点告警。\n    eager = np.where(values != 0, 1 / values, 0)  # where会先计算两个分支，不能阻止除零计算。", "assert np.isfinite(eager).all()  # 使用errstate管理已知浮点告警。"],
            ["choices = np.choose(np.array([0, 1, 2]), [np.full(3, 10), np.full(3, 20), np.full(3, 30)])  # choose按整数选择器从多组候选取值。", "assert choices.tolist() == [10, 20, 30]  # 验证多分支选择。"],
        ],
        [
            ["median = np.nanmedian(values); percentile = np.nanpercentile(values, [25, 75])  # 忽略NaN计算中位数和分位数。", "assert np.isfinite(median) and percentile.shape == (2,)  # 验证NaN安全统计。"],
            ["masked = np.ma.masked_invalid(values); masked_mean = masked.mean()  # MaskedArray可同时记录缺失mask和数据。", "assert np.isfinite(masked_mean)  # 验证屏蔽无效值后的均值。"],
            ["cleaned = np.nan_to_num(values, nan=0.0, posinf=1e6, neginf=-1e6)  # 显式指定NaN和正负无穷替换值。", "assert np.isfinite(cleaned).all()  # 验证清洗后均为有限值。"],
        ],
        [
            ["permuted = rng.permutation(100); shuffled = np.arange(100); rng.shuffle(shuffled); chosen = rng.choice(100, size=100, replace=False)  # permutation、arange加shuffle、choice无放回均得到不重复索引。", "assert len(np.unique(permuted)) == len(np.unique(shuffled)) == len(np.unique(chosen)) == 100  # 验证三种随机排列写法。"],
            ["sampled_with_replacement = rng.integers(0, 100, size=100)  # integers默认允许重复，不能直接替代permutation。", "assert sampled_with_replacement.shape == (100,) and np.unique(sampled_with_replacement).size <= 100  # 检查随机整数采样性质。"],
            ["seed_sequence = np.random.SeedSequence(42); child_a, child_b = [np.random.default_rng(seed) for seed in seed_sequence.spawn(2)]  # 用SeedSequence为并行任务创建独立随机流。", "assert not np.array_equal(child_a.normal(size=5), child_b.normal(size=5))  # 验证子随机流不同。"],
        ],
        [
            ["via_operator = matrix @ vector_a; via_dot = np.dot(matrix, vector_a); via_matmul = np.matmul(matrix, vector_a)  # 比较@、dot和matmul的二维行为。", "assert np.allclose(via_operator, via_dot) and np.allclose(via_dot, via_matmul)  # 验证三种写法等价。"],
            ["batched_left = np.ones((2, 3, 4)); batched_right = np.ones((2, 4, 5)); batched_product = np.matmul(batched_left, batched_right)  # matmul支持批量矩阵乘法。", "assert batched_product.shape == (2, 3, 5)  # 验证批量维广播。"],
            ["contracted = np.tensordot(np.arange(24).reshape(2, 3, 4), np.ones((4, 5)), axes=([2], [0]))  # tensordot显式指定收缩轴。", "assert contracted.shape == (2, 3, 5)  # 验证张量收缩shape。"],
        ],
        [
            ["least_squares, residuals, rank, singular = np.linalg.lstsq(coefficients, targets, rcond=None)  # 非方阵或含噪问题使用最小二乘。", "assert rank <= min(coefficients.shape) and singular.ndim == 1  # 检查秩和奇异值。"],
            ["rank_value = np.linalg.matrix_rank(coefficients); pseudo_solution = np.linalg.pinv(coefficients) @ targets  # 奇异系统不能盲目使用solve，可考虑伪逆。", "assert rank_value >= 1 and pseudo_solution.shape[0] == coefficients.shape[1]  # 验证伪逆解shape。"],
            ["multiple_rhs = np.column_stack([targets, targets * 2]); multiple_solutions = np.linalg.solve(coefficients, multiple_rhs)  # solve可一次处理多个右侧向量。", "assert np.allclose(coefficients @ multiple_solutions, multiple_rhs)  # 验证批量线性方程解。"],
        ],
        [
            ["sign, log_abs_det = np.linalg.slogdet(matrix)  # slogdet在行列式极大或极小时更稳定。", "assert np.isclose(sign * np.exp(log_abs_det), np.linalg.det(matrix))  # 验证与det关系。"],
            ["identity_via_solve = np.linalg.solve(matrix, np.eye(matrix.shape[0]))  # 求解Ax=I可得到逆，但实际预测应直接solve。", "assert np.allclose(identity_via_solve, np.linalg.inv(matrix))  # 验证两种结果。"],
            ["regularized = matrix.T @ matrix + 1e-6 * np.eye(matrix.shape[1]); stable_inverse = np.linalg.pinv(regularized)  # 综合使用正则化和伪逆处理病态矩阵。", "assert np.isfinite(stable_inverse).all()  # 验证数值结果有限。"],
        ],
        [
            ["general_values, general_vectors = np.linalg.eig(matrix)  # 一般方阵使用eig，实对称矩阵优先eigh。", "assert np.allclose(matrix @ general_vectors, general_vectors * general_values)  # 验证Av等于lambda乘v。"],
            ["symmetric = (matrix + matrix.T) / 2; symmetric_values, symmetric_vectors = np.linalg.eigh(symmetric)  # eigh利用对称结构并返回有序实特征值。", "assert np.allclose(symmetric, symmetric_vectors @ np.diag(symmetric_values) @ symmetric_vectors.T)  # 重建对称矩阵。"],
            ["power_vector = np.ones(matrix.shape[0]); power_vector = matrix @ power_vector; power_vector /= np.linalg.norm(power_vector)  # 用一次幂迭代逼近主特征向量方向。", "assert np.isclose(np.linalg.norm(power_vector), 1)  # 验证归一化。"],
        ],
        [
            ["compact_u, compact_s, compact_vt = np.linalg.svd(matrix, full_matrices=False)  # 经济型SVD减少无用维度。", "assert compact_u.shape[1] == compact_s.size == compact_vt.shape[0]  # 验证紧凑SVD shape。"],
            ["singular_only = np.linalg.svd(matrix, compute_uv=False)  # 只需要奇异值时不计算左右奇异向量。", "assert np.allclose(singular_only, singular_values)  # 验证两种调用得到相同奇异值。"],
            ["energy_ratio = np.cumsum(singular_values**2) / np.sum(singular_values**2); rank_for_90 = np.searchsorted(energy_ratio, 0.9) + 1  # 按累计能量选择低秩维数。", "assert 1 <= rank_for_90 <= singular_values.size  # 验证自动选择的秩范围。"],
        ],
        [
            ["norm_matrix = np.stack([a, b]); row_norms_extra = np.linalg.norm(norm_matrix, axis=1, keepdims=True); normalized_rows = norm_matrix / np.maximum(row_norms_extra, 1e-12)  # 沿行计算范数并防止除零。", "assert np.allclose(np.linalg.norm(normalized_rows, axis=1), 1)  # 验证行归一化。"],
            ["norm_matrix = np.stack([a, b]); pairwise = np.linalg.norm(norm_matrix[:, None, :] - norm_matrix[None, :, :], axis=-1)  # 利用广播计算两两欧氏距离。", "assert pairwise.shape == (len(norm_matrix), len(norm_matrix)) and np.allclose(np.diag(pairwise), 0)  # 验证距离矩阵。"],
            ["norm_matrix = np.stack([a, b]); cosine_matrix = norm_matrix @ norm_matrix.T / np.maximum(np.linalg.norm(norm_matrix, axis=1)[:, None] * np.linalg.norm(norm_matrix, axis=1)[None, :], 1e-12)  # 综合计算余弦相似度。", "assert np.allclose(np.diag(cosine_matrix), 1)  # 非零向量与自身余弦相似度为1。"],
        ],
        [
            ["outer_ufunc = np.multiply.outer(a, b)  # ufunc.outer是np.outer的通用写法。", "assert np.array_equal(outer_ufunc, np.outer(a, b))  # 验证两种外积等价。"],
            ["kronecker = np.kron(np.eye(2), np.ones((2, 2)))  # kron计算Kronecker积，不能和普通外积混淆。", "assert kronecker.shape == (4, 4)  # 验证Kronecker积shape。"],
            ["batch_outer = np.einsum('bi,bj->bij', np.ones((3, 2)), np.arange(12).reshape(3, 4))  # einsum计算每个batch的外积。", "assert batch_outer.shape == (3, 2, 4)  # 验证批量外积。"],
        ],
        [
            ["samples_by_row = np.cov(samples, rowvar=False, ddof=1)  # 样本在行、特征在列时必须设置rowvar=False。", "assert samples_by_row.shape == (samples.shape[1], samples.shape[1])  # 验证特征协方差矩阵shape。"],
            ["population_covariance = np.cov(samples, rowvar=False, ddof=0)  # ddof=0计算总体协方差，默认ddof=1是样本协方差。", "assert not np.allclose(population_covariance, covariance)  # 小样本下两种分母结果不同。"],
            ["standardized_matrix = (samples - samples.mean(0)) / samples.std(0, ddof=1); correlation_from_cov = np.cov(standardized_matrix, rowvar=False)  # 标准化后的协方差等于相关矩阵。", "assert np.allclose(correlation_from_cov, np.corrcoef(samples, rowvar=False))  # 验证协方差与相关系数关系。"],
        ],
        [
            ["polynomial = np.polynomial.Polynomial.fit(x, y, deg=2).convert()  # 新式Polynomial API可管理定义域并转换为普通系数。", "assert np.allclose(polynomial(x), predictions)  # 验证与polyfit预测一致。"],
            ["roots = np.roots(coefficients); evaluated = np.polyval(coefficients, roots)  # 多项式根代回后理论上接近零。", "assert np.allclose(evaluated, 0, atol=1e-6)  # 验证根的数值误差范围。"],
            ["vandermonde = np.vander(x, N=3); manual_coefficients = np.linalg.lstsq(vandermonde, y, rcond=None)[0]  # 综合用Vandermonde设计矩阵理解多项式拟合。", "assert np.allclose(vandermonde @ manual_coefficients, predictions)  # 验证底层最小二乘形式。"],
        ],
        [
            ["restored = np.fft.irfft(spectrum, n=sample_count)  # 使用irfft从单边频谱恢复实信号。", "assert np.allclose(restored, signal)  # 验证FFT往返变换。"],
            ["shifted_frequency = np.fft.fftshift(np.fft.fftfreq(8)); shifted_spectrum = np.fft.fftshift(np.fft.fft(np.arange(8)))  # fftshift把零频移动到中心。", "assert shifted_frequency.shape == shifted_spectrum.shape == (8,)  # 验证双边频谱shape。"],
            ["window = np.hanning(sample_count); windowed_spectrum = np.fft.rfft(signal * window)  # 综合使用窗函数减轻非整周期频谱泄漏。", "assert windowed_spectrum.shape == spectrum.shape  # 验证加窗不改变频点数量。"],
        ],
        [
            ["c_copy = np.array(original, copy=True, order='C'); f_copy = np.array(original.reshape(2, 3), copy=True, order='F')  # 显式控制复制和C/F内存顺序。", "assert c_copy.flags.c_contiguous and f_copy.flags.f_contiguous  # 验证内存布局。"],
            ["possible_share = np.may_share_memory(original, original[::2]); definite_share = np.shares_memory(original, original[::2])  # may_share_memory更快但可能保守判断。", "assert possible_share and definite_share  # 本例两个函数都识别出共享。"],
            ["transposed = original.reshape(2, 3).T; contiguous = np.ascontiguousarray(transposed)  # 综合把非连续转置结果变为C连续副本。", "assert contiguous.flags.c_contiguous and not np.shares_memory(contiguous, original)  # 验证连续化产生独立存储。"],
        ],
        [
            ["output = np.empty_like(values); np.add(values**2, 2 * values + 1, out=output)  # 使用ufunc的out参数复用输出内存。", "assert np.array_equal(output, vectorized)  # 验证out写法结果一致。"],
            ["python_wrapper = np.vectorize(lambda value: value**2 + 2 * value + 1); wrapped = python_wrapper(values)  # vectorize只是便利循环，并不会自动获得真正ufunc性能。", "assert np.array_equal(wrapped, vectorized)  # 验证语义相同但性能含义不同。"],
            ["positive_only = np.zeros_like(values); np.square(values, out=positive_only, where=values > 0)  # 综合使用ufunc的out和where条件写入。", "assert np.array_equal(positive_only, values**2)  # 本例所有值为正，因此等于完整平方。"],
        ],
    ]
    code = list(cases[family])
    if variant > 1:
        code.extend(extras[family][variant - 2])
    return title, task, code
