"""NumPy 与矩阵运算题目定义。"""

from __future__ import annotations


LEVELS = ["基础", "变式", "易错点", "综合"]


def numpy_case(family: int, variant: int) -> tuple[str, str, list[str]]:
    titles = [
        "数组创建dtype与shape",
        "arange与linspace",
        "切片与负索引",
        "布尔索引与花式索引",
        "reshape转置与轴",
        "广播机制",
        "concatenate与split",
        "聚合函数与axis",
        "排序与argpartition",
        "unique集合操作与计数",
        "where与select条件选择",
        "NaN与缺失值计算",
        "随机数Generator与复现",
        "向量点积与矩阵乘法",
        "线性方程组求解",
        "行列式逆矩阵与条件数",
        "特征值与特征向量",
        "SVD奇异值分解",
        "范数与向量距离",
        "outer与einsum",
        "协方差与相关系数",
        "多项式拟合",
        "FFT频域分析",
        "view与copy内存陷阱",
        "向量化与性能思想",
    ]
    title = titles[family]
    task = f"完成“{title}”的{LEVELS[variant - 1]}题，写出关键数组的shape并解释结果。"
    n = variant + 2
    cases: list[list[str]] = [
        [
            "import numpy as np  # 导入 NumPy。",
            f"array = np.array([[1, 2, {n}], [4, 5, 6]], dtype=np.float32)  # 创建二维浮点数组。",
            "converted = array.astype(np.int64)  # 显式转换dtype并产生新数组。",
            "assert array.shape == (2, 3) and array.ndim == 2  # 验证shape和维数。",
            "print(array.dtype, converted.dtype, array.size, array.itemsize)  # 查看类型、元素数和单元素字节数。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            f"integers = np.arange(0, {n * 4}, {n})  # 按步长生成左闭右开整数序列。",
            f"points = np.linspace(0.0, 1.0, num={n + 2}, endpoint=True)  # 按点数生成包含终点的等距序列。",
            "differences = np.diff(points)  # 计算相邻点间隔。",
            "assert np.allclose(differences, differences[0])  # 验证linspace等距。",
            "print(integers, points)  # 输出两种序列。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "matrix = np.arange(1, 17).reshape(4, 4)  # 创建4×4矩阵。",
            "center = matrix[1:3, 1:3]  # 同时切片行和列取得中心块。",
            "reversed_rows = matrix[::-1]  # 使用负步长翻转行顺序。",
            f"every_n = matrix.ravel()[::{variant}]  # 在展平视图上按步长抽样。",
            "assert center.shape == (2, 2)  # 验证二维切片shape。",
            "print(center, '\\n', reversed_rows, '\\n', every_n)  # 输出切片结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "array = np.array([3, 8, 1, 9, 4, 7])  # 创建一维数组。",
            f"selected = array[array >= {n}]  # 使用布尔mask筛选满足阈值的元素。",
            "order = np.array([3, 0, 5])  # 定义花式索引顺序。",
            "reordered = array[order]  # 花式索引总是返回副本。",
            "assert reordered.tolist() == [9, 3, 7]  # 验证按指定位置重排。",
            "print(selected, reordered)  # 输出两种索引结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "array = np.arange(24)  # 创建24个元素。",
            "cube = array.reshape(2, 3, 4)  # 重塑为三维数组。",
            "permuted = cube.transpose(2, 0, 1)  # 把轴顺序由(0,1,2)改为(2,0,1)。",
            "flattened = permuted.reshape(-1)  # 使用-1自动推导展平长度。",
            "assert permuted.shape == (4, 2, 3) and flattened.size == 24  # 验证轴变换只改布局不改元素数。",
            "print(cube.strides, permuted.strides)  # 查看转置前后的内存步幅。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "matrix = np.arange(12).reshape(3, 4)  # 创建shape为(3,4)的矩阵。",
            "column_bias = np.array([10, 20, 30, 40])  # 创建shape为(4,)的列方向偏置。",
            "row_scale = np.array([1, 2, 3]).reshape(3, 1)  # 显式变成shape为(3,1)的行方向缩放。",
            "answer = (matrix + column_bias) * row_scale  # 利用广播完成无循环计算。",
            "assert answer.shape == matrix.shape  # 广播结果保持矩阵shape。",
            "print(answer)  # 输出广播运算结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "left = np.arange(6).reshape(2, 3)  # 创建左侧矩阵。",
            "right = np.arange(6, 12).reshape(2, 3)  # 创建右侧矩阵。",
            "rows = np.concatenate([left, right], axis=0)  # 沿行轴拼接。",
            "columns = np.concatenate([left, right], axis=1)  # 沿列轴拼接。",
            "parts = np.array_split(columns, 3, axis=1)  # 允许不等分地拆成三块。",
            "assert rows.shape == (4, 3) and columns.shape == (2, 6)  # 验证不同轴的shape。",
            "print(rows, '\\n', [part.shape for part in parts])  # 输出拼接与拆分结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "cube = np.arange(24).reshape(2, 3, 4)  # 创建三维数组。",
            "sum_axis0 = cube.sum(axis=0)  # 消去batch轴得到shape(3,4)。",
            "mean_last = cube.mean(axis=-1, keepdims=True)  # 消去最后轴但保留长度1维。",
            "maximum_positions = cube.argmax(axis=2)  # 返回每行最大值的位置。",
            "assert mean_last.shape == (2, 3, 1)  # 验证keepdims便于后续广播。",
            "print(sum_axis0, '\\n', mean_last, '\\n', maximum_positions)  # 输出聚合结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "values = np.array([9, 1, 7, 3, 8, 2])  # 构造无序数组。",
            "sorted_values = np.sort(values)  # 完整排序并返回副本。",
            f"k = {min(variant + 1, 5)}  # 设置需要取得的前k个元素数量。",
            "smallest_indices = np.argpartition(values, k - 1)[:k]  # 线性期望时间取得最小k个位置但内部无序。",
            "smallest = np.sort(values[smallest_indices])  # 只对选中的k个元素排序。",
            "assert np.array_equal(smallest, sorted_values[:k])  # 与完整排序结果核对。",
            "print(sorted_values, smallest_indices, smallest)  # 输出排序与局部分区结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "values = np.array([3, 1, 3, 2, 1, 3])  # 构造含重复元素的数组。",
            "unique, first_indices, counts = np.unique(values, return_index=True, return_counts=True)  # 同时取得唯一值、首次位置和频次。",
            "left = np.array([1, 2, 3])  # 定义第一集合。",
            "right = np.array([3, 4, 5])  # 定义第二集合。",
            "intersection = np.intersect1d(left, right)  # 计算交集。",
            "assert counts.sum() == values.size  # 验证频次总和等于元素数。",
            "print(unique, first_indices, counts, intersection)  # 输出集合统计。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "values = np.array([-3, 0, 2, 8, 12])  # 构造跨多个条件区间的数据。",
            "sign = np.where(values >= 0, 1, -1)  # 二选一条件向量化。",
            "labels = np.select([values < 0, values < 10], ['negative', 'small'], default='large')  # 多条件按顺序选择。",
            "clipped = np.clip(values, 0, 10)  # 把数值限制到闭区间。",
            "assert labels.tolist() == ['negative', 'small', 'small', 'small', 'large']  # 验证条件优先级。",
            "print(sign, labels, clipped)  # 输出条件运算结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "values = np.array([1.0, np.nan, 3.0, np.nan, 5.0])  # 构造含NaN数组。",
            "mask = np.isnan(values)  # 识别NaN而不能用等号比较。",
            "mean = np.nanmean(values)  # 忽略NaN计算均值。",
            "filled = np.nan_to_num(values, nan=mean)  # 使用均值替换NaN。",
            "assert not np.isnan(filled).any()  # 验证填充完成。",
            "print(mask, mean, filled)  # 输出缺失值处理结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            f"rng = np.random.default_rng({40 + variant})  # 使用推荐的Generator并固定种子。",
            "normal = rng.normal(loc=0.0, scale=1.0, size=(2, 3))  # 从正态分布采样。",
            "integers = rng.integers(0, 10, size=5)  # 从离散均匀分布采样。",
            "choice = rng.choice(['A', 'B', 'C'], size=4, replace=True, p=[0.2, 0.3, 0.5])  # 按概率采样类别。",
            f"repeat = np.random.default_rng({40 + variant}).normal(size=(2, 3))  # 用相同种子复现第一组采样。",
            "assert np.allclose(normal, repeat)  # 验证可复现性。",
            "print(normal, integers, choice)  # 输出随机样本。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "vector_a = np.array([1.0, 2.0, 3.0])  # 创建第一个向量。",
            "vector_b = np.array([4.0, 5.0, 6.0])  # 创建第二个向量。",
            "dot = vector_a @ vector_b  # 一维@一维得到标量点积。",
            "matrix = np.arange(6).reshape(2, 3)  # 创建2×3矩阵。",
            "product = matrix @ vector_a  # 矩阵乘向量得到长度2结果。",
            "batch = np.matmul(np.ones((4, 2, 3)), np.ones((4, 3, 5)))  # 批量矩阵乘法。",
            "assert dot == 32 and batch.shape == (4, 2, 5)  # 验证点积值和批量shape。",
            "print(dot, product, batch.shape)  # 输出矩阵运算结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "coefficients = np.array([[3.0, 1.0], [1.0, 2.0]])  # 定义线性方程系数矩阵A。",
            f"targets = np.array([{9 + variant}.0, {8 + variant}.0])  # 定义右侧向量b。",
            "solution = np.linalg.solve(coefficients, targets)  # 直接求解Ax=b比显式求逆更稳定。",
            "reconstructed = coefficients @ solution  # 把解代回原方程。",
            "assert np.allclose(reconstructed, targets)  # 验证数值解。",
            "print(solution, reconstructed)  # 输出解和代回结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "matrix = np.array([[4.0, 2.0], [1.0, 3.0]])  # 创建可逆方阵。",
            "determinant = np.linalg.det(matrix)  # 计算行列式判断是否奇异。",
            "inverse = np.linalg.inv(matrix)  # 计算逆矩阵用于教学展示。",
            "identity = matrix @ inverse  # 原矩阵乘逆矩阵应得到单位阵。",
            "condition = np.linalg.cond(matrix)  # 条件数衡量数值敏感性。",
            "assert determinant != 0 and np.allclose(identity, np.eye(2))  # 验证可逆性。",
            "print(determinant, inverse, condition)  # 输出线性代数指标。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "matrix = np.array([[2.0, 1.0], [1.0, 2.0]])  # 创建实对称矩阵。",
            "eigenvalues, eigenvectors = np.linalg.eigh(matrix)  # 对称矩阵优先使用eigh。",
            "left = matrix @ eigenvectors[:, 0]  # 计算Av。",
            "right = eigenvalues[0] * eigenvectors[:, 0]  # 计算λv。",
            "assert np.allclose(left, right)  # 验证特征方程Av=λv。",
            "print(eigenvalues, '\\n', eigenvectors)  # 输出特征值和正交特征向量。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "matrix = np.array([[3.0, 1.0], [1.0, 3.0], [1.0, 1.0]])  # 创建非方阵。",
            "u, singular_values, vt = np.linalg.svd(matrix, full_matrices=False)  # 计算紧凑SVD。",
            "reconstructed = u @ np.diag(singular_values) @ vt  # 用UΣVᵀ重建矩阵。",
            f"rank_k = u[:, :1] @ np.diag(singular_values[:1]) @ vt[:1]  # 构造rank-{variant if variant == 1 else 1}低秩近似。",
            "assert np.allclose(reconstructed, matrix)  # 验证完整SVD可重建。",
            "print(singular_values, '\\n', rank_k)  # 输出奇异值和低秩近似。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "a = np.array([1.0, 2.0, 3.0])  # 创建向量a。",
            "b = np.array([4.0, 2.0, 0.0])  # 创建向量b。",
            "l1 = np.linalg.norm(a - b, ord=1)  # 计算曼哈顿距离。",
            "l2 = np.linalg.norm(a - b, ord=2)  # 计算欧氏距离。",
            "cosine = (a @ b) / (np.linalg.norm(a) * np.linalg.norm(b))  # 计算余弦相似度。",
            "assert -1 <= cosine <= 1  # 验证余弦范围。",
            "print(l1, l2, cosine)  # 输出三种相似性指标。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "a = np.array([1, 2, 3])  # 创建列因子向量。",
            "b = np.array([4, 5])  # 创建行因子向量。",
            "outer = np.outer(a, b)  # 计算所有两两乘积。",
            "einsum_outer = np.einsum('i,j->ij', a, b)  # 用爱因斯坦求和表达外积。",
            "matrix = np.arange(6).reshape(2, 3)  # 创建矩阵。",
            "column_sums = np.einsum('ij->j', matrix)  # 用einsum沿行轴求和。",
            "assert np.array_equal(outer, einsum_outer)  # 验证两种外积写法一致。",
            "print(outer, column_sums)  # 输出einsum结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "samples = np.array([[1.0, 2.0], [2.0, 4.0], [3.0, 5.0], [4.0, 8.0]])  # 每行一个样本每列一个特征。",
            "covariance = np.cov(samples, rowvar=False, ddof=1)  # 计算样本协方差矩阵。",
            "correlation = np.corrcoef(samples, rowvar=False)  # 计算标准化相关系数。",
            "centered = samples - samples.mean(axis=0, keepdims=True)  # 对特征中心化。",
            "manual_covariance = centered.T @ centered / (len(samples) - 1)  # 手算样本协方差。",
            "assert np.allclose(covariance, manual_covariance)  # 验证公式实现。",
            "print(covariance, '\\n', correlation)  # 输出协方差和相关矩阵。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "x = np.linspace(-2, 2, 9)  # 创建自变量采样点。",
            "y = 2 * x**2 - 3 * x + 1  # 根据二次函数生成无噪声目标。",
            "coefficients = np.polyfit(x, y, deg=2)  # 最小二乘拟合二次多项式。",
            "predictions = np.polyval(coefficients, x)  # 用拟合系数计算预测。",
            "assert np.allclose(predictions, y)  # 无噪声且阶数正确时应精确拟合。",
            "print(coefficients, np.mean((predictions - y) ** 2))  # 输出系数和MSE。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "sample_count = 128  # 设置采样点数。",
            "time = np.arange(sample_count) / sample_count  # 构造一秒内的均匀时间点。",
            f"frequency = {variant + 2}  # 设置正弦信号频率。",
            "signal = np.sin(2 * np.pi * frequency * time)  # 生成单频正弦信号。",
            "spectrum = np.fft.rfft(signal)  # 对实信号计算单边FFT。",
            "frequencies = np.fft.rfftfreq(sample_count, d=1 / sample_count)  # 计算每个频点对应频率。",
            "dominant = frequencies[np.abs(spectrum).argmax()]  # 找到幅度最大的主频。",
            "assert dominant == frequency  # 验证FFT识别出真实频率。",
            "print(dominant)  # 输出主频。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "original = np.arange(6)  # 创建原始数组。",
            "view = original[1:4]  # 基本切片通常返回共享内存的视图。",
            "copy = original[[1, 2, 3]]  # 花式索引返回独立副本。",
            "view[0] = 99  # 修改视图会影响原数组。",
            "copy[1] = 88  # 修改副本不会影响原数组。",
            "assert original[1] == 99 and original[2] != 88  # 验证view与copy差异。",
            "print(original, view, copy, np.shares_memory(original, view))  # 输出内存共享信息。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "values = np.arange(1, 1001, dtype=float)  # 创建待计算数据。",
            "vectorized = values**2 + 2 * values + 1  # 使用ufunc向量化完成逐元素公式。",
            "loop_result = np.array([value**2 + 2 * value + 1 for value in values])  # 用Python循环表达相同逻辑用于对照。",
            f"matrix = np.arange({n * n}).reshape({n}, {n})  # 创建随变式变化的方阵。",
            "row_norms = np.sqrt((matrix.astype(float) ** 2).sum(axis=1))  # 无显式循环计算每行L2范数。",
            "assert np.array_equal(vectorized, loop_result)  # 验证向量化不改变结果。",
            "print(vectorized[:3], row_norms)  # 输出部分结果。",
        ],
    ]
    return title, task, cases[family]
