"""Python 高频面试题定义。"""

from __future__ import annotations


LEVELS = ["基础", "变式", "易错点", "综合"]


def python_case(family: int, variant: int) -> tuple[str, str, list[str]]:
    titles = [
        "可变对象与不可变对象",
        "列表切片与步长",
        "字典集合与哈希",
        "列表字典集合推导式",
        "sorted的key与稳定排序",
        "函数参数args与kwargs",
        "作用域闭包与late-binding",
        "装饰器与functools.wraps",
        "生成器与yield",
        "迭代器协议",
        "上下文管理器",
        "异常处理与自定义异常",
        "dataclass数据类",
        "继承super与多态",
        "property与封装",
        "常用魔术方法",
        "浅拷贝与深拷贝",
        "字符串格式化与正则",
        "Path文件CSV与JSON",
        "collections高频工具",
        "itertools组合迭代",
        "functools缓存偏函数与reduce",
        "heapq与bisect",
        "类型注解与Protocol",
        "复杂度与常见陷阱",
    ]
    title = titles[family]
    task = f"完成“{title}”的{LEVELS[variant - 1]}题，并说明时间复杂度、对象身份或协议行为。"
    n = variant + 2
    cases: list[list[str]] = [
        [
            "immutable = (1, 2, 3)  # tuple是不可变对象。",
            "mutable = [1, 2, 3]  # list是可变对象。",
            "same_list = mutable  # 赋值只复制引用而不复制对象。",
            f"mutable.append({n})  # 原地修改列表。",
            "new_tuple = immutable + (4,)  # 拼接tuple会创建新对象。",
            "assert same_list is mutable and new_tuple is not immutable  # 验证身份语义。",
            "print(mutable, immutable, new_tuple, id(mutable))  # 输出对象和值。",
        ],
        [
            "values = list(range(10))  # 创建0到9的列表。",
            "middle = values[2:8:2]  # 使用起点终点步长切片。",
            "reversed_values = values[::-1]  # 使用负步长反转列表。",
            f"rotated = values[{variant}:] + values[:{variant}]  # 使用切片循环左移。",
            "copy = values[:]  # 全切片创建浅拷贝。",
            "assert copy == values and copy is not values  # 验证值相等但对象不同。",
            "print(middle, reversed_values, rotated)  # 输出切片结果。",
        ],
        [
            "records = [('a', 1), ('b', 2), ('a', 3)]  # 创建重复键记录。",
            "latest = dict(records)  # 字典后写入的重复键覆盖旧值。",
            "unique_keys = set(latest)  # set和dict键都要求可哈希。",
            "counts = {}  # 初始化频次字典。",
            "for key, _ in records:  # 遍历每条记录。",
            "    counts[key] = counts.get(key, 0) + 1  # 使用get安全累加。",
            "assert latest['a'] == 3 and counts['a'] == 2  # 验证覆盖和频次差异。",
            "print(latest, unique_keys, counts)  # 输出哈希容器结果。",
        ],
        [
            "values = range(1, 8)  # 创建惰性整数序列。",
            "squares = [value**2 for value in values if value % 2 == 0]  # 列表推导筛选偶数平方。",
            "mapping = {value: value**2 for value in values}  # 字典推导创建映射。",
            "remainders = {value % 3 for value in values}  # 集合推导自动去重。",
            "matrix = [[row + column for column in range(3)] for row in range(2)]  # 嵌套推导创建二维列表。",
            "assert squares == [4, 16, 36] and remainders == {0, 1, 2}  # 验证推导结果。",
            "print(squares, mapping, remainders, matrix)  # 输出各种推导式。",
        ],
        [
            "records = [{'name': 'B', 'score': 90}, {'name': 'A', 'score': 90}, {'name': 'C', 'score': 80}]  # 构造待排序记录。",
            "answer = sorted(records, key=lambda row: (-row['score'], row['name']))  # 用tuple key实现分数降序姓名升序。",
            "original = [('first', 1), ('second', 1), ('third', 2)]  # 构造能展示稳定性的序列。",
            "stable = sorted(original, key=lambda item: item[1])  # 相同key保持原相对顺序。",
            f"kth = sorted([5, 1, 9, 3, 7])[-{variant}]  # 取得第variant大元素用于小数据。",
            "assert stable[:2] == [('first', 1), ('second', 1)]  # 验证Timsort稳定性。",
            "print(answer, stable, kth)  # 输出排序结果。",
        ],
        [
            "def describe(required, default=10, *args, keyword_only=True, **kwargs):  # 定义各种参数类型。",
            "    return required, default, args, keyword_only, kwargs  # 返回绑定结果便于观察。",
            f"result = describe('x', {n}, 1, 2, keyword_only=False, extra='value')  # 混合位置和关键字传参。",
            "first, second, *rest = [10, 20, 30, 40]  # 扩展解包收集剩余元素。",
            "merged = {**{'a': 1}, **{'b': 2}}  # 双星号解包合并映射。",
            "assert result[2] == (1, 2) and rest == [30, 40]  # 验证参数收集和解包。",
            "print(result, first, second, rest, merged)  # 输出参数绑定结果。",
        ],
        [
            "def make_multiplier(factor):  # 外层函数创建闭包环境。",
            "    def multiply(value):  # 内层函数引用外层变量。",
            "        return value * factor  # factor被闭包保存。",
            "    return multiply  # 返回函数对象。",
            f"times_n = make_multiplier({n})  # 创建具体倍数闭包。",
            "bad = [lambda: index for index in range(3)]  # late-binding导致调用时都读取最终index。",
            "fixed = [lambda index=index: index for index in range(3)]  # 默认参数在定义时绑定当前值。",
            "assert [fn() for fn in bad] == [2, 2, 2] and [fn() for fn in fixed] == [0, 1, 2]  # 验证闭包陷阱。",
            "print(times_n(5), [fn() for fn in fixed])  # 输出闭包结果。",
        ],
        [
            "from functools import wraps  # 导入保留函数元数据的装饰器。",
            "def count_calls(function):  # 定义带状态的装饰器。",
            "    calls = 0  # 状态保存在闭包中。",
            "    @wraps(function)  # 保留原函数名称和文档。",
            "    def wrapper(*args, **kwargs):  # 接收任意原函数参数。",
            "        nonlocal calls  # 声明修改外层局部变量。",
            "        calls += 1  # 累加调用次数。",
            "        return calls, function(*args, **kwargs)  # 返回次数和原结果。",
            "    return wrapper  # 返回包装函数。",
            "@count_calls  # 应用装饰器。",
            "def add(a, b):  # 定义被装饰函数。",
            "    return a + b  # 返回加法结果。",
            f"result = add({n}, 4)  # 调用包装后的函数。",
            "assert add.__name__ == 'add' and result[0] == 1  # 验证元数据和状态。",
            "print(result)  # 输出装饰器结果。",
        ],
        [
            "def fibonacci(limit):  # 定义生成器函数。",
            "    first, second = 0, 1  # 初始化前两项。",
            "    while first < limit:  # 惰性生成直到上限。",
            "        yield first  # 暂停并产出当前值。",
            "        first, second = second, first + second  # 更新状态。",
            f"generator = fibonacci({n * 5})  # 创建生成器但尚未执行函数体。",
            "first_value = next(generator)  # 手动消费第一个值。",
            f"remaining = list(generator)  # 消费剩余值用于变式{variant}。",
            f"assert first_value == 0 and all(value < {n * 5} for value in remaining)  # 验证边界。",
            "print(first_value, remaining)  # 输出生成序列。",
        ],
        [
            "class Countdown:  # 定义可迭代且自身为迭代器的类。",
            "    def __init__(self, start):  # 保存起始状态。",
            "        self.current = start  # 初始化当前值。",
            "    def __iter__(self):  # 迭代器必须返回自身。",
            "        return self  # 返回实现__next__的对象。",
            "    def __next__(self):  # 定义每次next行为。",
            "        if self.current <= 0:  # 判断结束条件。",
            "            raise StopIteration  # 用协议异常结束迭代。",
            "        value = self.current  # 保存待返回值。",
            "        self.current -= 1  # 推进内部状态。",
            "        return value  # 返回本轮值。",
            f"values = list(Countdown({n}))  # 消费自定义迭代器。",
            f"assert values[0] == {n} and values[-1] == 1  # 验证倒计时。",
            "print(values)  # 输出迭代结果。",
        ],
        [
            "from contextlib import contextmanager  # 导入生成器式上下文管理器。",
            "@contextmanager  # 把生成器函数转换为上下文管理器。",
            "def managed_resource(events):  # 定义资源生命周期。",
            "    events.append('open')  # __enter__阶段获取资源。",
            "    try:  # 确保退出逻辑总会执行。",
            "        yield 'resource'  # 把资源交给with代码块。",
            "    finally:  # 正常或异常退出都会进入finally。",
            "        events.append('close')  # 释放资源。",
            "events = []  # 记录生命周期。",
            "with managed_resource(events) as resource:  # 使用上下文管理器。",
            "    events.append(resource)  # 在with内部使用资源。",
            "assert events == ['open', 'resource', 'close']  # 验证进入使用退出顺序。",
            "print(events)  # 输出生命周期。",
        ],
        [
            "class ValidationError(ValueError):  # 定义语义明确的业务异常。",
            "    pass  # 继承父类行为即可。",
            "def positive(value):  # 定义输入校验函数。",
            "    if value <= 0:  # 检查非法条件。",
            "        raise ValidationError('value must be positive')  # 抛出自定义异常。",
            "    return value  # 合法时返回。",
            "try:  # 捕获预期业务异常。",
            f"    positive(-{n})  # 传入非法值触发异常。",
            "except ValidationError as error:  # 只捕获具体异常而不是裸except。",
            "    message = str(error)  # 保存错误信息。",
            "else:  # 未发生异常才执行。",
            "    message = 'ok'  # 设置成功信息。",
            "finally:  # 无论如何都执行清理逻辑。",
            "    cleaned = True  # 模拟资源清理。",
            "assert message and cleaned  # 验证异常路径和finally。",
            "print(type(message).__name__, message)  # 输出异常处理结果。",
        ],
        [
            "from dataclasses import dataclass, field  # 导入数据类工具。",
            "@dataclass(order=True, frozen=True)  # 自动生成比较、repr并设为不可变。",
            "class Student:  # 定义值对象。",
            "    score: int  # 排序首先使用分数。",
            "    name: str = field(compare=False)  # 姓名不参与排序比较。",
            f"students = [Student(80, 'A'), Student({80 + n}, 'B')]  # 创建数据类实例。",
            "best = max(students)  # 使用自动生成的顺序方法。",
            "mapping = {student: student.name for student in students}  # frozen数据类可哈希可作字典键。",
            "assert best.name == 'B' and len(mapping) == 2  # 验证排序和哈希。",
            "print(students, best)  # 输出数据类。",
        ],
        [
            "class Animal:  # 定义父类。",
            "    def __init__(self, name):  # 初始化公共属性。",
            "        self.name = name  # 保存名称。",
            "    def speak(self):  # 定义可覆盖的方法。",
            "        return 'unknown'  # 返回默认行为。",
            "class Dog(Animal):  # 通过继承扩展父类。",
            "    def __init__(self, name, breed):  # 增加子类参数。",
            "        super().__init__(name)  # 使用super调用父类初始化。",
            "        self.breed = breed  # 保存子类属性。",
            "    def speak(self):  # 覆盖方法实现多态。",
            "        return f'{self.name}: woof'  # 返回Dog行为。",
            "animals = [Animal('A'), Dog('B', 'Lab')]  # 用统一父类接口保存不同对象。",
            "sounds = [animal.speak() for animal in animals]  # 动态分派调用实际类型方法。",
            "assert sounds == ['unknown', 'B: woof']  # 验证多态。",
            "print(sounds)  # 输出方法结果。",
        ],
        [
            "class Temperature:  # 定义封装温度的类。",
            "    def __init__(self, celsius):  # 初始化时走属性校验。",
            "        self.celsius = celsius  # 调用property setter。",
            "    @property  # 把方法暴露为只读式属性接口。",
            "    def celsius(self):  # 定义getter。",
            "        return self._celsius  # 返回内部存储。",
            "    @celsius.setter  # 定义同名属性setter。",
            "    def celsius(self, value):  # 接收待设置值。",
            "        if value < -273.15:  # 检查绝对零度。",
            "            raise ValueError('below absolute zero')  # 拒绝非法状态。",
            "        self._celsius = float(value)  # 规范化并保存。",
            "    @property  # 定义派生只读属性。",
            "    def fahrenheit(self):  # 计算华氏温度。",
            "        return self.celsius * 9 / 5 + 32  # 返回转换结果。",
            f"temperature = Temperature({n * 10})  # 创建合法实例。",
            "assert temperature.fahrenheit > temperature.celsius  # 验证派生属性。",
            "print(temperature.celsius, temperature.fahrenheit)  # 输出两种温标。",
        ],
        [
            "class Vector:  # 定义支持运算符的二维向量。",
            "    def __init__(self, x, y):  # 初始化坐标。",
            "        self.x, self.y = x, y  # 同时赋值两个属性。",
            "    def __repr__(self):  # 定义开发者友好表示。",
            "        return f'Vector({self.x}, {self.y})'  # 返回可读字符串。",
            "    def __len__(self):  # 定义len协议。",
            "        return 2  # 二维向量长度固定为2个分量。",
            "    def __add__(self, other):  # 定义加号行为。",
            "        return Vector(self.x + other.x, self.y + other.y)  # 返回新向量。",
            "    def __eq__(self, other):  # 定义值相等语义。",
            "        return isinstance(other, Vector) and (self.x, self.y) == (other.x, other.y)  # 比较类型和坐标。",
            f"answer = Vector(1, 2) + Vector({n}, 4)  # 使用重载运算符。",
            f"assert len(answer) == 2 and answer == Vector({1 + n}, 6)  # 验证协议实现。",
            "print(answer)  # 调用__repr__输出。",
        ],
        [
            "import copy  # 导入复制工具。",
            "original = {'items': [[1, 2], [3, 4]]}  # 创建嵌套可变对象。",
            "shallow = copy.copy(original)  # 浅拷贝只复制最外层容器。",
            "deep = copy.deepcopy(original)  # 深拷贝递归复制内部对象。",
            "shallow['items'][0].append(99)  # 修改共享的内部列表会影响original。",
            "deep['items'][1].append(88)  # 修改深拷贝内部列表不会影响original。",
            "assert 99 in original['items'][0] and 88 not in original['items'][1]  # 验证复制深度。",
            "print(original, shallow, deep)  # 输出三份对象。",
        ],
        [
            "import re  # 导入正则表达式模块。",
            "text = 'User Alice email alice@example.com score 95'  # 构造待解析文本。",
            "match = re.search(r'(?P<name>[A-Z][a-z]+).*?(?P<email>[\\w.]+@[\\w.]+).*?(?P<score>\\d+)', text)  # 使用命名组提取字段。",
            "if match is None:  # 处理匹配失败情况。",
            "    raise ValueError('pattern did not match')  # 明确抛出解析错误。",
            "fields = match.groupdict()  # 把命名组转换为字典。",
            f"message = '{{:<10}} | {{:0{variant + 2}d}}'.format(fields['name'], int(fields['score']))  # 使用格式说明符对齐和补零。",
            "assert fields['email'] == 'alice@example.com'  # 验证正则提取。",
            "print(fields, message)  # 输出解析和格式化结果。",
        ],
        [
            "import csv  # 导入标准库CSV工具。",
            "import json  # 导入JSON工具。",
            "import tempfile  # 导入临时目录工具。",
            "from pathlib import Path  # 导入路径工具。",
            "records = [{'name': 'A', 'score': 90}, {'name': 'B', 'score': 85}]  # 准备结构化记录。",
            "with tempfile.TemporaryDirectory() as folder:  # 创建自动清理目录。",
            "    csv_path = Path(folder) / 'scores.csv'  # 定义CSV路径。",
            "    json_path = Path(folder) / 'scores.json'  # 定义JSON路径。",
            "    with csv_path.open('w', newline='', encoding='utf-8') as file:  # 安全打开CSV写入。",
            "        writer = csv.DictWriter(file, fieldnames=['name', 'score'])  # 创建字典写入器。",
            "        writer.writeheader()  # 写入表头。",
            "        writer.writerows(records)  # 写入全部记录。",
            "    json_path.write_text(json.dumps(records), encoding='utf-8')  # 序列化JSON文本。",
            "    restored = json.loads(json_path.read_text(encoding='utf-8'))  # 读取并反序列化JSON。",
            "assert restored == records  # 验证JSON往返不丢数据。",
            "print(restored)  # 输出恢复记录。",
        ],
        [
            "from collections import Counter, defaultdict, deque  # 导入高频容器。",
            "words = 'to be or not to be'.split()  # 创建词序列。",
            "counts = Counter(words)  # 一行统计频次。",
            "groups = defaultdict(list)  # 缺失键自动创建空列表。",
            "for word in words:  # 按首字母分组。",
            "    groups[word[0]].append(word)  # 直接追加无需先判断键。",
            f"queue = deque(maxlen={n})  # 创建固定长度双端队列。",
            "queue.extend(words)  # 超过maxlen自动从左侧淘汰。",
            "assert counts.most_common(1)[0] == ('to', 2)  # 验证最高频词。",
            "print(counts, dict(groups), list(queue))  # 输出容器结果。",
        ],
        [
            "from itertools import chain, combinations, groupby, islice  # 导入组合迭代工具。",
            "values = [1, 1, 2, 2, 3]  # 创建已按分组键排序的序列。",
            "groups = {key: list(group) for key, group in groupby(values)}  # groupby只合并相邻相同键。",
            "pairs = list(combinations([1, 2, 3, 4], 2))  # 生成不重复二元组合。",
            "flattened = list(chain.from_iterable([[1, 2], [3], [4, 5]]))  # 惰性连接多个序列。",
            f"prefix = list(islice(range(100), {n}))  # 从惰性迭代器取前n项。",
            "assert len(pairs) == 6 and flattened == [1, 2, 3, 4, 5]  # 验证组合数和展平。",
            "print(groups, pairs, prefix)  # 输出itertools结果。",
        ],
        [
            "from functools import cache, partial, reduce  # 导入函数式工具。",
            "@cache  # 缓存纯函数的输入输出。",
            "def fibonacci(number):  # 定义递归斐波那契。",
            "    return number if number < 2 else fibonacci(number - 1) + fibonacci(number - 2)  # 使用缓存避免指数级重复计算。",
            "power_of_two = partial(pow, 2)  # 固定pow的第一个参数创建新函数。",
            "product = reduce(lambda left, right: left * right, range(1, 6), 1)  # 归约计算连乘。",
            f"value = fibonacci({n + 5})  # 计算随变式变化的斐波那契数。",
            "assert power_of_two(5) == 32 and product == 120  # 验证partial和reduce。",
            "print(value, fibonacci.cache_info(), product)  # 输出缓存命中信息。",
        ],
        [
            "import bisect  # 导入二分维护有序序列工具。",
            "import heapq  # 导入最小堆工具。",
            "values = [1, 3, 5, 7]  # 创建有序列表。",
            f"bisect.insort(values, {n})  # 用二分定位并插入以保持有序。",
            "heap = [8, 3, 6, 1, 9]  # 创建普通列表。",
            "heapq.heapify(heap)  # 原地线性时间构建最小堆。",
            "smallest = heapq.heappop(heap)  # 弹出最小元素。",
            "largest_two = heapq.nlargest(2, heap)  # 高效取得少量最大元素。",
            "assert values == sorted(values) and smallest == 1  # 验证两个数据结构。",
            "print(values, heap, largest_two)  # 输出有序列表和堆。",
        ],
        [
            "from typing import Protocol, TypeVar  # 导入结构化类型工具。",
            "class SupportsLen(Protocol):  # 定义只要求__len__的协议。",
            "    def __len__(self) -> int:  # 声明所需方法签名。",
            "        ...  # 协议无需实现。",
            "T = TypeVar('T')  # 定义泛型类型变量。",
            "def first(items: list[T]) -> T:  # 泛型函数保持输入元素类型。",
            "    if not items:  # 检查空列表。",
            "        raise ValueError('empty')  # 空输入没有首元素。",
            "    return items[0]  # 返回同类型元素。",
            "def length(value: SupportsLen) -> int:  # 接受任何结构上支持len的对象。",
            "    return len(value)  # 调用协议方法。",
            f"answer = first([{n}, 4, 5])  # 类型检查器可推导answer为int。",
            f"assert answer == {n} and length('abc') == 3  # 验证泛型与鸭子类型。",
            "print(answer, length([1, 2]))  # 输出类型协议结果。",
        ],
        [
            "values = list(range(1000))  # list顺序存储且按位置访问O(1)。",
            "lookup = set(values)  # set平均O(1)成员测试但需额外内存。",
            f"target = {n * 10}  # 设置查找目标。",
            "in_list = target in values  # list成员测试最坏O(n)。",
            "in_set = target in lookup  # set成员测试平均O(1)。",
            "matrix_bad = [[0] * 3] * 3  # 重复同一个内部列表引用的常见陷阱。",
            "matrix_good = [[0 for _ in range(3)] for _ in range(3)]  # 每行创建独立列表。",
            "matrix_bad[0][0] = 1  # 修改一行会影响所有共享行。",
            "matrix_good[0][0] = 1  # 正确矩阵只修改第一行。",
            "assert in_list == in_set and sum(row[0] for row in matrix_bad) == 3  # 验证复杂度容器和别名陷阱。",
            "print(matrix_bad, matrix_good)  # 输出错误与正确矩阵。",
        ],
    ]
    return title, task, cases[family]
