"""PyTorch 与机器学习高频题目定义。"""

from __future__ import annotations


LEVELS = ["基础", "变式", "易错点", "综合"]


def pytorch_case(family: int, variant: int) -> tuple[str, str, list[str]]:
    titles = [
        "Tensor创建dtype与device",
        "reshapeviewpermute与contiguous",
        "广播索引与mask",
        "Autograd梯度计算",
        "detach与no_grad",
        "自定义nnModule",
        "线性回归训练",
        "多分类与CrossEntropyLoss",
        "二分类与BCEWithLogitsLoss",
        "Dataset与DataLoader",
        "SGD与Adam优化器",
        "train与eval模式",
        "模型保存与加载",
        "参数初始化",
        "梯度裁剪",
        "Embedding与padding_idx",
        "RNN序列建模",
        "LSTM与隐藏状态",
        "GRU序列分类",
        "Conv2d输出shape",
        "Pooling与AdaptivePooling",
        "MultiheadAttention",
        "TransformerEncoder",
        "学习率调度器",
        "指标计算与混淆矩阵",
    ]
    title = titles[family]
    task = f"完成“{title}”的{LEVELS[variant - 1]}题，说明训练态、梯度和张量shape。"
    n = variant + 2
    cases: list[list[str]] = [
        [
            "import torch  # 导入 PyTorch。",
            f"tensor = torch.tensor([[1, 2], [3, {n}]], dtype=torch.float32)  # 显式指定浮点dtype创建Tensor。",
            "zeros = torch.zeros_like(tensor)  # 创建同shape、dtype和device的零Tensor。",
            "converted = tensor.to(dtype=torch.float64)  # 使用to转换dtype并返回新Tensor。",
            "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')  # 自动选择可用计算设备。",
            "on_device = tensor.to(device)  # 把数据移动到目标设备。",
            "assert tensor.shape == (2, 2) and converted.dtype == torch.float64  # 验证shape和类型。",
            "print(tensor, zeros, on_device.device)  # 输出Tensor与设备。",
        ],
        [
            "import torch  # 导入 PyTorch。",
            "tensor = torch.arange(24).reshape(2, 3, 4)  # 创建三维Tensor。",
            "permuted = tensor.permute(2, 0, 1)  # 重排维度得到shape(4,2,3)。",
            "is_contiguous_before = permuted.is_contiguous()  # permute通常产生非连续视图。",
            "flattened = permuted.contiguous().view(-1)  # 先连续化再使用view展平。",
            "reshaped = permuted.reshape(4, 6)  # reshape必要时自动复制以满足布局。",
            "assert flattened.numel() == tensor.numel() and reshaped.shape == (4, 6)  # 验证元素数不变。",
            "print(is_contiguous_before, tensor.stride(), permuted.stride())  # 输出连续性和步幅。",
        ],
        [
            "import torch  # 导入 PyTorch。",
            "matrix = torch.arange(12).reshape(3, 4)  # 创建3×4 Tensor。",
            "bias = torch.tensor([10, 20, 30, 40])  # 创建可广播的列偏置。",
            "shifted = matrix + bias  # 广播完成逐列加法。",
            f"mask = shifted.gt({10 + n})  # 创建布尔mask。",
            "selected = shifted[mask]  # 使用布尔索引提取一维结果。",
            "gathered = shifted.gather(1, torch.tensor([[0], [1], [2]]))  # 每行按不同列索引收集元素。",
            "assert gathered.shape == (3, 1)  # 验证gather输出shape。",
            "print(selected, gathered)  # 输出索引结果。",
        ],
        [
            "import torch  # 导入 PyTorch。",
            f"x = torch.tensor({float(n)}, requires_grad=True)  # 创建需要梯度的叶子Tensor。",
            "y = x**3 + 2 * x**2 - x  # 构建标量计算图。",
            "y.backward()  # 反向传播计算dy/dx。",
            "expected = 3 * x.detach() ** 2 + 4 * x.detach() - 1  # 手算解析梯度。",
            "assert torch.allclose(x.grad, expected)  # 验证Autograd结果。",
            "print(y.item(), x.grad.item(), y.grad_fn)  # 输出函数值、梯度和计算图节点。",
        ],
        [
            "import torch  # 导入 PyTorch。",
            "parameter = torch.tensor([2.0], requires_grad=True)  # 创建模型参数。",
            "tracked = parameter * 3  # 默认建立计算图。",
            "detached = tracked.detach()  # detach与原Tensor共享数据但切断梯度。",
            "with torch.no_grad():  # 在推理上下文中关闭梯度记录。",
            "    prediction = parameter * 4  # 该运算不会构建计算图。",
            "assert tracked.requires_grad and not detached.requires_grad and not prediction.requires_grad  # 验证三种梯度状态。",
            "print(tracked, detached, prediction)  # 输出不同状态Tensor。",
        ],
        [
            "import torch  # 导入 PyTorch。",
            "from torch import nn  # 导入神经网络模块。",
            "class TinyMLP(nn.Module):  # 定义继承nn.Module的模型。",
            "    def __init__(self):  # 初始化可训练层。",
            "        super().__init__()  # 注册父类内部状态。",
            "        self.network = nn.Sequential(nn.Linear(4, 8), nn.ReLU(), nn.Linear(8, 3))  # 组合两层MLP。",
            "    def forward(self, features):  # 定义前向计算。",
            "        return self.network(features)  # 返回三分类logits。",
            "model = TinyMLP()  # 实例化模型。",
            f"output = model(torch.randn({n}, 4))  # 输入随变式变化的batch。",
            "assert output.shape == (output.size(0), 3)  # 验证最后一维是类别数。",
            "print(model, output.shape, sum(parameter.numel() for parameter in model.parameters()))  # 输出结构、shape和参数量。",
        ],
        [
            "import torch  # 导入 PyTorch。",
            "from torch import nn  # 导入神经网络模块。",
            "torch.manual_seed(0)  # 固定随机种子。",
            "x = torch.linspace(-1, 1, 40).unsqueeze(1)  # 创建单特征训练样本。",
            "y = 3 * x + 2  # 根据真实线性关系生成标签。",
            "model = nn.Linear(1, 1)  # 定义线性回归模型。",
            f"optimizer = torch.optim.SGD(model.parameters(), lr={0.05 + variant * 0.01})  # 创建SGD优化器。",
            "for _ in range(150):  # 执行固定轮数训练。",
            "    loss = nn.functional.mse_loss(model(x), y)  # 计算均方误差。",
            "    optimizer.zero_grad()  # 清除上一轮累积梯度。",
            "    loss.backward()  # 反向传播。",
            "    optimizer.step()  # 更新参数。",
            "assert loss.item() < 0.01  # 验证模型学会线性关系。",
            "print(model.weight.item(), model.bias.item(), loss.item())  # 输出拟合参数和损失。",
        ],
        [
            "import torch  # 导入 PyTorch。",
            "from torch import nn  # 导入损失函数模块。",
            "logits = torch.tensor([[2.0, 0.5, -1.0], [0.1, 1.5, 0.2]], requires_grad=True)  # CrossEntropy接收未归一化logits。",
            "labels = torch.tensor([0, 1])  # 多分类标签使用Long类别索引。",
            f"loss = nn.CrossEntropyLoss(label_smoothing={variant * 0.02})(logits, labels)  # 内部组合log_softmax和NLLLoss。",
            "loss.backward()  # 计算logits梯度。",
            "probabilities = logits.detach().softmax(dim=1)  # 仅展示时转换概率。",
            "assert torch.allclose(probabilities.sum(1), torch.ones(2))  # 验证每行概率和为1。",
            "print(loss.item(), probabilities, logits.grad)  # 输出损失、概率和梯度。",
        ],
        [
            "import torch  # 导入 PyTorch。",
            "from torch import nn  # 导入损失函数模块。",
            "logits = torch.tensor([1.5, -0.5, 0.2], requires_grad=True)  # 二分类模型输出一个logit。",
            "targets = torch.tensor([1.0, 0.0, 1.0])  # BCE目标必须为浮点0或1。",
            "loss = nn.BCEWithLogitsLoss()(logits, targets)  # 数值稳定地组合sigmoid和BCE。",
            "loss.backward()  # 反向传播。",
            "probabilities = logits.detach().sigmoid()  # 推理阶段用sigmoid得到正类概率。",
            f"predictions = probabilities.ge({0.4 + variant * 0.02}).int()  # 使用可调阈值得到类别。",
            "assert predictions.shape == targets.shape  # 验证预测shape。",
            "print(loss.item(), probabilities, predictions)  # 输出二分类结果。",
        ],
        [
            "import torch  # 导入 PyTorch。",
            "from torch.utils.data import DataLoader, TensorDataset  # 导入数据集和批加载器。",
            "features = torch.arange(40, dtype=torch.float32).reshape(10, 4)  # 创建十个四维样本。",
            "labels = torch.arange(10) % 2  # 创建二分类标签。",
            "dataset = TensorDataset(features, labels)  # 把多个Tensor按第一维组成数据集。",
            f"loader = DataLoader(dataset, batch_size={variant + 1}, shuffle=True, generator=torch.Generator().manual_seed(0))  # 创建可复现的随机batch。",
            "batch_features, batch_labels = next(iter(loader))  # 取得第一个batch。",
            f"assert len(dataset) == 10 and len(batch_features) <= {variant + 1}  # 验证样本数和batch大小。",
            "print(batch_features.shape, batch_labels)  # 输出batch。",
        ],
        [
            "import torch  # 导入 PyTorch。",
            "from torch import nn  # 导入模型模块。",
            "torch.manual_seed(0)  # 固定初始化。",
            "model_sgd = nn.Linear(2, 1)  # 创建SGD模型。",
            "model_adam = nn.Linear(2, 1)  # 创建Adam模型。",
            "model_adam.load_state_dict(model_sgd.state_dict())  # 让两个模型从相同参数开始。",
            "x = torch.tensor([[1.0, 2.0]])  # 创建单个样本。",
            "target = torch.tensor([[1.0]])  # 创建回归目标。",
            f"optimizers = [torch.optim.SGD(model_sgd.parameters(), lr={0.01 * n}), torch.optim.Adam(model_adam.parameters(), lr=0.01)]  # 配置两种优化器。",
            "for model, optimizer in zip([model_sgd, model_adam], optimizers):  # 分别执行一步更新。",
            "    loss = (model(x) - target).square().mean()  # 计算MSE。",
            "    optimizer.zero_grad()  # 清梯度。",
            "    loss.backward()  # 算梯度。",
            "    optimizer.step()  # 更新参数。",
            "print(model_sgd.weight, model_adam.weight)  # 对比一步后的参数。",
        ],
        [
            "import torch  # 导入 PyTorch。",
            "from torch import nn  # 导入模型模块。",
            "torch.manual_seed(0)  # 固定随机种子。",
            "model = nn.Sequential(nn.Linear(4, 4), nn.BatchNorm1d(4), nn.Dropout(0.5))  # 组合受模式影响的层。",
            "x = torch.randn(8, 4)  # 创建batch输入。",
            "model.train()  # 开启Dropout并更新BatchNorm运行统计。",
            "train_output = model(x)  # 训练态前向。",
            "model.eval()  # 关闭Dropout并冻结BatchNorm运行统计。",
            "with torch.no_grad():  # 推理时关闭梯度记录。",
            "    eval_output_1 = model(x)  # 第一次推理。",
            "    eval_output_2 = model(x)  # 第二次推理。",
            "assert torch.allclose(eval_output_1, eval_output_2)  # 验证eval输出确定性。",
            "print(torch.allclose(train_output, eval_output_1))  # 比较训练态与推理态。",
        ],
        [
            "from pathlib import Path  # 导入路径工具。",
            "import tempfile  # 导入临时目录工具。",
            "import torch  # 导入 PyTorch。",
            "from torch import nn  # 导入模型模块。",
            "torch.manual_seed(0)  # 固定初始化。",
            "model = nn.Linear(3, 2)  # 创建待保存模型。",
            "with tempfile.TemporaryDirectory() as folder:  # 使用自动清理的临时目录。",
            "    path = Path(folder) / 'model.pt'  # 组成checkpoint路径。",
            "    torch.save({'model_state': model.state_dict(), 'epoch': 5}, path)  # 保存state_dict和元数据。",
            "    checkpoint = torch.load(path, weights_only=True)  # 安全加载仅含Tensor的checkpoint。",
            "    restored = nn.Linear(3, 2)  # 创建相同结构模型。",
            "    restored.load_state_dict(checkpoint['model_state'])  # 恢复参数。",
            "assert all(torch.equal(a, b) for a, b in zip(model.parameters(), restored.parameters()))  # 验证参数完全一致。",
            "print(checkpoint['epoch'])  # 输出恢复的训练元数据。",
        ],
        [
            "import torch  # 导入 PyTorch。",
            "from torch import nn  # 导入模型模块。",
            "torch.manual_seed(0)  # 固定随机种子。",
            "layer = nn.Linear(64, 32)  # 创建线性层。",
            f"nn.init.kaiming_uniform_(layer.weight, nonlinearity='relu')  # 为ReLU网络使用Kaiming初始化变式{variant}。",
            "nn.init.zeros_(layer.bias)  # 偏置初始化为零。",
            "fan_in, fan_out = nn.init._calculate_fan_in_and_fan_out(layer.weight)  # 取得扇入扇出用于解释方差。",
            "assert torch.count_nonzero(layer.bias) == 0  # 验证偏置为零。",
            "print(layer.weight.mean().item(), layer.weight.std().item(), fan_in, fan_out)  # 输出初始化统计。",
        ],
        [
            "import torch  # 导入 PyTorch。",
            "from torch import nn  # 导入模型模块。",
            "model = nn.Linear(3, 1)  # 创建简单模型。",
            "x = torch.tensor([[100.0, -100.0, 50.0]])  # 创建会产生较大梯度的输入。",
            "loss = model(x).square().mean()  # 构造损失。",
            "loss.backward()  # 计算原始梯度。",
            "before = torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)  # 按总范数裁剪并返回裁剪前范数。",
            "after = torch.sqrt(sum(parameter.grad.square().sum() for parameter in model.parameters()))  # 计算裁剪后总范数。",
            "assert after <= 1.00001  # 验证梯度范数不超过阈值。",
            "print(before.item(), after.item())  # 输出裁剪前后范数。",
        ],
        [
            "import torch  # 导入 PyTorch。",
            "from torch import nn  # 导入Embedding模块。",
            "token_ids = torch.tensor([[2, 5, 0, 0], [1, 3, 4, 0]])  # 0作为PAD token。",
            f"embedding = nn.Embedding(num_embeddings=10, embedding_dim={n * 2}, padding_idx=0)  # 创建词嵌入并固定PAD向量。",
            "vectors = embedding(token_ids)  # 把(B,T)映射为(B,T,D)。",
            "loss = vectors.square().sum()  # 构造用于反向传播的损失。",
            "loss.backward()  # 计算Embedding权重梯度。",
            "assert torch.count_nonzero(embedding.weight.grad[0]) == 0  # padding_idx对应行不更新。",
            "print(vectors.shape, embedding.weight.grad[0])  # 输出shape和PAD梯度。",
        ],
        [
            "import torch  # 导入 PyTorch。",
            "from torch import nn  # 导入RNN模块。",
            "torch.manual_seed(0)  # 固定随机种子。",
            "batch, steps, features, hidden = 3, 5, 4, 6  # 定义序列维度。",
            "rnn = nn.RNN(features, hidden, num_layers=2, batch_first=True, nonlinearity='tanh')  # 创建两层RNN。",
            "sequence = torch.randn(batch, steps, features)  # 创建batch-first输入。",
            "outputs, final_hidden = rnn(sequence)  # 取得所有时间步输出和各层最终状态。",
            "assert outputs.shape == (batch, steps, hidden) and final_hidden.shape == (2, batch, hidden)  # 验证shape。",
            "print(outputs[:, -1], final_hidden[-1])  # 对比顶层最后输出与最终隐藏状态。",
        ],
        [
            "import torch  # 导入 PyTorch。",
            "from torch import nn  # 导入LSTM模块。",
            "torch.manual_seed(0)  # 固定随机种子。",
            "lstm = nn.LSTM(input_size=5, hidden_size=7, num_layers=2, batch_first=True, bidirectional=True)  # 创建双向两层LSTM。",
            "sequence = torch.randn(4, 6, 5)  # 创建(B,T,F)输入。",
            "outputs, (hidden, cell) = lstm(sequence)  # LSTM返回hidden和cell两类状态。",
            "assert outputs.shape == (4, 6, 14)  # 双向输出特征为2×hidden。",
            "assert hidden.shape == cell.shape == (4, 4, 7)  # 层数×方向数为4。",
            "print(outputs.shape, hidden.shape, cell.shape)  # 输出关键shape。",
        ],
        [
            "import torch  # 导入 PyTorch。",
            "from torch import nn  # 导入GRU和线性层。",
            "torch.manual_seed(0)  # 固定随机种子。",
            "gru = nn.GRU(input_size=4, hidden_size=8, batch_first=True)  # 创建单层GRU。",
            "head = nn.Linear(8, 3)  # 创建三分类头。",
            "sequence = torch.randn(5, 7, 4)  # 创建五条长度七的序列。",
            "outputs, hidden = gru(sequence)  # 运行序列编码。",
            "logits = head(hidden[-1])  # 使用最终隐藏状态分类。",
            "labels = torch.tensor([0, 1, 2, 1, 0])  # 创建类别标签。",
            "loss = nn.CrossEntropyLoss()(logits, labels)  # 计算分类损失。",
            "loss.backward()  # 验证整个模型可反向传播。",
            "assert logits.shape == (5, 3)  # 验证分类输出shape。",
            "print(loss.item(), outputs.shape, hidden.shape)  # 输出损失和状态shape。",
        ],
        [
            "import torch  # 导入 PyTorch。",
            "from torch import nn  # 导入卷积层。",
            "height = width = 32  # 设置输入空间尺寸。",
            f"kernel = {3 if variant < 4 else 5}  # 设置卷积核大小。",
            "conv = nn.Conv2d(in_channels=3, out_channels=8, kernel_size=kernel, stride=2, padding=1)  # 创建二维卷积。",
            "images = torch.randn(4, 3, height, width)  # 创建NCHW图像batch。",
            "features = conv(images)  # 运行卷积。",
            "expected = (height + 2 - kernel) // 2 + 1  # 根据卷积公式计算输出边长。",
            "assert features.shape == (4, 8, expected, expected)  # 验证输出shape。",
            "print(features.shape, expected)  # 输出实际与公式结果。",
        ],
        [
            "import torch  # 导入 PyTorch。",
            "from torch import nn  # 导入池化模块。",
            "features = torch.arange(2 * 3 * 8 * 8, dtype=torch.float32).reshape(2, 3, 8, 8)  # 创建NCHW特征图。",
            "max_pooled = nn.MaxPool2d(kernel_size=2, stride=2)(features)  # 最大池化把空间尺寸减半。",
            f"adaptive = nn.AdaptiveAvgPool2d(({variant}, {variant}))(features)  # 自适应池化直接指定输出尺寸。",
            "global_average = nn.AdaptiveAvgPool2d(1)(features).flatten(1)  # 全局平均池化得到每通道特征。",
            "assert max_pooled.shape == (2, 3, 4, 4) and global_average.shape == (2, 3)  # 验证shape。",
            "print(max_pooled.shape, adaptive.shape, global_average)  # 输出池化结果。",
        ],
        [
            "import torch  # 导入 PyTorch。",
            "from torch import nn  # 导入多头注意力层。",
            "torch.manual_seed(0)  # 固定随机种子。",
            "attention = nn.MultiheadAttention(embed_dim=16, num_heads=4, batch_first=True)  # 创建batch-first多头注意力。",
            "tokens = torch.randn(2, 5, 16)  # 创建token表示。",
            "padding_mask = torch.tensor([[False, False, False, True, True], [False, False, False, False, True]])  # True表示屏蔽key。",
            "output, weights = attention(tokens, tokens, tokens, key_padding_mask=padding_mask, need_weights=True, average_attn_weights=False)  # 执行Self-Attention。",
            "assert output.shape == tokens.shape and weights.shape == (2, 4, 5, 5)  # 验证输出和逐头权重shape。",
            "print(output.shape, weights[0, 0])  # 输出shape和一个head权重。",
        ],
        [
            "import torch  # 导入 PyTorch。",
            "from torch import nn  # 导入Transformer Encoder。",
            "torch.manual_seed(0)  # 固定随机种子。",
            "layer = nn.TransformerEncoderLayer(d_model=16, nhead=4, dim_feedforward=64, batch_first=True)  # 配置单层Encoder。",
            f"encoder = nn.TransformerEncoder(layer, num_layers={variant}, enable_nested_tensor=False)  # 堆叠随变式变化的层数。",
            "tokens = torch.randn(2, 6, 16)  # 创建(B,T,D)输入。",
            "padding_mask = torch.tensor([[False, False, False, False, True, True], [False, False, False, False, False, True]])  # 定义PAD mask。",
            "encoded = encoder(tokens, src_key_padding_mask=padding_mask)  # 编码时屏蔽PAD key。",
            "pooled = (encoded * (~padding_mask).unsqueeze(-1)).sum(1) / (~padding_mask).sum(1, keepdim=True)  # masked mean pooling。",
            "assert encoded.shape == tokens.shape and pooled.shape == (2, 16)  # 验证序列与池化shape。",
            "print(encoded.shape, pooled.shape)  # 输出Encoder结果。",
        ],
        [
            "import torch  # 导入 PyTorch。",
            "from torch import nn  # 导入模型模块。",
            "model = nn.Linear(2, 1)  # 创建可优化模型。",
            "optimizer = torch.optim.SGD(model.parameters(), lr=0.1)  # 设置初始学习率。",
            f"scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size={variant}, gamma=0.5)  # 每指定轮数衰减学习率。",
            "history = []  # 保存学习率轨迹。",
            "for _ in range(6):  # 模拟六个epoch。",
            "    optimizer.zero_grad()  # 清除梯度。",
            "    model(torch.ones(1, 2)).sum().backward()  # 构造并反向传播简单损失。",
            "    optimizer.step()  # 更新模型参数。",
            "    scheduler.step()  # 在epoch末更新学习率。",
            "    history.append(scheduler.get_last_lr()[0])  # 记录当前学习率。",
            "assert history[-1] <= history[0]  # 验证学习率未增长。",
            "print(history)  # 输出调度轨迹。",
        ],
        [
            "import torch  # 导入 PyTorch。",
            "predictions = torch.tensor([0, 1, 2, 1, 0, 2, 1, 1])  # 创建三分类预测。",
            "targets = torch.tensor([0, 2, 2, 1, 0, 0, 1, 2])  # 创建真实标签。",
            "num_classes = 3  # 设置类别数。",
            "indices = targets * num_classes + predictions  # 把二维类别对编码为一维索引。",
            "confusion = torch.bincount(indices, minlength=num_classes**2).reshape(num_classes, num_classes)  # 构建混淆矩阵。",
            "true_positive = confusion.diag().float()  # 取得各类TP。",
            "precision = true_positive / confusion.sum(0).clamp_min(1)  # 按预测列计算precision。",
            "recall = true_positive / confusion.sum(1).clamp_min(1)  # 按真实行计算recall。",
            "accuracy = true_positive.sum() / confusion.sum()  # 计算整体准确率。",
            "assert confusion.sum() == len(targets)  # 验证每个样本被统计一次。",
            "print(confusion, precision, recall, accuracy)  # 输出分类指标。",
        ],
    ]
    return title, task, cases[family]
