"""scikit-learn 高频面试题定义。"""

from __future__ import annotations


LEVELS = ["基础", "综合"]


def sklearn_case(family: int, variant: int) -> tuple[str, str, list[str]]:
    titles = [
        "train_test_split与分层",
        "StandardScaler只拟合训练集",
        "缺失值SimpleImputer",
        "OneHotEncoder未知类别",
        "ColumnTransformer混合特征",
        "Pipeline防止数据泄漏",
        "KFold与StratifiedKFold",
        "cross_validate多指标",
        "GridSearchCV参数搜索",
        "RandomizedSearchCV",
        "LinearRegression与R2",
        "LogisticRegression分类",
        "KNeighborsClassifier",
        "DecisionTree与过拟合控制",
        "RandomForest特征重要性",
        "GradientBoosting",
        "SVM与特征缩放",
        "KMeans与silhouette",
        "PCA与解释方差",
        "classification_report与混淆矩阵",
        "ROC_AUC与PR_AUC",
        "类别权重与不平衡",
        "学习曲线",
        "PermutationImportance",
        "模型持久化与复现",
    ]
    title = titles[family]
    task = f"完成“{title}”的{LEVELS[variant - 1]}题，说明fit、transform和predict各自只能使用哪些数据。"
    seed = 40 + variant
    cases: list[list[str]] = [
        [
            "from sklearn.datasets import load_iris  # 导入经典分类数据。",
            "from sklearn.model_selection import train_test_split  # 导入数据切分函数。",
            "features, labels = load_iris(return_X_y=True)  # 加载特征和标签。",
            f"train_x, test_x, train_y, test_y = train_test_split(features, labels, test_size=0.2, random_state={seed}, stratify=labels)  # 分层切分保持类别比例。",
            "assert len(train_x) == 120 and len(test_x) == 30  # 验证切分大小。",
            "print(train_x.shape, test_x.shape, __import__('numpy').bincount(train_y))  # 输出shape和训练类别数。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "from sklearn.preprocessing import StandardScaler  # 导入标准化器。",
            "train = np.array([[1.0], [2.0], [3.0]])  # 创建训练数据。",
            "test = np.array([[100.0]])  # 创建分布不同的测试数据。",
            "scaler = StandardScaler().fit(train)  # 只能在训练集拟合均值和方差。",
            "train_scaled = scaler.transform(train)  # 使用训练统计量转换训练集。",
            "test_scaled = scaler.transform(test)  # 使用同一统计量转换测试集。",
            "assert np.isclose(train_scaled.mean(), 0) and test_scaled.item() > 10  # 验证没有用测试数据污染统计量。",
            "print(scaler.mean_, scaler.scale_, test_scaled)  # 输出拟合参数和转换结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "from sklearn.impute import SimpleImputer  # 导入缺失值填充器。",
            "train = np.array([[1.0, np.nan], [2.0, 4.0], [3.0, 8.0]])  # 创建含NaN训练数据。",
            "test = np.array([[np.nan, 100.0]])  # 创建含缺失测试样本。",
            f"imputer = SimpleImputer(strategy={repr('median' if variant == 1 else 'mean')}).fit(train)  # 只用训练数据拟合填充值。",
            "filled_train = imputer.transform(train)  # 填充训练集。",
            "filled_test = imputer.transform(test)  # 用训练填充值处理测试集。",
            "assert not np.isnan(filled_train).any() and not np.isnan(filled_test).any()  # 验证无剩余NaN。",
            "print(imputer.statistics_, filled_test)  # 输出填充值和结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "from sklearn.preprocessing import OneHotEncoder  # 导入独热编码器。",
            "train = np.array([['red'], ['blue'], ['red']])  # 创建训练类别。",
            "test = np.array([['green'], ['red']])  # 测试集包含未知类别。",
            "encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False).fit(train)  # 忽略推理时未知类别避免报错。",
            "encoded = encoder.transform(test)  # 转换测试类别。",
            "assert encoded.shape == (2, 2) and encoded[0].sum() == 0  # 未知类别编码为全零。",
            "print(encoder.categories_, encoded)  # 输出学习到的类别和编码。",
        ],
        [
            "import pandas as pd  # 导入 Pandas。",
            "from sklearn.compose import ColumnTransformer  # 导入列级转换器。",
            "from sklearn.preprocessing import OneHotEncoder, StandardScaler  # 导入数值和类别转换器。",
            "frame = pd.DataFrame({'age': [20, 30, 40], 'income': [30, 60, 90], 'city': ['A', 'B', 'A']})  # 创建混合特征表。",
            "preprocessor = ColumnTransformer([('numeric', StandardScaler(), ['age', 'income']), ('category', OneHotEncoder(sparse_output=False), ['city'])])  # 为不同列配置不同处理。",
            "transformed = preprocessor.fit_transform(frame)  # 一次拟合并转换训练数据。",
            "names = preprocessor.get_feature_names_out()  # 获取转换后的特征名。",
            "assert transformed.shape == (3, 4)  # 两个数值列加两个类别列。",
            "print(names, transformed)  # 输出特征名和矩阵。",
        ],
        [
            "from sklearn.datasets import load_iris  # 导入Iris数据。",
            "from sklearn.linear_model import LogisticRegression  # 导入逻辑回归。",
            "from sklearn.model_selection import cross_val_score  # 导入交叉验证评分。",
            "from sklearn.pipeline import Pipeline  # 导入流水线。",
            "from sklearn.preprocessing import StandardScaler  # 导入标准化器。",
            "features, labels = load_iris(return_X_y=True)  # 加载数据。",
            "pipeline = Pipeline([('scale', StandardScaler()), ('model', LogisticRegression(max_iter=500))])  # 把预处理放进每折内部防泄漏。",
            f"scores = cross_val_score(pipeline, features, labels, cv={3 + variant}, scoring='accuracy')  # 对完整Pipeline交叉验证。",
            "assert scores.mean() > 0.9  # 验证模型表现合理。",
            "print(scores, scores.mean())  # 输出各折准确率。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "from sklearn.model_selection import KFold, StratifiedKFold  # 导入两种K折。",
            "features = np.zeros((12, 1))  # 创建占位特征。",
            "labels = np.array([0] * 8 + [1] * 4)  # 创建不平衡标签。",
            "plain = KFold(n_splits=4, shuffle=True, random_state=42)  # 普通KFold不保证每折类别比例。",
            "stratified = StratifiedKFold(n_splits=4, shuffle=True, random_state=42)  # 分层KFold保持比例。",
            "ratios = [labels[test].mean() for _, test in stratified.split(features, labels)]  # 计算各验证折正类比例。",
            "assert np.allclose(ratios, labels.mean())  # 验证分层比例一致。",
            "print(len(list(plain.split(features))), ratios)  # 输出折数和分层比例。",
        ],
        [
            "from sklearn.datasets import load_breast_cancer  # 导入二分类数据。",
            "from sklearn.ensemble import RandomForestClassifier  # 导入非线性分类器。",
            "from sklearn.model_selection import cross_validate  # 导入多指标交叉验证。",
            "features, labels = load_breast_cancer(return_X_y=True)  # 加载数据。",
            "model = RandomForestClassifier(n_estimators=40, max_depth=5, random_state=42)  # 建立可复现的分类模型。",
            "result = cross_validate(model, features, labels, cv=3, scoring=['accuracy', 'roc_auc'], return_train_score=True)  # 同时评估多个指标。",
            "assert result['test_roc_auc'].mean() > 0.9  # 验证AUC合理。",
            "print({key: value.mean() for key, value in result.items() if key.startswith('test_')})  # 输出测试指标均值。",
        ],
        [
            "from sklearn.datasets import load_iris  # 导入分类数据。",
            "from sklearn.model_selection import GridSearchCV  # 导入网格搜索。",
            "from sklearn.pipeline import make_pipeline  # 导入Pipeline。",
            "from sklearn.preprocessing import StandardScaler  # 导入标准化器。",
            "from sklearn.svm import SVC  # 导入支持向量机。",
            "features, labels = load_iris(return_X_y=True)  # 加载数据。",
            "pipeline = make_pipeline(StandardScaler(), SVC())  # 建立预处理加模型流水线。",
            "search = GridSearchCV(pipeline, {'svc__C': [0.1, 1, 10], 'svc__kernel': ['linear', 'rbf']}, cv=3, scoring='accuracy').fit(features, labels)  # 使用步骤名双下划线搜索参数。",
            "assert 'svc__C' in search.best_params_  # 验证找到最优参数。",
            "print(search.best_params_, search.best_score_)  # 输出最优配置。",
        ],
        [
            "from scipy.stats import loguniform  # 导入对数均匀分布。",
            "from sklearn.datasets import load_iris  # 导入分类数据。",
            "from sklearn.linear_model import LogisticRegression  # 导入逻辑回归。",
            "from sklearn.model_selection import RandomizedSearchCV  # 导入随机搜索。",
            "from sklearn.pipeline import make_pipeline  # 导入Pipeline。",
            "from sklearn.preprocessing import StandardScaler  # 导入标准化。",
            "features, labels = load_iris(return_X_y=True)  # 加载数据。",
            "pipeline = make_pipeline(StandardScaler(), LogisticRegression(max_iter=500))  # 建立Pipeline。",
            f"search = RandomizedSearchCV(pipeline, {{'logisticregression__C': loguniform(1e-3, 1e2)}}, n_iter={3 + variant}, cv=3, random_state=42).fit(features, labels)  # 从连续分布随机抽取超参数。",
            "assert search.best_estimator_ is not None  # 验证搜索完成。",
            "print(search.best_params_, search.best_score_)  # 输出最优参数和分数。",
        ],
        [
            "from sklearn.datasets import load_diabetes  # 导入回归数据。",
            "from sklearn.linear_model import LinearRegression  # 导入线性回归。",
            "from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score  # 导入回归指标。",
            "from sklearn.model_selection import train_test_split  # 导入切分函数。",
            "features, targets = load_diabetes(return_X_y=True)  # 加载数据。",
            f"train_x, test_x, train_y, test_y = train_test_split(features, targets, test_size=0.2, random_state={seed})  # 固定随机切分。",
            "model = LinearRegression().fit(train_x, train_y)  # 拟合普通最小二乘。",
            "predictions = model.predict(test_x)  # 对未见测试集预测。",
            "metrics = mean_squared_error(test_y, predictions), mean_absolute_error(test_y, predictions), r2_score(test_y, predictions)  # 计算MSE、MAE、R²。",
            "assert predictions.shape == test_y.shape  # 验证预测shape。",
            "print(metrics)  # 输出回归指标。",
        ],
        [
            "from sklearn.datasets import load_iris  # 导入Iris数据。",
            "from sklearn.linear_model import LogisticRegression  # 导入逻辑回归。",
            "from sklearn.metrics import accuracy_score, log_loss  # 导入分类指标。",
            "from sklearn.model_selection import train_test_split  # 导入切分函数。",
            "features, labels = load_iris(return_X_y=True)  # 加载数据。",
            f"train_x, test_x, train_y, test_y = train_test_split(features, labels, test_size=0.25, random_state={seed}, stratify=labels)  # 分层切分。",
            "model = LogisticRegression(max_iter=500).fit(train_x, train_y)  # 训练多分类逻辑回归。",
            "probabilities = model.predict_proba(test_x)  # 输出每类概率。",
            "predictions = probabilities.argmax(axis=1)  # 概率最大类别即预测。",
            "assert accuracy_score(test_y, predictions) > 0.85  # 验证准确率。",
            "print(accuracy_score(test_y, predictions), log_loss(test_y, probabilities))  # 输出硬指标和概率指标。",
        ],
        [
            "from sklearn.datasets import load_iris  # 导入Iris数据。",
            "from sklearn.model_selection import cross_val_score  # 导入交叉验证。",
            "from sklearn.neighbors import KNeighborsClassifier  # 导入KNN。",
            "from sklearn.pipeline import make_pipeline  # 导入Pipeline。",
            "from sklearn.preprocessing import StandardScaler  # KNN对尺度敏感需标准化。",
            "features, labels = load_iris(return_X_y=True)  # 加载数据。",
            f"model = make_pipeline(StandardScaler(), KNeighborsClassifier(n_neighbors={3 + 2 * (variant - 1)}, weights='distance'))  # 配置距离加权KNN。",
            "scores = cross_val_score(model, features, labels, cv=5)  # 交叉验证泛化性能。",
            "assert scores.mean() > 0.85  # 验证模型表现。",
            "print(scores, scores.mean())  # 输出各折分数。",
        ],
        [
            "from sklearn.datasets import load_iris  # 导入分类数据。",
            "from sklearn.model_selection import train_test_split  # 导入切分函数。",
            "from sklearn.tree import DecisionTreeClassifier, export_text  # 导入决策树和文本导出。",
            "features, labels = load_iris(return_X_y=True)  # 加载数据。",
            "train_x, test_x, train_y, test_y = train_test_split(features, labels, stratify=labels, random_state=42)  # 分层切分。",
            f"model = DecisionTreeClassifier(max_depth={2 + variant}, min_samples_leaf=2, random_state=42).fit(train_x, train_y)  # 限制树深防止过拟合。",
            "train_score, test_score = model.score(train_x, train_y), model.score(test_x, test_y)  # 对比训练和测试准确率。",
            "rules = export_text(model, max_depth=2)  # 导出浅层规则便于解释。",
            f"assert model.get_depth() <= {2 + variant}  # 验证复杂度约束。",
            "print(train_score, test_score, '\\n', rules)  # 输出性能和规则。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "from sklearn.datasets import load_iris  # 导入分类数据。",
            "from sklearn.ensemble import RandomForestClassifier  # 导入随机森林。",
            "features, labels = load_iris(return_X_y=True)  # 加载数据。",
            f"model = RandomForestClassifier(n_estimators={20 + variant * 10}, max_depth=4, oob_score=True, bootstrap=True, random_state=42).fit(features, labels)  # 训练带袋外评估的森林。",
            "importance = model.feature_importances_  # 取得基于不纯度的特征重要性。",
            "order = np.argsort(importance)[::-1]  # 按重要性排序。",
            "assert np.isclose(importance.sum(), 1) and model.oob_score_ > 0.8  # 验证重要性归一化和OOB表现。",
            "print(order, importance, model.oob_score_)  # 输出特征排名。",
        ],
        [
            "from sklearn.datasets import load_breast_cancer  # 导入二分类数据。",
            "from sklearn.ensemble import GradientBoostingClassifier  # 导入梯度提升树。",
            "from sklearn.model_selection import train_test_split  # 导入数据切分。",
            "features, labels = load_breast_cancer(return_X_y=True)  # 加载数据。",
            "train_x, test_x, train_y, test_y = train_test_split(features, labels, stratify=labels, random_state=42)  # 分层切分。",
            f"model = GradientBoostingClassifier(n_estimators={30 + variant * 10}, learning_rate=0.05, max_depth=2, random_state=42).fit(train_x, train_y)  # 小学习率逐步拟合残差。",
            "staged_scores = [(stage_predictions == test_y).mean() for stage_predictions in model.staged_predict(test_x)]  # 观察每一阶段测试准确率。",
            "assert len(staged_scores) == model.n_estimators  # 验证每棵树对应一个阶段。",
            "print(model.score(test_x, test_y), max(staged_scores))  # 输出最终和最佳阶段分数。",
        ],
        [
            "from sklearn.datasets import load_breast_cancer  # 导入分类数据。",
            "from sklearn.model_selection import cross_val_score  # 导入交叉验证。",
            "from sklearn.pipeline import make_pipeline  # 导入Pipeline。",
            "from sklearn.preprocessing import StandardScaler  # SVM对尺度敏感。",
            "from sklearn.svm import SVC  # 导入核SVM。",
            "features, labels = load_breast_cancer(return_X_y=True)  # 加载数据。",
            f"model = make_pipeline(StandardScaler(), SVC(C={variant}, kernel='rbf', probability=True, random_state=42))  # 标准化后训练RBF SVM。",
            "scores = cross_val_score(model, features, labels, cv=3, scoring='roc_auc')  # 使用AUC交叉验证。",
            "assert scores.mean() > 0.9  # 验证性能合理。",
            "print(scores, scores.mean())  # 输出AUC。",
        ],
        [
            "import numpy as np  # 导入NumPy以局部管理当前平台的矩阵运算警告。",
            "from sklearn.cluster import KMeans  # 导入KMeans。",
            "from sklearn.datasets import make_blobs  # 导入聚类数据生成器。",
            "from sklearn.metrics import silhouette_score  # 导入轮廓系数。",
            "features, _ = make_blobs(n_samples=120, centers=3, cluster_std=0.6, random_state=42)  # 生成三个簇。",
            f"model = KMeans(n_clusters={2 + variant}, n_init=10, algorithm='elkan', random_state=42)  # 使用多次初始化和Elkan算法降低局部最优风险。",
            "with np.errstate(over='ignore', invalid='ignore', divide='ignore'):  # 仅屏蔽部分macOS Accelerate与NumPy组合的已知伪警告。",
            "    model.fit(features)  # 在局部数值错误策略下拟合KMeans。",
            "    score = silhouette_score(features, model.labels_)  # 计算簇内紧密簇间分离指标。",
            f"assert model.cluster_centers_.shape[0] == {2 + variant}  # 验证中心数量。",
            "print(model.inertia_, score, model.cluster_centers_)  # 输出惯性、轮廓系数和中心。",
        ],
        [
            "from sklearn.datasets import load_breast_cancer  # 导入高维数据。",
            "from sklearn.decomposition import PCA  # 导入PCA。",
            "from sklearn.pipeline import make_pipeline  # 导入Pipeline。",
            "from sklearn.preprocessing import StandardScaler  # PCA前标准化不同量纲特征。",
            "features, _ = load_breast_cancer(return_X_y=True)  # 加载数据。",
            f"pipeline = make_pipeline(StandardScaler(), PCA(n_components={2 + variant}, svd_solver='full'))  # 标准化后使用完整SVD降维。",
            "projected = pipeline.fit_transform(features)  # 拟合主成分并投影。",
            "pca = pipeline.named_steps['pca']  # 取得已拟合PCA步骤。",
            f"assert projected.shape[1] == {2 + variant} and pca.explained_variance_ratio_.sum() <= 1  # 验证降维shape和解释方差。",
            "print(projected.shape, pca.explained_variance_ratio_)  # 输出PCA结果。",
        ],
        [
            "from sklearn.datasets import load_iris  # 导入分类数据。",
            "from sklearn.ensemble import RandomForestClassifier  # 导入分类器。",
            "from sklearn.metrics import classification_report, confusion_matrix  # 导入综合指标。",
            "from sklearn.model_selection import cross_val_predict  # 导入无泄漏交叉验证预测。",
            "features, labels = load_iris(return_X_y=True)  # 加载数据。",
            "predictions = cross_val_predict(RandomForestClassifier(n_estimators=40, max_depth=4, random_state=42), features, labels, cv=5)  # 每个预测都来自未见该样本的折。",
            "matrix = confusion_matrix(labels, predictions)  # 构建混淆矩阵。",
            "report = classification_report(labels, predictions, output_dict=True)  # 获取precision recall F1字典。",
            "assert matrix.sum() == len(labels)  # 验证每个样本被统计一次。",
            "print(matrix, report['macro avg'])  # 输出矩阵和宏平均。",
        ],
        [
            "from sklearn.datasets import load_breast_cancer  # 导入二分类数据。",
            "from sklearn.ensemble import RandomForestClassifier  # 导入分类器。",
            "from sklearn.metrics import average_precision_score, roc_auc_score  # 导入排序指标。",
            "from sklearn.model_selection import cross_val_predict  # 导入交叉验证概率预测。",
            "features, labels = load_breast_cancer(return_X_y=True)  # 加载数据。",
            "probabilities = cross_val_predict(RandomForestClassifier(n_estimators=40, max_depth=5, random_state=42), features, labels, cv=3, method='predict_proba')[:, 1]  # 获取未见样本概率。",
            "roc_auc = roc_auc_score(labels, probabilities)  # 计算ROC AUC。",
            "pr_auc = average_precision_score(labels, probabilities)  # 计算PR曲线平均精度。",
            "assert roc_auc > 0.9 and pr_auc > 0.9  # 验证模型排序能力。",
            "print(roc_auc, pr_auc)  # 输出两种AUC。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "from sklearn.linear_model import LogisticRegression  # 导入分类器。",
            "from sklearn.metrics import balanced_accuracy_score  # 导入平衡准确率。",
            "rng = np.random.default_rng(42)  # 固定随机数。",
            "features = rng.normal(size=(110, 3))  # 创建特征。",
            "labels = np.array([0] * 100 + [1] * 10)  # 创建严重不平衡标签。",
            "features[labels == 1, 0] += 2  # 为少数类加入可学习信号。",
            f"model = LogisticRegression(class_weight='balanced', C={variant}).fit(features, labels)  # 自动按频次设置反比类别权重。",
            "predictions = model.predict(features)  # 生成预测。",
            "score = balanced_accuracy_score(labels, predictions)  # 各类召回率等权平均。",
            "assert score >= 0.5  # 至少不差于随机基准。",
            "print(model.class_weight, score, np.bincount(predictions, minlength=2))  # 输出不平衡结果。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "from sklearn.datasets import load_iris  # 导入分类数据。",
            "from sklearn.tree import DecisionTreeClassifier  # 导入对小样本规模稳定的模型。",
            "from sklearn.model_selection import learning_curve  # 导入学习曲线工具。",
            "features, labels = load_iris(return_X_y=True)  # 加载数据。",
            "sizes, train_scores, valid_scores = learning_curve(DecisionTreeClassifier(max_depth=3, random_state=42), features, labels, train_sizes=[0.5, 0.75, 1.0], cv=3, scoring='accuracy', shuffle=True, random_state=42)  # 在不同训练规模交叉验证。",
            "train_mean = train_scores.mean(axis=1)  # 计算每个规模训练均值。",
            "valid_mean = valid_scores.mean(axis=1)  # 计算每个规模验证均值。",
            "assert len(sizes) == 3 and np.all((0 <= valid_mean) & (valid_mean <= 1))  # 验证曲线shape和范围。",
            "print(sizes, train_mean, valid_mean)  # 输出学习曲线数据。",
        ],
        [
            "import numpy as np  # 导入 NumPy。",
            "from sklearn.datasets import load_iris  # 导入分类数据。",
            "from sklearn.inspection import permutation_importance  # 导入排列重要性。",
            "from sklearn.model_selection import train_test_split  # 导入切分函数。",
            "from sklearn.ensemble import RandomForestClassifier  # 导入随机森林。",
            "features, labels = load_iris(return_X_y=True)  # 加载数据。",
            "train_x, test_x, train_y, test_y = train_test_split(features, labels, stratify=labels, random_state=42)  # 创建独立测试集。",
            "model = RandomForestClassifier(n_estimators=40, random_state=42).fit(train_x, train_y)  # 训练模型。",
            f"importance = permutation_importance(model, test_x, test_y, n_repeats={3 + variant}, random_state=42)  # 在测试集打乱单列测性能下降。",
            "order = np.argsort(importance.importances_mean)[::-1]  # 按平均下降排序。",
            "assert len(order) == features.shape[1]  # 验证每个特征都有结果。",
            "print(order, importance.importances_mean)  # 输出排列重要性。",
        ],
        [
            "from pathlib import Path  # 导入路径工具。",
            "import tempfile  # 导入临时目录工具。",
            "import joblib  # 导入scikit-learn推荐持久化工具。",
            "import numpy as np  # 导入 NumPy。",
            "from sklearn.datasets import load_iris  # 导入数据。",
            "from sklearn.pipeline import make_pipeline  # 导入Pipeline。",
            "from sklearn.preprocessing import StandardScaler  # 导入标准化器。",
            "from sklearn.linear_model import LogisticRegression  # 导入分类器。",
            "features, labels = load_iris(return_X_y=True)  # 加载数据。",
            f"model = make_pipeline(StandardScaler(), LogisticRegression(max_iter=500, random_state={seed})).fit(features, labels)  # 固定随机种子训练完整Pipeline。",
            "expected = model.predict(features[:5])  # 保存前取得基准预测。",
            "with tempfile.TemporaryDirectory() as folder:  # 创建自动清理目录。",
            "    path = Path(folder) / 'pipeline.joblib'  # 定义模型文件路径。",
            "    joblib.dump(model, path)  # 持久化预处理和模型。",
            "    restored = joblib.load(path)  # 只加载可信来源的模型文件。",
            "    actual = restored.predict(features[:5])  # 恢复后重新预测。",
            "assert np.array_equal(expected, actual)  # 验证持久化前后预测一致。",
            "print(actual)  # 输出恢复模型预测。",
        ],
    ]
    return title, task, cases[family]
